Repository h2oai/h2o-3, pull requests merged in 2018-10, with the labels that each got.

#2895 [PUBDEV-5939] Enable configuration of buffers for http/https connection [wright]
  h2o-core/src/main/java/water/AbstractHTTPD.java
  h2o-core/src/main/java/water/H2O.java
Labels: 4RELEASE

#2896 [PUBDEV-5938] Enable loading log4j.properties from classpath [wright]
  h2o-core/src/main/java/water/util/Log.java
Labels: 4RELEASE

#2881 [ITA-344] Build Python package under h2o-py/build/.
  h2o-py/build.gradle
  h2o-py/setup.py
  make-dist.sh
  scripts/install-clients.sh
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/PR_startup_checks.sh
  scripts/jenkins/groovy/defaultStage.groovy
Labels: ITA

#2905 [FLOW-PUBDEV-5954] Update lodash.
  h2o-web/bower.json
Labels: Flow

#2891 [ITA-306] Java 7 tests.
  docker/Jenkinsfile-build-docker
  docker/jenkins-images/Dockerfile-jdk-others
  docker/scripts/install_java_version_local
  docker/scripts/java-7-vars.sh
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
Labels: ITA

#2907 [ITA-347] Remove keys from docker images.
  docker/Jenkinsfile-build-hadoop-docker
  docker/hadoop/cdh/Dockerfile
  docker/hadoop/cdh/scripts/startup/10_hdfs_start
  docker/hadoop/common/sbin/install_hive.sh
  docker/hadoop/hdp/Dockerfile
  docker/hadoop/hdp/scripts/startup/10_hdfs_start
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#2908 ITA-346] Add GBM benchmarks in client mode.
  scripts/jenkins/groovy/benchmarkStage.groovy
  scripts/jenkins/groovy/compareBenchmarksStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2917 [BUILD] Update sphinx-osexample.
  h2o-py/test-requirements.txt
Labels: ITA

#2915 PUBDEV-5962: Add -notify_local flag to User Guide
  h2o-docs/src/product/starting-h2o.rst
Labels: docs

#2913 PUBDEV-5967: Added isWsl() capability.
  h2o-core/src/main/java/water/init/HostnameGuesser.java
  h2o-core/src/main/java/water/util/LinuxProcFileReader.java
  h2o-core/src/main/java/water/util/OSUtils.java
Labels: 4RELEASE

#2911 [ITA-343] Fix build deps.
  gradle.properties
  h2o-assemblies/main/build.gradle
  h2o-bindings/build.gradle
  h2o-docs/build.gradle
  h2o-py/build.gradle
  h2o-r/build.gradle
  h2o-web/build.gradle
Labels: ITA, WIP

#2933 [ITA-349] Add isofor R package.
  docker/scripts/install_R_version
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#2941 added EditorConfig metafile to reduce growth of the indentation mess
  .editorconfig
Labels: please review

#2916 PUBDEV-5743- h2o.xgboost: Add a way to visualize h2o-xgboost trees
  h2o-algos/src/main/java/hex/tree/TreeHandler.java
  h2o-core/build.gradle
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
  h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostRegTree.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTreeConverterTest.java
  h2o-genmodel-extensions/xgboost/build.gradle
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostJavaMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoReader.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostNativeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/drf/DrfMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/gbm/GbmMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraph.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraphConverter.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java
  h2o-genmodel/src/main/java/hex/genmodel/tools/PrintMojo.java
  h2o-py/h2o/tree/tree.py
  h2o-py/tests/testdir_tree/pyunit_xgboost_tree.py
  h2o-r/tests/testdir_jira/runit_pubdev_5743.R
Labels: please review

#2931 PUBDEV-5609: Isolation Forest
  h2o-algos/src/main/java/hex/api/RegisterAlgos.java
  h2o-algos/src/main/java/hex/schemas/IsolationForestModelV3.java
  h2o-algos/src/main/java/hex/schemas/IsolationForestV3.java
  h2o-algos/src/main/java/hex/tree/DTree.java
  h2o-algos/src/main/java/hex/tree/Score.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/main/java/hex/tree/isofor/IsolationForest.java
  h2o-algos/src/main/java/hex/tree/isofor/IsolationForestModel.java
  h2o-algos/src/main/java/hex/tree/isofor/IsolationForestMojoWriter.java
  h2o-algos/src/main/java/hex/tree/isofor/ModelMetricsAnomaly.java
  h2o-algos/src/main/java/water/api/ModelMetricsAnomalyV3.java
  h2o-algos/src/main/resources/META-INF/services/water.api.Schema
  h2o-algos/src/test/java/hex/tree/isofor/IsolationForestTest.java
  h2o-algos/src/test/java/water/ModelSerializationTest.java
  h2o-bindings/bin/gen_R.py
  h2o-bindings/bin/gen_python.py
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelMetrics.java
  h2o-core/src/main/java/hex/ModelMetricsSupervised.java
  h2o-core/src/main/java/hex/ScoreKeeper.java
  h2o-genmodel/src/main/java/hex/ModelCategory.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoFactory.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/isofor/IsolationForestMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/isofor/IsolationForestMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/AnomalyDetectionPrediction.java
  h2o-py/docs/modeling.rst
  h2o-py/h2o/estimators/__init__.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/isolation_forest.py
  h2o-py/h2o/model/anomaly_detection.py
  h2o-py/h2o/model/metrics_base.py
  h2o-py/tests/testdir_algos/isofor/pyunit_isofor_smoke.py
  h2o-r/H2O_Load.R
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/isolationforest.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/testdir_algos/isofor/runit_isofor_accuracy.R
  h2o-r/tests/testdir_algos/isofor/runit_isofor_creditfraud_large.R
  h2o-r/tests/testdir_algos/isofor/runit_isofor_depth.R
  h2o-r/tests/testdir_algos/isofor/runit_isofor_smoke.R
  h2o-r/tests/testdir_jira/runit_pubdev_4711_supported_export_formats.R
  py/testdir_multi_jvm/test_rest_api.py
Labels: 4RELEASE

#2949 PUBDEV-5949: Adding H2O tree class to docs - WIP
  h2o-py/docs/index.rst
  h2o-py/docs/tree.rst
  h2o-r/h2o-package/index.Rmd
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
Labels: docs

#2945 PUBDEV-5988 Add experimental feature flag to the launch option
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/main/java/water/api/AlgoAbstractRegister.java
Labels: 4RELEASE, please review

#2939 PUBDEV-5982: Documentation for Isolation Forest - DO NOT MERGE
  h2o-docs/src/product/cross-validation.rst
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/algo-params/build_tree_one_node.rst
  h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
  h2o-docs/src/product/data-science/algo-params/col_sample_rate_change_per_level.rst
  h2o-docs/src/product/data-science/algo-params/col_sample_rate_per_tree.rst
  h2o-docs/src/product/data-science/algo-params/ignore_const_cols.rst
  h2o-docs/src/product/data-science/algo-params/ignored_columns.rst
  h2o-docs/src/product/data-science/algo-params/keep_cross_validation_fold_assignment.rst
  h2o-docs/src/product/data-science/algo-params/keep_cross_validation_models.rst
  h2o-docs/src/product/data-science/algo-params/keep_cross_validation_predictions.rst
  h2o-docs/src/product/data-science/algo-params/max_depth.rst
  h2o-docs/src/product/data-science/algo-params/max_runtime_secs.rst
  h2o-docs/src/product/data-science/algo-params/min_rows.rst
  h2o-docs/src/product/data-science/algo-params/mtries.rst
  h2o-docs/src/product/data-science/algo-params/ntrees.rst
  h2o-docs/src/product/data-science/algo-params/sample_rate.rst
  h2o-docs/src/product/data-science/algo-params/score_each_iteration.rst
  h2o-docs/src/product/data-science/algo-params/score_tree_interval.rst
  h2o-docs/src/product/data-science/algo-params/seed.rst
  h2o-docs/src/product/data-science/if.rst
  h2o-docs/src/product/grid-search.rst
Labels: docs

#2937 PUBDEV-5775: Combine two or more models into a single MOJO model pipeline
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelMojoWriter.java
  h2o-core/src/main/java/water/api/StreamWriter.java
  h2o-core/src/main/java/water/init/AbstractBuildVersion.java
  h2o-genmodel/src/main/java/hex/genmodel/AbstractMojoWriter.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelDescriptor.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoFactory.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoPipelineBuilder.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoPipelineWriter.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoReaderBackendFactory.java
  h2o-genmodel/src/main/java/hex/genmodel/MultiModelMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/pipeline/MojoPipeline.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/pipeline/MojoPipelineReader.java
  h2o-genmodel/src/main/java/hex/genmodel/tools/BuildPipeline.java
  h2o-genmodel/src/main/java/hex/genmodel/utils/IOUtils.java
  h2o-genmodel/src/test/java/hex/genmodel/MojoPipelineBuilderTest.java
  h2o-genmodel/src/test/resources/hex/genmodel/algos/pipeline/glm_model.zip
  h2o-genmodel/src/test/resources/hex/genmodel/algos/pipeline/kmeans_model.zip
Labels: 4RELEASE

#2953 [BUILD] Increased JUnit timeouts to 3h.
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2964 [PUBDEV-6005] added XGBoost to list of algos that can be excluded in Flow.
  h2o-web/bower.json
Labels: Flow

#2960 PUBDEV-5820: Introduced composition-based extension mechanism for servlet handlers
  h2o-core/src/main/java/water/ExtensionManager.java
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/main/java/water/JettyHTTPD.java
  h2o-core/src/main/java/water/server/RequestAuthExtension.java
Labels: 4RELEASE, please review

#2958 PUBDEV-6002: change naming format for models in AutoML and grids to start index at 1
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-docs/src/product/automl.rst
Labels: 4RELEASE

#2961 PUBDEV-6000: AutoML auto-split frame from 80/20 to 90/10
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-docs/src/product/automl.rst
Labels: 4RELEASE

#2974 [BUILD] Fix conda build.
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: ITA

#2975 PUBDEV-6002: Fix Py test utility relying on model build index extracting from grid naming convention
  h2o-py/tests/pyunit_utils/utilsPY.py
Labels: 4RELEASE

#2957 PUBDEV-5955 & PUBDEV-6004 StackedEnsemble Mojo categorical index out of range
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/ensemble/StackedEnsembleMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/ensemble/StackedEnsembleMojoReader.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/ensemble/StackedEnsembleBinomialMojoTest.java
  h2o-genmodel/src/test/resources/hex/genmodel/algos/ensemble/binomial_titanic.zip
Labels: 4RELEASE, please review

#2967 multi-node XGBoost is no longer beta
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/starting-h2o.rst
Labels: 4RELEASE

#2982 [BUILD] Update expected benchmarks results.
  scripts/jenkins/groovy/compareBenchmarksStage.groovy
Labels: ITA

#2984 [BUILD] Fix PyPI, minor changes.
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: ITA

#2983 Fix model export issue
  h2o-core/src/main/java/water/AutoBuffer.java
  h2o-core/src/main/java/water/FetchClazzes.java
Labels: 4RELEASE

#2988 Py-Docs: Adding index entry for TargetEncoder so that it appears in t…
  h2o-py/docs/frame.rst
  h2o-py/h2o/targetencoder.py
Labels: docs

#2991 PUBDEV-6025-relxia: Py-Docs - Adding index entry for TargetEncoder so…
  h2o-py/docs/frame.rst
  h2o-py/h2o/targetencoder.py
Labels: docs

#2993 PUBDEV-5313: Update categorical_encoding default value in XGBoost
  h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#2994 PUBDEV-5313-relxia: Update categorical_encoding default value in XGBoost
  h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#2995 PUBDEV-6016: Update DRF FAQ for NAs seen in training
  h2o-docs/src/product/data-science/drf.rst
Labels: docs

#2996 PUBDEV-6016-relxia: Update DRF FAQ for NAs seen in training
  h2o-docs/src/product/data-science/drf.rst
Labels: docs
