Repository h2oai/h2o-3, pull requests merged in 2018-09, with the labels that each got.

#2821 PUBDEV-5857: Generated Model Jar available on Flow Admin menu
  h2o-docs/src/product/api-reference.rst
  h2o-docs/src/product/faq/java.rst
  h2o-docs/src/product/flow.rst
  h2o-docs/src/product/images/Flow_assist.png
Labels: docs

#2833 [FLOW-PUBDEV-5748] Generate CM for predictions.
  h2o-web/bower.json
Labels: Flow

#2834 [WRI-FLOW-PUBDEV-5748] Generate CM for predictions.
  h2o-web/bower.json
Labels: Flow

#2838 [ITA-337] Java 11 Smoke tests.
  docker/Dockerfile.jenkins
  docker/scripts/install_java_version
  h2o-algos/testMultiNode.sh
  h2o-algos/testSSL.sh
  h2o-algos/testSingleNode.sh
  h2o-algos/testSingleNodeOneProc.sh
  h2o-core/testClientNode.sh
  h2o-core/testMultiNode.sh
  h2o-extensions/jython-cfunc/testMultiNode.sh
  h2o-extensions/jython-cfunc/testSingleNode.sh
  h2o-extensions/xgboost/testMultiNode.sh
  h2o-extensions/xgboost/testSingleNode.sh
  h2o-parsers/h2o-avro-parser/testMultiNode.sh
  h2o-parsers/h2o-orc-parser/testMultiNode.sh
  h2o-parsers/h2o-parquet-compat/h2o-parquet-v17-compat/testMultiNode.sh
  h2o-parsers/h2o-parquet-parser/testMultiNode.sh
  h2o-persist-gcs/testMultiNode.sh
  h2o-persist-hdfs/testMultiNode.sh
  h2o-persist-http/testMultiNode.sh
  h2o-persist-s3/testMultiNode.sh
  h2o-scala/testMultiNode.sh
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2846 PUBDEV-5910: Doc update to MOJOs (rel-wright branch)
  h2o-docs/src/product/productionizing.rst
  h2o-genmodel/src/main/java/overview.html
Labels: docs

#2845 PUBDEV-5910: Doc update to MOJOs
  h2o-docs/src/product/mojo-quickstart.rst
  h2o-genmodel/src/main/java/overview.html
Labels: docs

#2844 [WRI-ITA-333] Use AWS CLI for release upload to S3.
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/insideDocker.groovy
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: ITA

#2858 [ITA-337] Add JUnit 11 tests.
  h2o-test-integ/build.gradle
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/run.py
Labels: ITA

#2852 [WRI-ITA] Move Dockerfile. Java 11 Smoke Tests. Gradle 4.10
  build.gradle
  docker/Dockerfile
  docker/Dockerfile.jenkins
  docker/Jenkinsfile-build-docker
  docker/scripts/install_R_version
  docker/scripts/install_java_version
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  h2o-algos/testMultiNode.sh
  h2o-algos/testSSL.sh
  h2o-algos/testSingleNode.sh
  h2o-algos/testSingleNodeOneProc.sh
  h2o-core/testClientNode.sh
  h2o-core/testMultiNode.sh
  h2o-extensions/jython-cfunc/testMultiNode.sh
  h2o-extensions/jython-cfunc/testSingleNode.sh
  h2o-extensions/xgboost/testMultiNode.sh
  h2o-extensions/xgboost/testSingleNode.sh
  h2o-parsers/h2o-avro-parser/testMultiNode.sh
  h2o-parsers/h2o-orc-parser/testMultiNode.sh
  h2o-parsers/h2o-parquet-compat/h2o-parquet-v17-compat/testMultiNode.sh
  h2o-parsers/h2o-parquet-parser/testMultiNode.sh
  h2o-persist-gcs/testMultiNode.sh
  h2o-persist-hdfs/testMultiNode.sh
  h2o-persist-http/testMultiNode.sh
  h2o-persist-s3/testMultiNode.sh
  h2o-scala/testMultiNode.sh
  h2o-test-integ/build.gradle
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/run.py
Labels: ITA, WIP

#2866 [ITA] Use docker image with roxygen2 4.1.1.
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#2869 [ITA] Use gpu lable for xgboost smoke tests.
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#2785 PUBDEV-5855 - Error when parsing double quotations in a column (rel-wright)
  h2o-core/src/main/java/water/parser/BufferedString.java
  h2o-core/src/main/java/water/parser/CharSkippingBufferedString.java
  h2o-core/src/main/java/water/parser/CsvParser.java
  h2o-core/src/main/java/water/parser/Parser.java
  h2o-core/src/test/java/water/parser/CharSkippingBufferedStringTest.java
  h2o-core/src/test/java/water/parser/CsvParserTest.java
  h2o-core/src/test/java/water/parser/ParserTest2.java
  h2o-py/tests/testdir_parser/pyunit_csv_parser.py
Labels: 4RELEASE

#2874 [ITA-342] Test different Python version in nightly only.
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2875 [WRI-ITA-342] Test different Python version in nightly only.
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2878 [ITA] Fix release pipeline.
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: ITA

#2880 [ITA] Fix release pipeline.
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: ITA

#2863 [ITA-341] Multiple images used to test H2O-3.
  docker/Dockerfile.jenkins
  docker/Jenkinsfile-build-docker
  docker/hadoop/cdh/Dockerfile
  docker/hadoop/hdp/Dockerfile
  docker/jenkins-images/Dockerfile-base
  docker/jenkins-images/Dockerfile-build
  docker/jenkins-images/Dockerfile-build-base
  docker/jenkins-images/Dockerfile-build-hadoop
  docker/jenkins-images/Dockerfile-jdk-8-base
  docker/jenkins-images/Dockerfile-jdk-others
  docker/jenkins-images/Dockerfile-jdk-others-base
  docker/jenkins-images/Dockerfile-python
  docker/jenkins-images/Dockerfile-python-base
  docker/jenkins-images/Dockerfile-r
  docker/jenkins-images/Dockerfile-r-base
  docker/jenkins-images/Dockerfile-release
  docker/scripts/build-h2o-3
  docker/scripts/install_R_version
  docker/scripts/install_java_version
  docker/scripts/install_java_versions
  docker/scripts/install_python_version
  docker/scripts/java-10-vars.sh
  docker/scripts/java-11-vars.sh
  docker/scripts/java-8-vars.sh
  h2o-py/test-requirements.txt
  scripts/jenkins/groovy/benchmarkStage.groovy
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/buildH2O3.groovy
  scripts/jenkins/groovy/defaultStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/hadoopStage.groovy
  scripts/jenkins/groovy/insideDocker.groovy
  scripts/jenkins/groovy/makeTarget.groovy
  scripts/jenkins/groovy/pipelineContext.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
  scripts/jenkins/jenkinsfiles/Jenkinsfile
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Coverage
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Hadoop
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Single-Test
  scripts/jenkins/jenkinsfiles/Jenkinsfile-XGB
Labels: ITA

#2883 [PUBDEV-5932] Use pandas in pyunit_ecology_gbm.py
  h2o-py/tests/testdir_algos/gbm/pyunit_ecology_gbm.py
Labels: WIP

#2892 [ITA] :fire: revert docker images to v1.
  h2o-py/test-requirements.txt
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA
