Repository h2oai/h2o-3, pull requests merged in 2018-08, with the labels that each got.

#2710 [WRI] Update Flow to 0.7.34.
  h2o-web/bower.json
Labels: 4RELEASE, Flow

#2711 PUBDEV-5810: Note that class_sampling_factors requires balance_classes to be enabled.
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/class_sampling_factors.rst
  h2o-docs/src/product/data-science/algo-params/solver.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/naive-bayes.rst
Labels: docs

#2709 [WRI-PUBDEV-5813] Add AutoML test for Flow.
  h2o-docs/src/product/flow/packs/test-small/automl_prostate.flow
  h2o-docs/src/product/flow/packs/test-small/index.list
Labels: 4RELEASE, Flow

#2680 PUBDEV-5613: AutoML (and all models) should respect max_runtime_secs
  h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
  h2o-automl/src/main/java/ai/h2o/automl/UserFeedback.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/water/Job.java
  h2o-core/src/main/java/water/util/ArrayUtils.java
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-r/tests/testdir_algos/automl/runit_automl_args.R
Labels: core

#2719 [FLOW-PUBDEV-5813] Add AutoML test for Flow.
  h2o-docs/src/product/flow/packs/test-small/automl_prostate.flow
  h2o-docs/src/product/flow/packs/test-small/index.list
Labels: Flow

#2722 [FLOW-PUBDEV-5793] Fix ignored columns in AutoML.
  h2o-web/bower.json
Labels: Flow

#2729 [ITA-327] Add mojo-compatibility stage.
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2732 [WRI-ITA-327] Add mojo-compatibility stage.
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2735 PUBDEV-4590: Add Scala example to Stacked Ensemble chapter
  h2o-docs/src/product/data-science/stacked-ensembles.rst
Labels: docs

#2708 PUBDEV-5812: Add terminal node ids to model outputs in MOJO
  h2o-algos/src/main/java/hex/tree/CompressedTree.java
  h2o-algos/src/main/java/hex/tree/DTree.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/main/java/hex/tree/drf/DrfMojoWriter.java
  h2o-algos/src/main/java/hex/tree/gbm/GbmMojoWriter.java
  h2o-algos/src/test/java/hex/tree/CompressedTreeTest.java
  h2o-core/src/main/java/hex/Model.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraph.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/BinomialModelPrediction.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/MultinomialModelPrediction.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/RegressionModelPrediction.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/gbm/GbmMojoModelTest.java
Labels: core

#2740 [ITA-322] Fix R Docs.
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/defaultStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2742 [WRI-ITA-322] Fix R Docs.
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/defaultStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#2748 PUBDEV-5839: Update "Docker Users" topic in the User Guide
  h2o-docs/src/product/mojo-quickstart.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#2736 PUBDEV-5789: cleaner message after failure to locally start server
  h2o-core/src/main/java/water/H2O.java
  h2o-r/h2o-package/R/connection.R
  h2o-r/tests/testdir_jira/runit_pubdev_5789.R
Labels: R

#2744 PUBDEV-5789: simplified R user experience when facing java version issue
  h2o-core/src/main/java/water/H2O.java
  h2o-r/h2o-package/R/connection.R
  h2o-r/tests/testdir_jira/runit_pubdev_5789.R
Labels: R

#2745 PUBDEV-5786 - GLM Coordinate descent should only be disabled for mult…
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
  h2o-algos/src/test/java/hex/glm/GLMBasicTestRegression.java
  h2o-algos/src/test/java/hex/glm/GLMTest.java
  h2o-py/tests/testdir_algos/glm/pyunit_solvers_glm.py
Labels: 4RELEASE

#2751 Adding the changes/fixes to GLRM from master to rel-wright for fixed-release.
  h2o-algos/src/main/java/hex/glrm/GLRM.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoModel.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/glrm/GlrmMojoModelTest.java
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/archetypes
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d000.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d001.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d002.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d003.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d004.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d005.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d006.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/domains/d007.txt
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/experimental/README.md
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/experimental/modelDetails.json
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/losses
  h2o-genmodel/src/test/resources/hex/genmodel/algos/glrm/model.ini
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_algos/glrm/pyunit_PUBDEV_5776_glrm_fix_new_enum_level.py
  h2o-py/tests/testdir_algos/glrm/pyunit_pubdev_5493_glrm_seed.py
Labels: 4RELEASE

#2764 PUBDEV-5838: Update solver documentation
  h2o-docs/src/product/data-science/algo-params/solver.rst
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#2765 PUBDEV-5838-relwright: Update solver documentation
  h2o-docs/src/product/data-science/algo-params/solver.rst
  h2o-docs/src/product/data-science/glm.rst
Labels: 4RELEASE, docs

#2757 PUBDEV-5803 fixed bug in setting http headers
  h2o-r/h2o-package/R/communication.R
Labels: R

#2762 PUBDEV-5803 fixed bug in setting http headers
  h2o-r/h2o-package/R/communication.R
Labels: R

#2741 Pubdev 5826 glrm predict mojo mismatch
  h2o-algos/src/main/java/hex/glrm/GLRMGenX.java
  h2o-algos/src/main/java/hex/glrm/GLRMModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/utils/ParseUtils.java
  h2o-genmodel/src/test/java/hex/genmodel/utils/ParseUtilsTest.java
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_javapredict/pyunit_pubdev_5826_glrm_predict_large.py
Labels: 4RELEASE

#2771 PUBDEV-5836: Doc update to Hive2 JDBC section
  h2o-dist/index.html
  h2o-docs/src/product/downloading.rst
  h2o-docs/src/product/getting-data-into-h2o.rst
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
Labels: docs

#2772 PUBDEV-5836-relwright: Doc update to Hive2 JDBC section (rel-wright)
  h2o-dist/index.html
  h2o-docs/src/product/downloading.rst
  h2o-docs/src/product/getting-data-into-h2o.rst
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
Labels: 4RELEASE, docs

#2775 PUBDEV-5847: H2O parses only part of file when reading from compressed HTTP [wright]
  h2o-persist-http/src/main/java/water/persist/PersistHTTP.java
  h2o-persist-http/src/test/java/water/persist/PersistHTTPTest.java
Labels: 4RELEASE

#2776 Use quotes around colorama>0.3.8
  h2o-dist/index.html
  h2o-docs/src/product/downloading.rst
Labels: docs

#2777 Use quotes around colorama>0.3.8 (rel-wright)
  h2o-dist/index.html
  h2o-docs/src/product/downloading.rst
Labels: 4RELEASE, docs

#2749 PUBDEV-5792: Parsing large numbers (2E19) can cause the parser to hang
  h2o-core/src/main/java/water/fvec/NewChunk.java
  h2o-core/src/main/java/water/parser/FVecParseWriter.java
  h2o-core/src/test/java/water/parser/FVecParseWriterTest.java
Labels: 4RELEASE

#2768 PUBDEV-5851: AstFillNA Rapids expression should throw H2O.unimp() on backward method [wright]
  h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstFillNA.java
  h2o-core/src/test/java/water/rapids/ast/prims/advmath/AstFillNATest.java
Labels: 4RELEASE

#2725 PUBDEV-5756: Add Python example to cross-validation topic
  h2o-docs/src/product/cross-validation.rst
Labels: docs

#2790 [FLOW-PUBDEV-5822] Add Download Gen Model button to Admin Menu.
  h2o-web/bower.json
Labels: Flow

#2791 PUBDEV-5848: error when manipulating previous AutoML leaderboard after multiple runs
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_multiple_runs.R
Labels: 4RELEASE

#2796 PUBDEV-5841: Properly dispose all XGBoost native memory
  h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
  h2o-core/src/main/java/hex/Model.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostMojoWriter.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostOutput.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
  h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostModelInfo.java
  h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
  h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdateTask.java
  h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdater.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostNativeMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/BoosterHelper.java
Labels: 4RELEASE, CRITICAL

#2805 Update the docs site in h2o-3 repo to match live site (master)
  h2o-docs/src/front/index.html
Labels: docs

#2806 Update the docs site in h2o-3 repo to match live site (rel-wright)
  h2o-docs/src/front/index.html
Labels: docs

#2807 Fixed link to SW product page; added link to H2O4GPU product page
  h2o-docs/src/front/index.html
Labels: docs
