Repository h2oai/h2o-3, pull requests merged in 2018-12, with the labels that each got.

#3104 [BENCHMARK] Add GLM benchmarks.
  scripts/jenkins/groovy/compareBenchmarksStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#3092 PUBDEV-5820 - Added Jetty 9 implementation of IFacade
  build.gradle
  h2o-core/src/test/java/water/api/CustomHttpFilterTest.java
  h2o-jetty-9/build.gradle
  h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9DelegatingAuthenticator.java
  h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Facade.java
  h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Helper.java
  h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9ProxyServerAdapter.java
  h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9ServerAdapter.java
  h2o-jetty-9/src/main/java/water/webserver/jetty9/TransparentProxyServlet.java
  h2o-jetty-9/src/main/resources/META-INF/services/water.webserver.iface.HttpServerFacade
  scripts/jenkins/Makefile.jenkins
  settings.gradle
Labels: please review

#3102 PUBDEV-6030 get reconstruction error for auto encoders from easy wrapper
  h2o-algos/src/test/java/hex/deeplearning/DeepLearningAutoEncoderCategoricalTest.java
  h2o-algos/src/test/java/hex/deeplearning/DeepLearningAutoEncoderTest.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/deeplearning/DeeplearningMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/AutoEncoderModelPrediction.java
Labels: please review

#3132 [flow] update to 0.9.2
  h2o-web/bower.json
Labels: Flow

#3125 Fix code generators to no longer generate trailing spaces
  h2o-bindings/bin/gen_R.py
  h2o-r/h2o-package/R/stackedensemble.R
Labels: please review

#3127 [HEXDEV-717] add kerberos login to hadoop tests
  docker/Jenkinsfile-build-hadoop-docker
  docker/hadoop/cdh/Dockerfile
  docker/hadoop/cdh/Dockerfile.kerberos
  docker/hadoop/common/sbin/krb-edit-hadoop-confs.sh
  docker/hadoop/common/sbin/krb-init-kadmin.sh
  docker/hadoop/hdp/Dockerfile
  docker/hadoop/hdp/Dockerfile.kerberos
  docker/scripts/install_python_version
  h2o-py/scripts/h2o-py-test-setup.py
  h2o-py/test-requirements.txt
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/config/kerberos.conf
  scripts/jenkins/config/kerberos.properties
  scripts/jenkins/config/ldap.txt
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/hadoopStage.groovy
  scripts/run.py
Labels: please review

#3139 Remove -output hdfsOutputDirName when starting Hadoop
  h2o-dist/index.html
  h2o-docs/src/product/downloading.rst
Labels: docs

#3142 HEXDEV-725: fix bit order in explanatory comments for byte arrays
  h2o-core/src/main/java/water/util/IcedBitSet.java
  h2o-core/src/test/java/water/util/IcedBitSetTest.java
  h2o-core/src/test/java/water/util/IcedBitSetUnitTest.java
Labels: please review

#3144 PUBDEV-4377: Add to docs that for binary models, labels are created b…
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3145 PUBDEV-6105: Doc update for enum_limited
  h2o-docs/src/product/data-science/aggregator.rst
  h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#3100 PUBDEV-6097 - Jetty 8 updated to version 8.1.21.v20160908
  gradle.properties
  h2o-jetty-8/build.gradle
Labels: please review

#3138 Removed is_train_or_valid parameter from Target encoding
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoder.java
  h2o-automl/src/main/java/water/rapids/ast/prims/mungers/AstTargetEncoderTransform.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingAirlinesBenchmark.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingExceptionsHandlingTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingImmutabilityTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingKFoldStrategyTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingLeaveOneOutStrategyTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingMultiClassTargetTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingNoneStrategyTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingTitanicBenchmark.java
  h2o-py/h2o/targetencoder.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_gbm_target_encoding.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py
Labels: WIP

#3148 HEXDEV-725 fixed bit ordering in IcedBitSet
  h2o-core/src/main/java/water/util/IcedBitSet.java
  h2o-core/src/test/java/water/util/IcedBitSetTest.java
  h2o-core/src/test/java/water/util/IcedBitSetUnitTest.java
Labels: please review

#3058 PUBDEV-5236 add the missing transform method
  h2o-bindings/bin/gen_python.py
  h2o-py/h2o/estimators/pca.py
  h2o-py/h2o/transforms/decomposition.py
  h2o-py/tests/testdir_pipeline/pyunit_scale_pca_rf.py
  h2o-py/tests/testdir_scikit_grid/pyunit_scal_pca_rf_grid.py
Labels: API, python

#3155 [PUBDEV-6147] Fix download links.
  h2o-web/bower.json
Labels: Flow

#3097 PUBDEV-5865: Add monotonicity constraints to H2O GBM
  .gitignore
  h2o-algos/src/main/java/hex/schemas/GBMV3.java
  h2o-algos/src/main/java/hex/tree/Constraint.java
  h2o-algos/src/main/java/hex/tree/Constraints.java
  h2o-algos/src/main/java/hex/tree/DTree.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/main/java/hex/tree/TreeUtils.java
  h2o-algos/src/main/java/hex/tree/drf/DRF.java
  h2o-algos/src/main/java/hex/tree/gbm/GBM.java
  h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
  h2o-algos/src/main/java/hex/tree/isofor/IsolationForest.java
  h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
  h2o-core/src/main/java/hex/VarImp.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-py/demos/H2O_tutorial_gbm_monotonicity.ipynb
  h2o-py/h2o/estimators/gbm.py
  h2o-r/h2o-package/R/gbm.R
  h2o-r/tests/testdir_algos/gbm/runit_gbm_monotone.R
Labels: 4RELEASE, please review

#3159 PUBDEV-6107 - Regression XGBoost tree retrieval no-class validation fixed
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTreeConverterTest.java
Labels: 4RELEASE

#3151 PUBDEV-6122 - Add a parameter to pdp to save the plot
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_misc/pyunit_pubdev_5706_usersplits_pdp.py
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_jira/runit_pubdev_6122.R
Labels: 4RELEASE, please review

#3152 HEXDEV-726: Improve performance of Grid Search in client mode (for SW)
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/test/java/water/RemoteRunnableTest.java
Labels: 4RELEASE

#3157 PUBDEV-4377: Add more info regarding the prediction threshold as requ…
  h2o-docs/src/product/performance-and-prediction.rst
Labels: 4RELEASE, docs

#3161 PUBDEV-6148: Add monotone_constraints parameter to list of GBM parame…
  h2o-docs/src/product/data-science/gbm.rst
Labels: 4RELEASE, docs

#3162 updated formatting for h2o.init parameters. indented descriptions.
  h2o-py/h2o/h2o.py
Labels: 4RELEASE

#3160 PUBDEV-6111 Fixed euclidean distance formula in AstDistance rapids expression
  h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstDistance.java
  h2o-core/src/test/java/water/rapids/RapidsTest.java
Labels: 4RELEASE

#3169 Docs: Removed duplicate "benefits" section
  h2o-docs/src/product/mojo-quickstart.rst
Labels: docs

#3170 PUBDEV-6152: NPE when building SE during AutoML reruns in some corner cases
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
Labels: 4RELEASE

#3177 PUBDEV-6156: Default value for reg_lambda is now 1.
  h2o-docs/src/product/data-science/xgboost.rst
Labels: 4RELEASE, docs

#3178 PUBDEV-6048: New stopping_metric options
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/flow.rst
Labels: 4RELEASE, docs

#3165 PUBDEV-6153: Add support for Cloudera Hadoop 6.1
  docker/hadoop/cdh/Dockerfile
  docker/hadoop/cdh/scripts/startup/50_hive_start
  docker/hadoop/common/startup/50_hive_start
  h2o-dist/buildinfo.json
  h2o-hadoop-3/h2o-cdh6.1-assembly/build.gradle
  make-dist.sh
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/hadoopStage.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
  settings.gradle
Labels: please review

#3105 [Experimental] Allows to use MOJO2 Pipelines to transform H2O Frames
  build.gradle
  gradle.properties
  h2o-app/build.gradle
  h2o-extensions/mojo-pipeline/build.gradle
  h2o-extensions/mojo-pipeline/src/main/java/hex/mojopipeline/MojoPipeline.java
  h2o-extensions/mojo-pipeline/src/main/java/hex/mojopipeline/MojoPipelineExtension.java
  h2o-extensions/mojo-pipeline/src/main/java/hex/mojopipeline/rapids/AstPipelineTransform.java
  h2o-extensions/mojo-pipeline/src/main/resources/META-INF/services/water.AbstractH2OExtension
  h2o-extensions/mojo-pipeline/src/main/resources/META-INF/services/water.rapids.ast.AstPrimitive
  h2o-extensions/mojo-pipeline/src/test/java/hex/mojopipeline/MojoPipelineTest.java
  h2o-extensions/mojo-pipeline/testSingleNode.sh
  h2o-py/h2o/pipeline/__init__.py
  h2o-py/h2o/pipeline/mojo_pipeline.py
  h2o-py/tests/testdir_misc/pyunit_mojo_pipeline.py
  scripts/jenkins/Makefile.jenkins
  settings.gradle
Labels: please review
