Repository h2oai/h2o-3, pull requests merged in 2018-04, with the labels that each got.

#2210 [PUBDEV-5424] MOJO scoring on a CSV or data frame in R.
  h2o-py/h2o/utils/shared_utils.py
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/R/predict.R
  h2o-r/tests/testdir_javapredict/runit_mojo_predict.R
Labels: WIP

#2253 Disabled GCS AUTH module checks during test startup
  scripts/jenkins/Makefile.jenkins
Labels: please review

#2258 PUBDEV-5453 (rel-wolpert): Updated docs site
  h2o-docs/src/front/assets/images/label_gray.png
  h2o-docs/src/front/assets/images/label_yellow.png
  h2o-docs/src/front/index.html
Labels: docs

#2259 PUBDEV-5453 (master): Updated docs site
  h2o-docs/src/front/assets/images/label_gray.png
  h2o-docs/src/front/assets/images/label_yellow.png
  h2o-docs/src/front/index.html
Labels: docs

#2264 PUBDEV-5457 (rel-wolpert): Fix links to POJO/MOJO topics in GBM FAQ Scoring section
  h2o-docs/src/product/data-science/gbm-faq/scoring.rst
  h2o-docs/src/product/productionizing.rst
Labels: docs

#2297 SW Recent Changes links now point to the user guide instead of github
  h2o-docs/src/front/index.html
Labels: docs

#2296 SW Recent Changes links now point to the user guide instead of github (rel-wolpert)
  h2o-docs/src/front/index.html
Labels: docs

#2295 PUBDEV-5473: Add offset field to predictBinomial Easy wrapper.
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
Labels: 4RELEASE

#2303 PUBDEV 5321 - A simple numerical comparison of native XGBoost and H2O…
  h2o-py/tests/testdir_algos/xgboost/numerical_test.py
Labels: 4RELEASE

#2281 PUBDEV-5321 - A simple numerical comparison of native XGBoost and H2O…
  h2o-py/tests/testdir_algos/xgboost/numerical_test.py
Labels: WIP

#2312 Removed links to SW 2.0 docs
  h2o-docs/src/front/index.html
Labels: docs

#2315 NO_GCS_CHECK environment variable set for all relevant tests in Jenki…
  h2o-persist-gcs/testMultiNode.sh
  scripts/jenkins/Makefile.jenkins
Labels: please review

#2301 [ITA-279] Add benchmarks of xgb-vanilla.
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/benchmarkStage.groovy
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/buildH2O3.groovy
  scripts/jenkins/groovy/defaultStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/pipelineContext.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
Labels: WIP

#2319 PUBDEV-5474: Update h2o-3 version in install docs
  h2o-docs/src/product/cloud-integration/gcs.rst
  h2o-docs/src/product/cloud-integration/nimbix.rst
  h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/downloading.rst
  h2o-docs/src/product/starting-h2o.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#2340 PUBDEV-5476 - Expose offset column in EasyPredictModelWrapper
  h2o-genmodel/build.gradle
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/EasyPredictModelWrapperTest.java
Labels: please review

#2347 PUBDEV-5505 - Closing Rabit connection after communication ends
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/rabit/RabitTrackerH2O.java
Labels: please review
