Repository h2oai/h2o-3, pull requests merged in 2018-05, with the labels that each got.

#2359 PUBDEV-5513: Adding info to docs about disabling XGBoost
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#2361 PUBDEV-5509: Documentation for XGBoost MOJOs with Maven
  h2o-docs/src/product/images/gbm_mojo_graph.png
  h2o-docs/src/product/productionizing.rst
  h2o-genmodel/src/main/java/overview.html
Labels: docs

#2358 PUBDEV-5524 - XGBoost - Check failed: param.max_depth < 16 Tree depth…
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostModelTest.java
Labels: please review

#2383 Docs: Updates to GLM ordinal regression equation in UG and booklet
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/product/conf.py
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#2390 Time allowed in Response variable
  h2o-core/src/main/java/hex/ModelBuilder.java
Labels: please review

#2393 Response variable time type allowed (wolpert)
  h2o-core/src/main/java/hex/ModelBuilder.java
Labels: 4RELEASE

#2402 Fix for adding Double.NaN to IntAryVisitor via addValue().
  h2o-core/src/main/java/water/fvec/ChunkVisitor.java
Labels: enhancement, please review

#2404 PUBDEV-5557 - XGBoost dense matrix memory allocation failure
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
Labels: CRITICAL

#2414 PUBDEV-5565: Disable Version Check in H2O-3
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/main/java/water/api/AboutHandler.java
  h2o-core/src/main/java/water/init/AbstractBuildVersion.java
Labels: 4RELEASE

#2413 PUBDEV-5559: Remove all Google Analytics completely
  h2o-core/build.gradle
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/main/java/water/api/RequestServer.java
  h2o-core/src/main/java/water/parser/ParseDataset.java
  h2o-core/src/main/java/water/util/GAUtils.java
Labels: 4RELEASE

#2418 [PUBDEV-5568] Remove GA from docs page.
  h2o-docs/template/index.html
  h2o-docs/template/rest-api-reference.html
Labels: 4RELEASE

#2415 Remove GA from JS scripts.
  h2o-core/src/main/resources/www/h2o/js/ga.js
  h2o-core/src/main/resources/www/h2o/js/ga.release.js
  h2o-core/src/main/resources/www/page.html
  h2o-dist/index-old.html
  h2o-dist/index.html
Labels: 4RELEASE

#2411 PUBDEV-5545: Added section for enforcing system-level commas-line arguments in h2odriver
  h2o-docs/src/front/index.html
  h2o-docs/src/product/api-reference.rst
  h2o-docs/src/product/security.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#2427 PUBDEV-5578: Added info about setting -extramempercent higher when running xgboost on hadoop.
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#2428 PUBDEV-5494: Added data munging topic for target encoding
  h2o-docs/src/product/data-munging.rst
  h2o-docs/src/product/data-munging/target-encoding.rst
  h2o-docs/src/product/images/gbm_variable_importance1.png
  h2o-docs/src/product/images/gbm_variable_importance2.png
Labels: docs

#2439 make built front page match docs site
  h2o-docs/src/front/index.html
Labels: docs
