Repository h2oai/h2o-3, pull requests merged in 2019-02, with the labels that each got.

#3256 PUBDEV-6231 Deep Learning mojo predict bug
  h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
  h2o-algos/src/main/java/hex/deeplearning/Neurons.java
  h2o-genmodel/src/test/java/hex/genmodel/GenModelTest.java
  h2o-py/tests/testdir_javapredict/pyunit_pubdev_6231_deeplearning_mojo_pojo_large.py
Labels: please review

#3238 PUBDEV-6188 - Dynamic S3 credentials
  h2o-core/src/main/java/water/api/RequestServer.java
  h2o-persist-s3/src/main/java/water/persist/IcedS3Credentials.java
  h2o-persist-s3/src/main/java/water/persist/PersistS3.java
  h2o-persist-s3/src/main/java/water/persist/PersistS3CredentialsV3.java
  h2o-persist-s3/src/main/java/water/persist/PersistS3Handler.java
  h2o-persist-s3/src/main/java/water/persist/RegisterRestApi.java
  h2o-persist-s3/src/main/resources/META-INF/services/water.api.RestApiExtension
  h2o-persist-s3/src/main/resources/META-INF/services/water.api.Schema
  h2o-persist-s3/src/test/java/water/persist/PersistS3HandlerTest.java
  h2o-persist-s3/src/test/java/water/persist/PersistS3Test.java
  h2o-py/h2o/persist/__init__.py
  h2o-py/h2o/persist/persist.py
  h2o-py/tests/testdir_persist/pyunit_persistence.py
  h2o-r/h2o-package/R/import.R
  h2o-r/tests/testdir_persist/runit_pubdev_6188.R
Labels: please review

#3271 PUBDEV-6253: Note that stopping_metric=custom,custom_increasing aren't available in R
  h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
  h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-r/h2o-package/R/gbm.R
  h2o-r/h2o-package/R/randomforest.R
Labels: docs

#3278 PUBDEV-6032: Note in docs that POJO/MOJO cannot parse double quoted columns
  h2o-docs/src/product/mojo-quickstart.rst
  h2o-docs/src/product/performance-and-prediction.rst
  h2o-docs/src/product/pojo-quickstart.rst
Labels: docs

#3280 Commit generated doc files.
  h2o-py/h2o/estimators/deeplearning.py
  h2o-py/h2o/estimators/deepwater.py
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/xgboost.py
  h2o-r/h2o-package/R/deeplearning.R
  h2o-r/h2o-package/R/deepwater.R
  h2o-r/h2o-package/R/gbm.R
  h2o-r/h2o-package/R/randomforest.R
  h2o-r/h2o-package/R/xgboost.R
Labels: docs

#3279 [BUILD] Fix git diff check.
  h2o-py/h2o/estimators/deeplearning.py
  h2o-py/h2o/estimators/deepwater.py
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/xgboost.py
  h2o-r/h2o-package/R/deeplearning.R
  h2o-r/h2o-package/R/deepwater.R
  h2o-r/h2o-package/R/gbm.R
  h2o-r/h2o-package/R/randomforest.R
  h2o-r/h2o-package/R/xgboost.R
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/benchmarkStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/initPipelineContext.groovy
  scripts/jenkins/groovy/insideDocker.groovy
Labels: ITA

#3286 [FLOW-PUBDEV-6180] fixed rendering of SE base models ids.
  h2o-web/bower.json
Labels: Flow

#3288 [BUILD] Add chromium browser to python images
  docker/Jenkinsfile-build-docker
  docker/jenkins-images/Dockerfile-python-base
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#3272 PUBDEV-6183: Doc fix for Tweedie deviance equation
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#3269 PUBDEV-6199: Add data munging topic for Tokenize
  h2o-docs/src/product/data-munging.rst
  h2o-docs/src/product/data-munging/tokenize.rst
  h2o-docs/src/product/data-science/word2vec.rst
Labels: docs

#3266 PUBDEV-6245: Add predict_leaf_node_assignment to User Guide
  h2o-docs/src/product/data-science/if.rst
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3299 [ITA-372] Check for leaked passwords and usernames in logs.
  .gitignore
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/hadoopStage.groovy
  scripts/jenkins/groovy/makeTarget.groovy
  tests/leakCheckKeywords
Labels: ITA, WIP

#3306 [ITA-372] Remove find, use recursive grep.
  scripts/jenkins/Makefile.jenkins
Labels: ITA

#3273 PUBDEV-6254: AutoML basic support for blending
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
  h2o-automl/src/main/java/ai/h2o/automl/UserFeedbackEvent.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-core/src/main/java/hex/ModelMetrics.java
  h2o-core/src/test/java/water/TestUtil.java
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/runitUtils/utilsR.R
  h2o-r/tests/testdir_algos/automl/runit_automl_args.R
Labels: please review

#3317 PUBDEV-6287: Add documentation for check_constant_response in GBM and DRF
  h2o-docs/src/product/data-science/algo-params/check_constant_response.rst
  h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/data-science/stacked-ensembles.rst
  h2o-docs/src/product/flow.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#3321 PUBDEV-6301: Add description of AUCPR to the User Guide
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3327 PUBDEV-6314: Fixed max_depth setting in Python Random Grid Search example
  h2o-docs/src/product/grid-search.rst
Labels: docs

#3320 PUBDEV-6313: AutoML: missing validation frame if not provided by user when cross-validation is disabled
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
Labels: please review
