Repository h2oai/h2o-3, pull requests merged in 2019-04, with the labels that each got.

#3420 PUBDEV-6401: Fix links to Sparkling Water topics in FAQ
  h2o-docs/src/product/faq/sparkling-water.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#3424 [BUILD] Add local nexus as host in docker.
  scripts/jenkins/groovy/insideDocker.groovy
Labels: ITA

#3426 [BUILD] Pull from test.0xdata.com in case of xgb snapshot builds.
  scripts/jenkins/groovy/buildH2O3.groovy
  scripts/jenkins/groovy/defaultStage.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
Labels: ITA

#3429 PUBDEV-6377 - Filling of sparse DMatrix data
  h2o-core/src/test/java/water/TestUtil.java
  h2o-core/src/test/java/water/fvec/TestFrameBuilder.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostUtilsTest.java
Labels: please review

#3437 PUBDEV-6245: Fix link to demo in CoxPH chapter of docs
  h2o-docs/src/product/data-science/coxph.rst
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3409 PUBDEV-6040: Updates to Target Encoding Topic
  h2o-docs/src/product/data-munging/target-encoding.rst
  h2o-docs/src/product/images/gbm_variable_importance1.png
  h2o-docs/src/product/images/gbm_variable_importance2.png
  h2o-py/tests/testdir_algos/automl/target_encoding/PUBDEV-6040: pyunit_automl_gbm_target_encoding.py
Labels: docs

#3444 PUBDEV-6394 - Rapids replace operations on categoricals do not respect reduced categorical domains
  h2o-core/src/main/java/water/rapids/ast/prims/string/AstReplaceAll.java
  h2o-core/src/main/java/water/rapids/ast/prims/string/AstReplaceFirst.java
  h2o-core/src/main/java/water/util/VecUtils.java
  h2o-core/src/test/java/water/rapids/RapidsTest.java
  h2o-py/tests/testdir_jira/pyunit_pubdev_6394.py
Labels: please review

#3459 [ITA-374] Add Java 12 Docker images.
  docker/Jenkinsfile-build-docker
  docker/jenkins-images/Dockerfile-jdk-8-base
  docker/jenkins-images/Dockerfile-jdk-others
  docker/scripts/install_java_version_local
  docker/scripts/java-12-vars.sh
  docker/scripts/java-8-vars.sh
  h2o-core/src/main/java/water/H2O.java
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#3393 PUBDEV-6382: Extend Py API for TargetEncoder with convenient method for getting encoding maps
  h2o-py/h2o/targetencoder.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_gbm_target_encoding.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py
Labels: please review

#3461 PUBDEV-6435 - MOJO import convenience methods
  h2o-py/h2o/__init__.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_generic_model/pyunit_mojo_import.py
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_algos/generic/runit_generic_mojo_convenience.R
Labels: please review

#3466 PUBDEV-6419: Flatten out h2o-3 logs directory structure
  h2o-core/src/main/java/water/util/GetLogsFromNode.java
Labels: please review

#3467 PUBDEV-6419: [rel-yates] Flatten out h2o-3 logs directory structure
  h2o-core/src/main/java/water/util/GetLogsFromNode.java
Labels: please review
