Repository h2oai/h2o-3, pull requests merged in 2019-07, with the labels that each got.

#3636 [FLOW] Update to 0.10.2
  h2o-web/bower.json
Labels: Flow

#3637 [FLOW] Update to 0.9.14
  h2o-web/bower.json
Labels: Flow

#3622 PUBDEV-6613: Add stopping parameters to Isolation Forest
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
  h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
  h2o-docs/src/product/data-science/algo-params/stopping_tolerance.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/if.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#3643 PUBDEV-6598: Update documentation for partial plots for 2D
  h2o-docs/src/product/performance-and-prediction.rst
  h2o-py/h2o/model/model_base.py
Labels: docs

#3648 PUBDEV-6642: updates to python documentation
  h2o-py/h2o/model/model_base.py
Labels: docs

#3645 PUBDEV-6637: Refactored out RowToRawDataConverter
  h2o-genmodel/src/main/java/hex/genmodel/easy/DomainMapConstructor.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/RowToRawDataConverter.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/DomainMapConstructorTest.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/RowToRawDataConverterTest.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/stub/TestMojoModel.java
Labels: please review

#3656 Add DRF to list of supported algorithms for predict_contributions
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3658 PUBDEV-6648: Add more examples to Predict topic
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3660 PUBDEV-6649: fixes for frame.py
  h2o-py/h2o/frame.py
Labels: docs

#3661 PUBDEV-6651: Syntax fix for modeling functions
  h2o-py/h2o/model/dim_reduction.py
  h2o-py/h2o/model/model_base.py
Labels: docs

#3662 PUBDEV-6652: syntax errors in backend server
  h2o-py/h2o/backend/server.py
  h2o-py/h2o/tree/tree.py
Labels: docs

#3663 PUBDEV-6654: fix spelling/add description
  h2o-py/h2o/model/metrics_base.py
Labels: docs

#3665 PUBDEV-6656: Users can only specify a list in the GLM "interactions" parameter
  h2o-docs/src/product/data-science/algo-params/interactions.rst
Labels: docs

#3664 PUBDEV-6650: syntax errors in frame.py
  h2o-py/h2o/frame.py
Labels: docs

#3607 PUBDEV-6500: Creating documentation for SVM
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/svm.rst
  h2o-docs/src/product/grid-search.rst
Labels: WIP, docs

#3638 PUBDEV-6590: support for AutoML deletion (including models and other dependencies)
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/EventLog.java
  h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-automl/src/test/java/ai/h2o/automl/EventLogTest.java
  h2o-automl/src/test/java/ai/h2o/automl/LeaderboardTest.java
  h2o-core/src/main/java/hex/Model.java
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/base.py
  h2o-py/h2o/frame.py
  h2o-py/h2o/h2o.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_memory_cleanup.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/tests/testdir_algos/automl/runit_automl_memory_cleanup.R
Labels: 4RELEASE, please review

#3676 PUBDEV-6663: fix for h2o.frame parameters in the python documentation
  h2o-py/h2o/frame.py
Labels: docs

#3677 PUBDEV-6664: add examples to TargetEncoding Python documentation
  h2o-py/h2o/targetencoder.py
Labels: docs

#3678 PUBDEV-6500: Added alpha note to top of svm.rst
  h2o-docs/src/product/data-science/svm.rst
Labels: docs

#3679 PUBDEV-6660: Update Flow documentation to include Isolation Forest
  h2o-docs/src/product/flow.rst
  h2o-docs/src/product/images/Flow_model_dropdown.png
Labels: docs

#3675 PUBDEV-6452: Update GLM booklet to include information about minimizing negative log likelihood
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#3684 Fix test of h2o.init in R on Java 7
  h2o-r/h2o-package/R/connection.R
  h2o-r/tests/testdir_jira/h2o.init_test_HOQE-16.R
  scripts/jenkins/Makefile.jenkins
Labels: 4RELEASE

#3683 PUBDEV-6672: fixed bug in python client code when no figure is plotted.
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_misc/pyunit_pubdev_6672_2D_pdp_fix.py
Labels: 4RELEASE

#3687 PUBDEV-6673: Bring back old method Frame.toCSV
  h2o-core/src/main/java/water/fvec/Frame.java
  h2o-core/src/test/java/water/fvec/FrameTest.java
Labels: 4RELEASE

#3690 parameters71219: Minor changes to parameters in the parameters appendix
  h2o-docs/src/product/data-science/algo-params/base_models.rst
  h2o-docs/src/product/data-science/algo-params/beta_constraints.rst
  h2o-docs/src/product/data-science/algo-params/blending_frame.rst
  h2o-docs/src/product/data-science/algo-params/build_tree_one_node.rst
  h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
  h2o-docs/src/product/data-science/algo-params/max_runtime_secs.rst
  h2o-docs/src/product/data-science/algo-params/pred_noise_bandwidth.rst
  h2o-docs/src/product/data-science/algo-params/prior.rst
  h2o-docs/src/product/data-science/algo-params/sample_size.rst
  h2o-docs/src/product/data-science/algo-params/seed.rst
  h2o-docs/src/product/data-science/algo-params/ties.rst
Labels: docs

#3680 PUBDEV-6518: Expose an option to collect logs in plain-text, not as a ZIP
  h2o-core/src/main/java/water/api/RequestServer.java
  h2o-core/src/main/java/water/util/GetLogsFromNode.java
  h2o-core/src/main/java/water/util/LogArchiveContainer.java
  h2o-core/src/main/java/water/util/LogArchiveWriter.java
  h2o-core/src/test/java/water/util/LogArchiveWriterTest.java
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_misc/pyunit_txt_logs.py
Labels: 4RELEASE

#3647 PUBDEV-6639: adding cascade param to remove API
  h2o-algos/src/main/java/hex/aggregator/AggregatorModel.java
  h2o-algos/src/main/java/hex/coxph/CoxPHModel.java
  h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
  h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-algos/src/main/java/hex/glrm/GLRMModel.java
  h2o-algos/src/main/java/hex/psvm/PSVMModel.java
  h2o-algos/src/main/java/hex/svd/SVDModel.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/test/java/hex/XValPredictionsCheck.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/EventLog.java
  h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
  h2o-core/src/main/java/hex/FrameSplitter.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/hex/grid/Grid.java
  h2o-core/src/main/java/water/Key.java
  h2o-core/src/main/java/water/Keyed.java
  h2o-core/src/main/java/water/Lockable.java
  h2o-core/src/main/java/water/Scope.java
  h2o-core/src/main/java/water/api/FramesHandler.java
  h2o-core/src/main/java/water/api/ModelsHandler.java
  h2o-core/src/main/java/water/api/RemoveHandler.java
  h2o-core/src/main/java/water/api/schemas3/RemoveV3.java
  h2o-core/src/main/java/water/fvec/FileVec.java
  h2o-core/src/main/java/water/fvec/Frame.java
  h2o-core/src/main/java/water/fvec/RebalanceDataSet.java
  h2o-core/src/main/java/water/fvec/SubsetVec.java
  h2o-core/src/main/java/water/fvec/Vec.java
  h2o-core/src/main/java/water/parser/ParseDataset.java
  h2o-core/src/main/java/water/rapids/Session.java
  h2o-core/src/main/java/water/util/FrameUtils.java
  h2o-core/src/test/java/hex/ModelBuilderTest.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-py/h2o/h2o.py
  h2o-r/h2o-package/R/kvstore.R
Labels: 4RELEASE

#3642 PUBDEV-6482 MOJO model metrics available in H2O
  h2o-algos/src/main/java/hex/generic/Generic.java
  h2o-algos/src/main/java/hex/generic/GenericModel.java
  h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
  h2o-algos/src/main/java/hex/schemas/GenericModelV3.java
  h2o-algos/src/main/java/water/api/ModelMetricsAnomalyV3.java
  h2o-algos/src/test/java/hex/generic/GenericModelTest.java
  h2o-core/src/main/java/hex/AUC2.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelMetrics.java
  h2o-core/src/main/java/hex/ModelMetricsBinomial.java
  h2o-core/src/main/java/hex/ModelMetricsBinomialGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsMultinomial.java
  h2o-core/src/main/java/hex/ModelMetricsMultinomialGeneric.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialGenericV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsMultinomialGenericV3.java
  h2o-core/src/main/resources/META-INF/services/water.api.Schema
  h2o-genmodel/src/main/java/hex/genmodel/AbstractMojoWriter.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelDescriptor.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoPipelineWriter.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelAttributes.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelJsonReader.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/SharedTreeModelAttributes.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/Table.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/VariableImportances.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/metrics/MojoModelMetrics.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/metrics/MojoModelMetricsBinomial.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/metrics/MojoModelMetricsMultinomial.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/metrics/MojoModelMetricsRegression.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/metrics/SerializedName.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/JsonModelDescriptorReader.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptor.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/glm/GlmMultinomialMojoModelTest.java
  h2o-py/h2o/model/metrics_base.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_drf.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_gbm.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_glm.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_irf.py
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_drf.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_gbm.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_glm.R
Labels: 4RELEASE, please review

#3627 PUBDEV-5858: allow user to choose number of iteration for GLRM mojo scoring.
  h2o-algos/src/main/java/hex/glrm/GLRM.java
  h2o-core/src/main/java/water/util/RandomUtils.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_javapredict/pyunit_pubdev_5858_GLRMIterNumber.py
  h2o-py/tests/testdir_javapredict/pyunit_pubdev_5858_mojo_predict.py
  h2o-r/tests/runitUtils/utilsR.R
  h2o-r/tests/testdir_javapredict/runit_PUBDEV_5858_glrmIterNumber.R
Labels: 4RELEASE

#3688 [WIP] PUBDEV-6554: Add "upload_custom_distribution" to Parameters Appendix
  h2o-docs/src/product/data-science/algo-params/base_models.rst
  h2o-docs/src/product/data-science/algo-params/custom_distribution_func.rst
  h2o-docs/src/product/data-science/algo-params/upload_custom_distribution.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#3646 PUBDEV-6640 Introduced TargetEncoderBuilder and TargetEncoderModel
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/FrameToTETableTask.java
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TEComponents.java
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoder.java
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoderBuilder.java
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoderFrameHelper.java
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoderModel.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncoderBuilderTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingKFoldStrategyTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingLeaveOneOutStrategyTest.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingNoneStrategyTest.java
  h2o-automl/src/test/java/water/H2OTestNodeStarter.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/test/java/water/TestUtil.java
  h2o-genmodel/src/main/java/hex/ModelCategory.java
Labels: please review

#3692 [PUBDEV-6436] User friendly way to import MOJO models via Flow
  h2o-algos/src/main/java/hex/generic/Generic.java
  h2o-algos/src/main/java/hex/generic/GenericModelParameters.java
  h2o-algos/src/main/java/hex/schemas/GenericV3.java
  h2o-bindings/bin/gen_python.py
  h2o-py/h2o/estimators/generic.py
  h2o-r/h2o-package/R/generic.R
  h2o-r/h2o-package/R/models.R
Labels: please review

#3716 PUBDEV-6682 - DRF MOJO output checking
  h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelJsonReader.java
  h2o-py/tests/testdir_generic_model/__init__.py
  h2o-py/tests/testdir_generic_model/common.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_drf.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_gbm.py
  h2o-r/tests/testdir_algos/generic/generic_model_test_common.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_drf.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_gbm.R
Labels: please review

#3734 PUBDEV-6698: Add "aucpr" to list of stopping_metric options
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/if.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#3733 PUBDEV-6687: Update docs for MOJO import
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/mojo_import.rst
  h2o-docs/src/product/flow.rst
  h2o-docs/src/product/images/Flow_model_dropdown.png
Labels: docs

#3714 [WIP] PUBDEV-6671: Add `feature_frequencies` to Performance and Prediction section
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3739 PUBDEV-6678: Add a "Defining a MOJO import" section to the MOJO import chapter
  h2o-docs/src/product/data-science/mojo_import.rst
Labels: docs

#3691 PUBDEV-6666: Add examples to GBM chapter
  h2o-py/h2o/estimators/gbm.py
Labels: docs

#3741 PUBDEV-6706: Create Parameters Appendix entry for export_checkpoints_dir
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/aggregator.rst
  h2o-docs/src/product/data-science/algo-params/export_checkpoints_dir.rst
  h2o-docs/src/product/data-science/coxph.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/data-science/glrm.rst
  h2o-docs/src/product/data-science/if.rst
  h2o-docs/src/product/data-science/k-means.rst
  h2o-docs/src/product/data-science/naive-bayes.rst
  h2o-docs/src/product/data-science/pca.rst
  h2o-docs/src/product/data-science/stacked-ensembles.rst
  h2o-docs/src/product/data-science/word2vec.rst
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#3743 PUBDEV-6112
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
  h2o-bindings/bin/gen_python.py
  h2o-py/h2o/estimators/stackedensemble.py
Labels: please review

#3748 PUBDEV-6716: Make sure TargetEncoderMojoModel and TargetEncoderModel return same values for unseen categorical levels
  h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoder.java
  h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TEMojoIntegrationTest.java
Labels: please review

#3763 PUBDEV-6707 Create Parameters Appendix entry for monotone_constraints
  h2o-docs/src/product/data-science/algo-params/monotone_constraints.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#3762 Pubdev 6728: Create examples for the Multinomial Models section in the Python documentation
  h2o-py/h2o/model/multinomial.py
Labels: docs
