Repository h2oai/h2o-3, pull requests merged in 2019-10, with the labels that each got.

#3938 PUBDEV-6925: Add CDH 6.3 to list of supported Hadoop platforms
  h2o-docs/src/product/welcome.rst
Labels: 4RELEASE, docs

#3936 PUBDEV-6897: Add GBM POJO support for OneHotExplicit encoding
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
  h2o-core/src/main/java/hex/Model.java
  h2o-genmodel/src/main/java/hex/genmodel/CategoricalEncoding.java
  h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/water/genmodel/IGeneratedModel.java
Labels: 4RELEASE

#3911 PUBDEV-6825: Added ability to make copy of the ModelBuilder
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/test/java/hex/ModelBuilderTest.java
Labels: please review

#3764 PUBDEV-6263 - Bypass proxy in Python when H2O is started on localhost
  h2o-py/h2o/backend/connection.py
  h2o-py/tests/testdir_misc/pyunit_init_proxy.py
Labels: please review

#3919 PUBDEV-6749 - Allow Grid Search to Continue After Cluster Restart
  h2o-algos/src/test/java/hex/ModelParametersChecksumTest.java
  h2o-algos/src/test/java/hex/grid/GridTest.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/grid/Grid.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/hex/schemas/GridSchemaV99.java
  h2o-core/src/main/java/water/api/GridImportExportHandler.java
  h2o-core/src/main/java/water/api/RegisterV3Api.java
  h2o-core/src/main/java/water/api/schemas3/GridExportV3.java
  h2o-core/src/main/java/water/api/schemas3/GridImportV3.java
  h2o-core/src/main/resources/META-INF/services/water.api.Schema
  h2o-py/h2o/__init__.py
  h2o-py/h2o/grid/grid_search.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_algos/grid/pyunit_grid_manual_export_resume.py
  h2o-py/tests/testdir_algos/grid/pyunit_grid_manual_export_resume_new_hyperspace.py
  h2o-py/tests/testdir_algos/grid/pyunit_grid_resume.py
  h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2ogrid_checkpoints.py
  h2o-r/h2o-package/R/export.R
  h2o-r/h2o-package/R/grid.R
  h2o-r/h2o-package/R/import.R
  h2o-r/tests/testdir_algos/glm/runit_GLM_grid_checkpoints.R
  h2o-r/tests/testdir_algos/grid/runit_grid_manual_export_resume.R
  h2o-r/tests/testdir_algos/grid/runit_grid_resume.R
Labels: please review

#3946 PUBDEV-6893 - Saving files in Python not properly creating directories
  h2o-py/h2o/backend/connection.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_pojo.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_6893_download_pojo_creatable_location.py
Labels: please review

#3950 PUBDEV-6952 Checking whether testMultiNode task is being run for TE ext module
  h2o-extensions/target-encoder/testMultiNode.sh
Labels: please review

#3930 PUBDEV-6918: Python Docs: Update GLM Examples
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-bindings/bin/custom/python/gen_xgboost.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/xgboost.py
Labels: docs

#3962 PUBDEV-6749 - Fix grid search parameter checksum comparison
  h2o-core/src/main/java/hex/grid/GridSearch.java
Labels: please review

#3944 PUBDEV-6941: Added blending of posterior and prior during imputation of unseen values
  h2o-extensions/target-encoder/build.gradle
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TEMojoIntegrationTest.java
Labels: please review

#3957 PUBDEV-6953: Fix broken link in XGBoost documentation
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-py/docs/conf.py
Labels: docs

#3955 PUBDEV-6851: Docs - Add Parameter Appendix entries for CoxPH parameters
  h2o-docs/src/product/data-science/algo-params/init1.rst
  h2o-docs/src/product/data-science/algo-params/init2.rst
  h2o-docs/src/product/data-science/algo-params/lre_min.rst
  h2o-docs/src/product/data-science/algo-params/stratify_by.rst
  h2o-docs/src/product/data-science/coxph.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#3971 PUBDEV-6967 - TE broken in flow - response_column parameter not exposed.
  h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderV3.java
  h2o-py/h2o/estimators/targetencoder.py
  h2o-r/h2o-package/R/targetencoder.R
  h2o-web/bower.json
Labels: please review

#3968 PUBDEV-6958: Python Docs: Add examples to NaiveBayes
  h2o-bindings/bin/custom/python/gen_naivebayes.py
  h2o-py/h2o/estimators/naive_bayes.py
Labels: docs

#3910 PUBDEV-6494: training_frame requirements for StackedEnsemble in blending mode
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-bindings/bin/custom/R/gen_stackedensemble.py
  h2o-bindings/bin/custom/python/gen_stackedensemble.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_base_model_training_frame.py
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_blending_frame.py
  h2o-r/h2o-package/R/stackedensemble.R
  h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_blending_frame.R
Labels: please review

#3931 [PUBDEV-6922] Send data to and from external backend not by each item, but after specified block size
  h2o-core/src/main/java/water/ExternalFrameReaderBackend.java
  h2o-core/src/main/java/water/ExternalFrameUtils.java
  h2o-core/src/main/java/water/ExternalFrameWriterClient.java
  h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java
Labels: please review

#3978 PUBDEV-6951: AutoML in User Guide: remove experimental note
  h2o-docs/src/product/automl.rst
Labels: docs

#3987 Fix a test class to be compatible with Python 2.7 syntax
  h2o-py/tests/testdir_generic_model/common.py
Labels: 4RELEASE

#3985 PUBDEV-6979: `use_spnego` option added to the Starting H2O in R topic
  h2o-docs/src/product/starting-h2o.rst
Labels: 4RELEASE, docs

#3934 PUBDEV-6912: Python Docs: Add examples to KMeans
  h2o-bindings/bin/custom/python/gen_kmeans.py
  h2o-py/h2o/estimators/kmeans.py
Labels: docs

#3996 PUBDEV-6989: Update XGBoost extramempercent FAQ
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#3965 EasyPredictModelWrapper Refactoring: first step towards 1-hot encoding for POJO/MOJO
  h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/CategoricalEncoder.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/DWImageConverter.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/DWTextConverter.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/DomainMapConstructor.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EnumEncoder.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/RowDataConverterFactory.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/RowToRawDataConverter.java
  h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/targetencoder/TargetEncoderMojoModelTest.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/DomainMapConstructorTest.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/EasyPredictModelWrapperTest.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/RowToRawDataConverterTest.java
Labels: WIP

#3844 EMR Terraform: Setup EMR on a private subnet expose Flow using load balancer
  templates/emr/terraform/main.tf
  templates/emr/terraform/modules/emr/main.tf
  templates/emr/terraform/modules/emr/outputs.tf
  templates/emr/terraform/modules/emr/security_groups.tf
  templates/emr/terraform/modules/emr/variables.tf
  templates/emr/terraform/modules/network/main.tf
  templates/emr/terraform/modules/network/outputs.tf
  templates/emr/terraform/modules/network/variables.tf
  templates/emr/terraform/outputs.tf
  templates/emr/terraform/variables.tf
Labels: WIP

#4000 PUBDEV-6996: Python Docs: Remove examples for `ignored_columns` and `response_column`
  h2o-bindings/bin/custom/python/gen_drf.py
  h2o-bindings/bin/custom/python/gen_gbm.py
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-bindings/bin/custom/python/gen_isolationforest.py
  h2o-bindings/bin/custom/python/gen_kmeans.py
  h2o-bindings/bin/custom/python/gen_naivebayes.py
  h2o-bindings/bin/custom/python/gen_xgboost.py
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/isolation_forest.py
  h2o-py/h2o/estimators/kmeans.py
  h2o-py/h2o/estimators/naive_bayes.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/xgboost.py
Labels: docs

#3961 PUBDEV-6939: Python Docs: Add examples to DeepLearning
  h2o-bindings/bin/custom/python/gen_deeplearning.py
  h2o-docs/src/product/conf.py
  h2o-py/h2o/estimators/deeplearning.py
Labels: docs

#4015 PUBDEV-7010: Python, H2OFrame.drop should not modify params
  h2o-py/h2o/frame.py
  h2o-py/tests/testdir_misc/pyunit_drop.py
Labels: please review

#4016 PUBDEV-7011: fixed swallowed error on model.actual_params property
  h2o-py/h2o/model/model_base.py
Labels: please review

#4014 PUBDEV-6195: AutoML, add warning message on empty leaderboard
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/h2o-package/R/communication.R
  h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
Labels: please review

#4012 PUBDEV-6998: ensure project_name is validated before AutoML is being trained
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/utils/shared_utils.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_args.R
Labels: please review

#4022 PUBDEV-7016 - .h2o.__waitOnJob R function tries to split lines in a stracktrace a non-existing object
  h2o-r/h2o-package/R/communication.R
Labels: please review

#3857 PUBDEV-6847 - Show MOJO Import possibility when importing model from a different version
  h2o-core/src/main/java/water/AutoBuffer.java
Labels: please review

#4005 Add ability to specify algo parameters (e.g. monotonicity constraints) in H2O AutoML
  h2o-automl/build.gradle
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/GBMStepsProvider.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-automl/src/main/resources/META-INF/services/water.api.Schema
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLBuildSpecTest.java
  h2o-core/src/main/java/water/api/SchemaMetadata.java
  h2o-core/src/main/java/water/util/JSONUtils.java
  h2o-core/src/main/java/water/util/JSONValue.java
  h2o-core/src/main/java/water/util/PojoUtils.java
  h2o-core/src/test/java/water/util/JSONValueTest.java
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_model_selection.R
Labels: please review

#4013 PUBDEV-7004: Python Docs: Add Examples to PCA
  h2o-bindings/bin/custom/python/gen_pca.py
  h2o-py/h2o/estimators/pca.py
Labels: docs

#3993 PUBDEV-6988: Python Docs: Add examples to Aggregator
  h2o-bindings/bin/custom/python/gen_aggregator.py
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-py/h2o/estimators/aggregator.py
  h2o-py/h2o/estimators/glm.py
Labels: docs

#4031 PUBDEV-6831 - Generated R & Py docs
  h2o-py/h2o/estimators/random_forest.py
  h2o-r/h2o-package/R/randomforest.R
Labels: please review

#4029 PUBDEV-7009: Python Docs: Add examples to Word2vec
  h2o-bindings/bin/custom/python/gen_word2vec.py
  h2o-py/docs/model_categories.rst
  h2o-py/h2o/estimators/word2vec.py
  h2o-py/h2o/frame.py
  h2o-py/h2o/model/word_embedding.py
Labels: docs
