Repository h2oai/h2o-3, pull requests merged in 2019-11, with the labels that each got.

#4026 PUBDEV-7019: New section for Installing and Starting H2O in the Python Client documentation
  h2o-bindings/bin/custom/python/gen_targetencoder.py
  h2o-py/docs/intro.rst
  h2o-py/h2o/estimators/targetencoder.py
Labels: docs

#4033 PUBDEV-7022: Python Docs: Add Examples to Generic
  h2o-bindings/bin/custom/python/gen_generic.py
  h2o-py/h2o/estimators/generic.py
Labels: docs

#4041 PUBDEV-7038: Docs - Logloss Range Fix
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#4045 Disable parsing MOJO Model metadata by default - not needed for scoring
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
  h2o-genmodel/src/test/java/hex/genmodel/MockMojoReader.java
  h2o-genmodel/src/test/java/hex/genmodel/ModelMojoReaderTest.java
  h2o-genmodel/src/test/resources/META-INF/services/hex.genmodel.ModelMojoReader
Labels: please review

#3990 PUBDEV-6774 - Parallelize Grid Search
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/test/java/hex/grid/GridTest.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/hex/ModelBuilderListener.java
  h2o-core/src/main/java/hex/ParallelModelBuilder.java
  h2o-core/src/main/java/hex/grid/Grid.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
  h2o-core/src/main/java/hex/schemas/GridSearchSchema.java
  h2o-core/src/main/java/water/api/GridSearchHandler.java
  h2o-py/h2o/grid/grid_search.py
  h2o-py/tests/testdir_algos/grid/pyunit_grid_parallel.py
  h2o-r/h2o-package/R/grid.R
  h2o-r/tests/testdir_algos/grid/runit_grid_parallel.R
Labels: please review

#4047 PUBDEV-7034: Python Docs: Fix documentation spacing for in-function parameters
  h2o-bindings/bin/custom/python/gen_deeplearning.py
  h2o-bindings/bin/custom/python/gen_drf.py
  h2o-bindings/bin/custom/python/gen_gbm.py
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-bindings/bin/custom/python/gen_isolationforest.py
  h2o-bindings/bin/custom/python/gen_kmeans.py
  h2o-bindings/bin/custom/python/gen_naivebayes.py
  h2o-bindings/bin/custom/python/gen_xgboost.py
  h2o-py/h2o/estimators/deeplearning.py
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/isolation_forest.py
  h2o-py/h2o/estimators/kmeans.py
  h2o-py/h2o/estimators/naive_bayes.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/xgboost.py
Labels: docs

#4061 PUBDEV-6926: Python docs: Add example for `melt` data manipulation function
  h2o-py/h2o/frame.py
Labels: docs

#3983 PUBDEV-6972: Python Docs: Add examples to StackedEnsemble
  h2o-bindings/bin/custom/python/gen_stackedensemble.py
  h2o-py/h2o/estimators/stackedensemble.py
Labels: docs

#3975 PUBDEV-6970: introduced AllCategorical and Threshold TE application strategies
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/strategy/AllCategoricalTEApplicationStrategy.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/strategy/TEApplicationStrategy.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/strategy/ThresholdTEApplicationStrategy.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/strategy/AllCategoricalTEApplicationStrategyTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/strategy/ThresholdTEApplicationStrategyTest.java
Labels: please review

#4020 PUBDEV-6737: expose monotone_constraints as a top level parameter in AutoML
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_model_selection.R
Labels: please review

#4059 PUBDEV-7055: Change examples to insecure=False on Security Page
  h2o-docs/src/product/security.rst
Labels: docs

#4077 PUBDEV-6911 - Allow H2OGenericEstimator to be instantiated with no params.
  h2o-bindings/bin/custom/python/gen_generic.py
  h2o-py/h2o/estimators/generic.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model.py
Labels: please review

#4084 [BUILD] Suppress healthchecks for benchmark stages.
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: Build

#4079 PUBDEV-6940: fix list of metrics exposed in Flow
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-core/src/main/java/hex/ModelMetricsBinomial.java
  h2o-core/src/main/java/hex/ScoreKeeper.java
  h2o-core/src/main/java/hex/ScoringInfo.java
  h2o-core/src/main/java/hex/schemas/HyperSpaceSearchCriteriaV99.java
  h2o-core/src/main/java/water/api/EnumValuesProvider.java
  h2o-core/src/main/java/water/api/SchemaMetadata.java
  h2o-core/src/main/java/water/api/schemas3/ModelParameterSchemaV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelParamsValuesProviders.java
  h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
Labels: please review

#4035 PUBDEV-7025: Python Docs: Add examples to SVD
  h2o-bindings/bin/custom/python/gen_svd.py
  h2o-py/h2o/estimators/svd.py
  h2o-py/h2o/model/binomial.py
Labels: docs

#4071 PUBDEV-7059: Use AutoML annotations for UI in Flow
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/water/automl/api/AutoMLBuilderHandler.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/EventLogEntryV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/LeaderboardV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-docs/src/product/flow/packs/examples/PCA_before_AutoML_Example.flow
  h2o-docs/src/product/flow/packs/test-small/automl_prostate.flow
  h2o-docs/src/product/flow/packs/test-small/automl_prostate_prefill.flow
  h2o-web/bower.json
Labels: please review

#4008 PUBDEV-6975: Attempt to reuse existing tools for grid search over TE hyper parameters
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderModel.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderMojoWriter.java
  h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderV3.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TEMojoIntegrationTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderModelTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/strategy/TargetEncoderRGSTest.java
Labels: please review

#4066 PUBDEV-6890: add platt scaling for XGBoost
  h2o-algos/src/main/java/hex/tree/PlattScalingHelper.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostV3.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostMojoWriter.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostOutput.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/PlattScalingMojoHelper.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-py/h2o/estimators/xgboost.py
  h2o-r/h2o-package/R/xgboost.R
  h2o-r/tests/testdir_algos/xgboost/runit_XGBoost_calibration_binomial.R
Labels: please review

#4088 PUBDEV-4986: ensure case-insensitivity of stopping+sort metrics
  h2o-core/src/main/java/water/util/EnumUtils.java
  h2o-core/src/main/java/water/util/PojoUtils.java
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_algos/automl/runit_automl_args.R
  h2o-r/tests/testdir_algos/randomforest/runit_RF_early_stopping.R
Labels: please review
