Repository h2oai/h2o-3, pull requests merged in 2019-03, with the labels that each got.

#3333 PUBDEV-5554: Recommend setting extramempercent to 120 for xgboost
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#3331 PUBDEV-6283 - Stratified split fails when ran on the same column twice
  h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstStratifiedSplit.java
  h2o-core/src/test/java/water/util/VecUtilsTest.java
  h2o-py/tests/testdir_jira/pyunit_pubdev_6283.py
Labels: please review

#3328 PUBDEV-6292: remove NA row from GLM varimp
  h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_algos/glm/pyunit_pubdev_6292_varimp_check.py
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_algos/glm/runit_pubdev_6292_varimp_check.R
Labels: 4RELEASE, please review

#3337 [BUILD] Do not run benchmarks for every commit.
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
Labels: ITA

#3341 PUBDEV-6337: Add note to docs re monotone_constraints in GBM
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/flow.rst
Labels: docs

#3342 PUBDEV-6347 - Update S3 documentation for 3.22.x
  h2o-docs/src/product/aws.rst
  h2o-docs/src/product/cloud-integration/ec2-and-s3.rst
  h2o-docs/src/product/howto/H2O-DevS3Creds.md
Labels: docs

#3346 Reorder cleanWs in hadoop docker build
  docker/Jenkinsfile-build-hadoop-docker
Labels: ITA

#3318 PUBDEV-6196: expose include_algos parameter to AutoML Py+R clients
  h2o-automl/src/main/java/ai/h2o/automl/Algo.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-docs/src/product/automl.rst
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_args.R
Labels: please review

#3353 [BUILD] Do not update latest_stable_(Py|R) by default.
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: ITA

#3218 PUBDEV-5809: H2O-core changes to ensure per-model runtime limit
  h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
  h2o-algos/src/main/java/hex/deepwater/DeepWater.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/tree/gbm/GBM.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
  h2o-core/src/main/java/hex/schemas/HyperSpaceSearchCriteriaV99.java
  h2o-core/src/main/java/water/api/EnumValuesProvider.java
  h2o-core/src/main/java/water/api/Handler.java
  h2o-core/src/main/java/water/api/Schema.java
  h2o-core/src/main/java/water/api/ValuesProvider.java
  h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelParamsValuesProviders.java
  h2o-core/src/main/java/water/util/Countdown.java
  h2o-core/src/main/java/water/util/PojoUtils.java
  h2o-core/src/test/java/water/util/CountdownTest.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
Labels: please review

#3350 PUBDEV-6208: SE Model deletion can lead to removal of shared vecs
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
Labels: please review

#3371 PUBDEV-6362: Replaced "h2o cloud" with "h2o cluster" in end-user docs
  h2o-docs/devel/h2o_clouding.rst
  h2o-docs/src/booklets/v2_2015/source/RBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/sw/sections/backends.tex
  h2o-docs/src/booklets/v2_2015/source/sw/sections/deployment.tex
  h2o-docs/src/booklets/v2_2015/source/sw/sections/pysparkling.tex
  h2o-docs/src/booklets/v2_2015/source/sw/sections/usecase.tex
  h2o-docs/src/product/architecture.rst
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-munging/combining-columns.rst
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/faq/java.rst
  h2o-docs/src/product/hadoop.rst
  h2o-docs/src/product/starting-h2o.rst
  h2o-docs/src/product/welcome.rst
  h2o-py/docs/intro.rst
  h2o-py/h2o/backend/connection.py
  h2o-py/h2o/backend/server.py
  h2o-py/h2o/h2o.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/connection.R
  h2o-r/h2o-package/R/frame.R
  h2o-r/h2o-package/R/import.R
  h2o-r/h2o-package/R/logging.R
  scripts/run.py
Labels: docs

#3373 PUBDEV-6280: Documentation for negative binomial family in GLM
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/GLM_Vignette_code_examples/glm_negativebinomial_example.R
  h2o-docs/src/booklets/v2_2015/source/GLM_Vignette_code_examples/glm_negativebinomial_example.py
  h2o-docs/src/product/data-science/algo-params/link.rst
  h2o-docs/src/product/data-science/algo-params/theta.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/flow.rst
  h2o-docs/src/product/grid-search.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#3375 PUBDEV-6331: Add parameter appendix entries for new AutoML options
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/exclude_algos.rst
  h2o-docs/src/product/data-science/algo-params/include_algos.rst
  h2o-docs/src/product/data-science/algo-params/max_models.rst
  h2o-docs/src/product/data-science/algo-params/max_runtime_secs_per_model.rst
  h2o-docs/src/product/data-science/algo-params/sort_metric.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#3274 PUBDEV-6136 - Mojo delegating generic model
  h2o-algos/src/main/java/hex/api/RegisterAlgos.java
  h2o-algos/src/main/java/hex/generic/Generic.java
  h2o-algos/src/main/java/hex/generic/GenericModel.java
  h2o-algos/src/main/java/hex/generic/GenericModelMojoWriter.java
  h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
  h2o-algos/src/main/java/hex/generic/GenericModelParameters.java
  h2o-algos/src/main/java/hex/schemas/GenericModelV3.java
  h2o-algos/src/main/java/hex/schemas/GenericV3.java
  h2o-algos/src/main/resources/META-INF/services/water.api.Schema
  h2o-algos/src/test/java/hex/generic/GenericModelTest.java
  h2o-bindings/bin/gen_R.py
  h2o-bindings/bin/gen_python.py
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelMojoWriter.java
  h2o-core/src/main/java/water/util/ArrayUtils.java
  h2o-core/src/main/java/water/util/TwoDimTable.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelDescriptor.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoPipelineWriter.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/JsonModelDescriptorReader.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/Table.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/VariableImportances.java
  h2o-py/docs/modeling.rst
  h2o-py/h2o/estimators/__init__.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/generic.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_drf.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_gbm.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_glm.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_irf.py
  h2o-r/H2O_Load.R
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package/R/generic.R
  h2o-r/h2o-package/R/models.R
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_drf.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_gbm.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_glm.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_irf.R
Labels: please review

#3384 PUBDEV-6378 - Generic model release notes (PUBDEV-6136)
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/generic.rst
Labels: please review

#3366 PUBDEV-6324 - Clear H2O DKV but some predefined frames
  h2o-algos/src/test/java/hex/ClearDKVTaskTest.java
  h2o-algos/src/test/java/hex/naivebayes/NaiveBayesTest.java
  h2o-core/src/main/java/water/DKV.java
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/main/java/water/Value.java
  h2o-core/src/main/java/water/fvec/Frame.java
  h2o-core/src/test/java/water/DKVTest.java
Labels: please review

#3382 PUBDEV-6376: StackedEnsemble prediction fails when applied to a test dataset without response column
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
Labels: please review

#3397 PUBDEV-6381: monotone_constraints available with Bernoulli distribution
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/flow.rst
Labels: 4RELEASE, docs

#3398 PUBDEV-6375: Add section for predict contributions in Predict topic
  h2o-docs/src/product/performance-and-prediction.rst
Labels: 4RELEASE, docs

#3405 PUBDEV-6386: XGBoost MOJO should use Java predictor by default
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostMojoWriter.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/DefaultMojoImplTest.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoReader.java
Labels: 4RELEASE

#3399 PUBDEV-6056: SHAP values support for MOJO
  h2o-algos/src/test/java/hex/tree/gbm/GBMPredictContribsTest.java
  h2o-core/src/test/java/water/TestUtil.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostJavaMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/PredictContributions.java
  h2o-genmodel/src/main/java/hex/genmodel/PredictContributionsFactory.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/gbm/GbmMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/TreeSHAP.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/BinomialModelPrediction.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/RegressionModelPrediction.java
Labels: 4RELEASE

#3367 PUBDEV-6350: fixed rendering of multiple Confusion Matrices when using Py and R clients
  h2o-py/h2o/model/metrics_base.py
  h2o-py/tests/testdir_misc/pyunit_make_metrics.py
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_misc/runit_make_metrics.R
Labels: R, please review, python

#3408 PUBDEV-6254: AutoML adding blending_frame param to doc
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/blending_frame.rst
Labels: 4RELEASE

#3406 PUBDEV-6388: AutoML, reorder algorithms to improve perf on large datasets
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-docs/src/product/automl.rst
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_pojo.py
  h2o-r/tests/testdir_algos/automl/runit_automl_args.R
  h2o-r/tests/testdir_algos/automl/runit_automl_pojo.R
Labels: 4RELEASE

#3380 PUBDEV-6367 - Overridable non-data line markers
  h2o-bindings/src/main/java/water/bindings/examples/Example.java
  h2o-core/src/main/java/water/api/ParseHandler.java
  h2o-core/src/main/java/water/api/schemas3/ParseSetupV3.java
  h2o-core/src/main/java/water/api/schemas3/ParseV3.java
  h2o-core/src/main/java/water/parser/ARFFParser.java
  h2o-core/src/main/java/water/parser/CsvParser.java
  h2o-core/src/main/java/water/parser/DefaultParserProviders.java
  h2o-core/src/main/java/water/parser/ParseSetup.java
  h2o-core/src/main/java/water/parser/ParserProvider.java
  h2o-core/src/test/java/water/parser/ARFFParserTest.java
  h2o-core/src/test/java/water/parser/CsvParserTest.java
  h2o-py/h2o/frame.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_6367.py
  h2o-r/h2o-package/R/import.R
  h2o-r/h2o-package/R/parse.R
  h2o-r/tests/testdir_jira/runit_pubdev_6339.R
  h2o-r/tests/testdir_jira/runit_pubdev_6367.R
Labels: 4RELEASE
