Repository h2oai/h2o-3, pull requests merged in 2019-05, with the labels that each got.

#3462 PUBDEV-6408- CSV - ArrayIndexOutOfBounds when quotes are parsed
  h2o-core/src/main/java/water/parser/CsvParser.java
  h2o-core/src/test/java/water/parser/CsvParserTest.java
  h2o-py/tests/testdir_parser/pyunit_csv_parser.py
Labels: please review

#3196 PUBDEV-6024 enhance gbm reproducibility section
  h2o-docs/src/product/data-science/gbm-faq/reproducibility.rst
Labels: WIP

#3472 PUBDEV-6416 - Grid search appears to use old parameters
  h2o-algos/src/test/java/hex/glrm/GLRMGridTest.java
  h2o-algos/src/test/java/hex/grid/GridTest.java
  h2o-algos/src/test/java/hex/kmeans/KMeansGridTest.java
  h2o-algos/src/test/java/hex/tree/drf/DRFGridTest.java
  h2o-algos/src/test/java/hex/tree/gbm/GBMGridTest.java
  h2o-core/src/main/java/hex/grid/Grid.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/hex/schemas/GridSchemaV99.java
  h2o-py/tests/testdir_jira/pyunit_pubdev_6416.py
Labels: please review

#3481 PUBDEV-6440 - Unable to parse files from s3 [using s3's directory url with s3 protocol]
  h2o-persist-s3/src/main/java/water/persist/PersistS3.java
  h2o-persist-s3/src/test/java/water/persist/PersistS3Test.java
Labels: please review

#3484 PUBDEV-6475 - h2o.getModelTree throws invalid object for slot 'nas'
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_jira/runit_pubdev_6475.R
Labels: please review

#3495 Docs: Remove note in Isolation Forest chapter stating it is a Beta version
  h2o-docs/src/product/data-science/if.rst
Labels: docs

#3496 PUBDEV-6486: Add support for CDH 6.2 to User Guide
  h2o-docs/src/product/faq/hadoop.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#3498 PUBDEV-6162 - Dynamic change of S3A credentials
  h2o-core/src/main/java/water/api/RegisterV3Api.java
  h2o-core/src/main/java/water/persist/IcedS3Credentials.java
  h2o-core/src/main/java/water/persist/PersistS3CredentialsV3.java
  h2o-core/src/main/java/water/persist/PersistS3Handler.java
  h2o-core/src/main/java/water/persist/RegisterRestApi.java
  h2o-core/src/main/resources/META-INF/services/water.api.Schema
  h2o-persist-hdfs/src/main/java/water/persist/H2ODynamicS3ACredentialsProvider.java
  h2o-persist-hdfs/src/main/java/water/persist/PersistHdfs.java
  h2o-persist-hdfs/src/test/java/water/persist/PersistS3HdfsTest.java
  h2o-persist-s3/src/main/resources/META-INF/services/water.api.RestApiExtension
  h2o-persist-s3/src/main/resources/META-INF/services/water.api.Schema
  h2o-persist-s3/testMultiNode.sh
  h2o-py/tests/testdir_persist/pyunit_persistence_s3.py
  h2o-py/tests/testdir_persist/pyunit_persistence_s3a.py
  h2o-r/tests/testdir_persist/runit_set_s3a_credentials.R
  settings.gradle
Labels: please review

#3511 PUBDEV-6488 h2o.getModelTree failing
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_jira/runit_pubdev_6488.R
Labels: please review

#3517 PUBDEV-6511 - add missing functions to _pkgdown.yml file
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
Labels: R, docs

#3529 PUBDEV-6162 - S3A Hadoop multi-bucket configuration docs
  h2o-docs/src/product/welcome.rst
Labels: docs, please review

#3532 PUBDEV-6522 - Rename Generic Models to MOJO import in documentation
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/mojo_import.rst
Labels: docs, please review

#3540 PUBDEV-6532 - XGBoost should not use grouping in parameter localization
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/BoosterParms.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/BoosterParmsTest.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostParamsTest.java
Labels: 4RELEASE

#3541 [PUBDEV-6510] parallelize xgboost matrix population
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/MatrixFactoryUtils.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/SparseMatrix.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/SparseMatrixDimensions.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/SparseMatrixFactory.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostUtilsTest.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/matrix/SparseMatrixFactoryAllocationTest.java
Labels: please review

#3553 PUBDEV-6537: Removed oprobit and ologlog from docs
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/product/data-science/algo-params/link.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/flow.rst
Labels: docs
