Repository h2oai/h2o-3, pull requests merged in 2019-01, with the labels that each got.

#3191 PUBDEV-6164: Updated copyright year in docs
  h2o-docs/src/booklets/v2_2015/source/DeepLearningBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/GBMBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/PythonBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/RBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/SparklingWaterBooklet.tex
  h2o-docs/src/product/conf.py
  h2o-py/docs/conf.py
Labels: docs

#3195 PUBDEV-6167 XGBoost stress test timeout
  h2o-py/tests/testdir_algos/xgboost/stress/pyunit_xgboost_airlines_stress.py
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: please review

#3181 PUBDEV-6146 - HDP 3.0 & HDP 3.1
  docker/hadoop/cdh/Dockerfile
  docker/hadoop/cdh/scripts/sbin/install_hive.sh
  docker/hadoop/common/kerberos/00_kerberos_init
  docker/hadoop/common/startup/50_hive_start
  docker/hadoop/hdp/Dockerfile
  docker/hadoop/hdp/scripts/sbin/add_hdp_repo.sh
  docker/hadoop/hdp/scripts/sbin/generate-mapred-site
  docker/hadoop/hdp/scripts/sbin/generate-yarn-site
  docker/hadoop/hdp/scripts/sbin/install_hive.sh
  docker/hadoop/hdp/scripts/startup/40_yarn_start
  h2o-dist/buildinfo.json
  h2o-hadoop-3/h2o-hdp3.0-assembly/build.gradle
  h2o-hadoop-3/h2o-hdp3.1-assembly/build.gradle
  make-dist.sh
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/hadoopStage.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
  settings.gradle
Labels: WIP

#3200 PUBDEV-6165 Docs: Add support for HDP 3.0 and 3.1
  h2o-docs/src/product/downloading.rst
  h2o-docs/src/product/starting-h2o.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#3202 [FLOW-PUBDEV-6147] Download links.
  h2o-web/bower.json
Labels: Flow

#3217 ITA-362: always archive summary.txt on jenkins jobs
  scripts/jenkins/groovy/makeTarget.groovy
Labels: please review

#3219 PUBDEV-6190: Doc update for KMeans
  h2o-docs/src/product/data-science/k-means.rst
Labels: docs

#2940 [BUILD] Move to harbor.
  docker/Jenkinsfile-build-docker
  docker/Jenkinsfile-build-hadoop-docker
  docker/Jenkinsfile-build-xgb-docker
  docker/Makefile
  docker/jenkins-images/Dockerfile-build
  docker/jenkins-images/Dockerfile-build-base
  docker/jenkins-images/Dockerfile-build-hadoop
  docker/jenkins-images/Dockerfile-jdk-8-base
  docker/jenkins-images/Dockerfile-jdk-others
  docker/jenkins-images/Dockerfile-jdk-others-base
  docker/jenkins-images/Dockerfile-python
  docker/jenkins-images/Dockerfile-python-base
  docker/jenkins-images/Dockerfile-r
  docker/jenkins-images/Dockerfile-r-base
  docker/jenkins-images/Dockerfile-release
  docker/xgb/centos/common/sbin/install_java
  docker/xgb/centos/common/sbin/install_packages
  docker/xgb/common/sbin/install_python
  docker/xgb/ubuntu/common/sbin/install_java
  docker/xgb/ubuntu/common/sbin/install_packages
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#3224 [BUILD] Move to harbor.
  docker/Jenkinsfile-build-docker
  docker/Jenkinsfile-build-hadoop-docker
  docker/Jenkinsfile-build-xgb-docker
  docker/Makefile
  docker/jenkins-images/Dockerfile-build
  docker/jenkins-images/Dockerfile-build-base
  docker/jenkins-images/Dockerfile-build-hadoop
  docker/jenkins-images/Dockerfile-jdk-8-base
  docker/jenkins-images/Dockerfile-jdk-others
  docker/jenkins-images/Dockerfile-jdk-others-base
  docker/jenkins-images/Dockerfile-python
  docker/jenkins-images/Dockerfile-python-base
  docker/jenkins-images/Dockerfile-r
  docker/jenkins-images/Dockerfile-r-base
  docker/jenkins-images/Dockerfile-release
  docker/xgb/centos/common/sbin/install_java
  docker/xgb/centos/common/sbin/install_packages
  docker/xgb/common/sbin/install_python
  docker/xgb/ubuntu/common/sbin/install_java
  docker/xgb/ubuntu/common/sbin/install_packages
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#3135 [BUILD] Fix docker images
  docker/Jenkinsfile-build-docker
  docker/jenkins-images/Dockerfile-build-base
  docker/jenkins-images/Dockerfile-jdk-others-base
  docker/jenkins-images/Dockerfile-python-base
  docker/jenkins-images/Dockerfile-r-base
  docker/jenkins-images/Dockerfile-release
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
Labels: ITA

#3225 [FLOW-PUBDEV-6192] Fix frame split.
  h2o-web/bower.json
Labels: Flow

#3211 PUBDEV-6198: Make sure H2ONode never loses a Sending Thread
  h2o-core/src/main/java/water/AutoBuffer.java
  h2o-core/src/main/java/water/ClientDisconnectCheckThread.java
  h2o-core/src/main/java/water/ClientRandomDisconnectThread.java
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/main/java/water/H2ONode.java
  h2o-core/src/main/java/water/MRTask.java
  h2o-core/src/main/java/water/Paxos.java
  h2o-core/src/main/java/water/RPC.java
  h2o-core/src/main/java/water/TCPReceiverThread.java
  h2o-core/src/main/java/water/UDPClientEvent.java
  h2o-core/src/main/java/water/UDPHeartbeat.java
  h2o-core/src/main/java/water/init/NetworkInit.java
  h2o-core/src/main/java/water/util/JStackCollectorTask.java
  h2o-core/src/test/java/water/ClientJarMD5IgnoreTest.java
  h2o-core/src/test/java/water/ClientReconnectSimulationTest.java
  h2o-core/src/test/java/water/ExternalFrameReaderClientTest.java
  h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java
  h2o-core/src/test/java/water/UnknownHeartbeatTest.java
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: WIP

#3206 ITA-362: move test lookups into Makefile
  .gitignore
  docker/scripts/build-h2o-3
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/buildH2O3.groovy
  scripts/jenkins/groovy/insideDocker.groovy
  scripts/jenkins/groovy/makeTarget.groovy
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: ITA

#3230 [FLOW] Multiple bugfixes.
  h2o-web/bower.json
Labels: Flow

#3236 Updated the default min_rows default value for DRF, IF, and XGBoost
  h2o-docs/src/product/data-science/algo-params/min_rows.rst
Labels: docs

#3242 [BUILD] Remove Java 7 smokes - SSL issues.
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: ITA

#3237 [FLOW] Do not render big CM. Monotone constraints UI. Fix Flow tests.
  h2o-web/bower.json
Labels: Flow, ITA

#3246 [ITA] Gradle 4.10.1, Java 7 Smokes.
  docker/Jenkinsfile-build-docker
  docker/Makefile
  docker/jenkins-images/Dockerfile-jdk-others
  docker/jenkins-images/Dockerfile-openjdk-others
  docker/jenkins-images/Dockerfile-r-base
  docker/scripts/install_java_version_open_jdk
  docker/scripts/java-11-vars.sh
  docker/scripts/java-7-vars.sh
  docker/scripts/java-8-vars.sh
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/makeTarget.groovy
Labels: ITA, WIP

#3248 Fix HTTPS on Jetty 9 (for Hadoop 3.x)
  h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Helper.java
  h2o-jetty-9/src/main/java/water/webserver/jetty9/TransparentProxyServlet.java
  h2o-py/scripts/h2o-py-test-setup.py
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/hadoopStage.groovy
  scripts/run.py
Labels: WIP

#3255 PUBDEV-6174: In H2O-3, Gini is only available for binary classification
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs
