Repository h2oai/h2o-3, pull requests merged in 2019-08, with the labels that each got.

#3755 PUBDEV-6603 - H2OFrame.split_frame() leaks a _splitter object
  h2o-py/h2o/frame.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_5352.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_6603.py
Labels: please review

#3712 Docs: Instructions to add cloud-boothook to force execution of user-data
  h2o-docs/src/product/productionizing.rst
Labels: approved

#3770 Add H2ONode, H2OLeafNode, and H2OSplitNode to docs
  h2o-py/docs/tree.rst
  h2o-py/h2o/tree/__init__.py
Labels: docs

#3772 Updated description of GBM to include newer distribution options
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/data-science/svm.rst
Labels: docs

#3773 PUBDEV 6732 - Cannot export model using java-rest-bindings
  h2o-bindings/bin/gen_java.py
  h2o-bindings/src/main/java/water/bindings/examples/retrofit/GBM_Example.java
Labels: please review

#3769 PUBDEV-6742: Create examples for the Tree Class section in the Python documentation
  h2o-py/h2o/tree/tree.py
Labels: docs

#3767 PUBDEV-6741: Create examples for the Autoencoder section in the Python documentation
  h2o-py/h2o/model/autoencoder.py
Labels: docs

#3768 PUBDEV-6731: Create examples for the Regression section in the Python documentation
  h2o-py/h2o/model/regression.py
Labels: docs

#3766 PUBDEV-6730: Create examples for the Clustering Methods section in the Python documentation
  h2o-py/h2o/model/clustering.py
Labels: docs

#3779 PUBDEV-6750: removed "enum" from XGBoost
  h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#3781 PUBDEV-6760: Fix for handling of categorical values in GLM docs
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#3756 PUBDEV-6513 XGBoost MOJO import
  h2o-algos/src/main/java/hex/generic/Generic.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostModelAttributes.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/SharedTreeModelAttributes.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_xgboost.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_xgboost.R
Labels: please review

#3795 Build mojocompat image. Bump Java 12 links.
  docker/Jenkinsfile-build-docker
  docker/Makefile
  docker/jenkins-images/Dockerfile-mojocompat
  docker/scripts/java-12-vars.sh
  scripts/jenkins/groovy/buildConfig.groovy
Labels: ITA

#3796 PUBDEV-6782: Fix swapped by mistake API help messages for ModelParametersSchemaV3 class
  h2o-core/src/main/java/water/api/schemas3/ModelParameterSchemaV3.java
Labels: please review

#3805 fixed hyperparameter typos
  h2o-docs/src/product/grid-search.rst
Labels: docs

#3807 PUBDEV-6771: predict_leaf_node_assignment is now supported in XGBoost
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#3809 PUBDEV-6761: Create examples for the Assembly section in the Python documentation
  h2o-py/h2o/assembly.py
Labels: docs

#3811 PUBDEV-6791: added options to the h2o.init() section of the User Guide
  h2o-docs/src/product/starting-h2o.rst
Labels: docs

#3812 PUBDEV-6792: Python docs: Add bind_to_localhost to list of paramters for h2o.init()
  h2o-py/h2o/h2o.py
Labels: docs

#3801 PUBDEV-6733: Add shapley example to predict_contributions documentation
  h2o-docs/src/product/performance-and-prediction.rst
  h2o-py/demos/predict_contributionsShap.ipynb
Labels: docs

#3817 [PUBDEV-6802] Move initFrame and finalizeFrame to ExternalFrame API
  h2o-core/src/main/java/water/ExternalBackendRequestType.java
  h2o-core/src/main/java/water/ExternalFrameHandler.java
  h2o-core/src/main/java/water/ExternalFrameReaderClient.java
  h2o-core/src/main/java/water/ExternalFrameWriterBackend.java
  h2o-core/src/main/java/water/ExternalFrameWriterClient.java
  h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java
Labels: WIP

#3819 PUBDEV-6753: Fix mismatch between sorted grid metric and corresponding metric from the model
  h2o-core/src/main/java/hex/AUC2.java
  h2o-core/src/main/java/hex/ModelMetrics.java
  h2o-core/src/main/java/hex/ModelMetricsBinomial.java
  h2o-py/tests/testdir_algos/gbm/pyunit_grid_f2_f0point5_metrics_PUBDEV-6753.py
Labels: please review

#3822 PUBDEV-6703: Add links to custom distribution and custom loss function demos
  h2o-docs/src/product/data-science/algo-params/custom_distribution_func.rst
  h2o-docs/src/product/data-science/gbm.rst
Labels: docs

#3824 PUBDEV-6816: New plug_values in GLM
  h2o-docs/src/product/data-science/algo-params/missing_values_handling.rst
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#3744 PUBDEV-6715: sklearn wrappers for AutoML and other Estimators
  h2o-bindings/bin/gen_python.py
  h2o-py/h2o/backend/connection.py
  h2o-py/h2o/estimators/__init__.py
  h2o-py/h2o/estimators/aggregator.py
  h2o-py/h2o/estimators/coxph.py
  h2o-py/h2o/estimators/deeplearning.py
  h2o-py/h2o/estimators/deepwater.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/generic.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/glrm.py
  h2o-py/h2o/estimators/isolation_forest.py
  h2o-py/h2o/estimators/kmeans.py
  h2o-py/h2o/estimators/naive_bayes.py
  h2o-py/h2o/estimators/pca.py
  h2o-py/h2o/estimators/psvm.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/h2o/estimators/svd.py
  h2o-py/h2o/estimators/word2vec.py
  h2o-py/h2o/estimators/xgboost.py
  h2o-py/h2o/model/regression.py
  h2o-py/h2o/sklearn/__init__.py
  h2o-py/h2o/sklearn/wrapper.py
  h2o-py/h2o/transforms/decomposition.py
  h2o-py/h2o/utils/shared_utils.py
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_api.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_automl_pipeline.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_pipeline.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_search_pipeline.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_estimators_as_transformers.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_generic_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_params.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_regression_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_regression_pipeline.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_regression_search_pipeline.py
  scripts/run.py
Labels: please review

#3845 PUBDEV-6837 - Support for Target Encoding in Flow (H2O-3 part)
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderBuilder.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderModel.java
  h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderV3.java
  h2o-py/h2o/estimators/targetencoder.py
  h2o-r/h2o-package/R/targetencoder.R
  h2o-web/bower.json
Labels: please review
