Repository h2oai/h2o-3, pull requests merged in 2019-12, with the labels that each got.

#4091 PUBDEV-6572: AutoML set default max_runtime_secs=1h iff max_models is not set by user
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/water/automl/api/AutoMLBuilderHandler.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-docs/src/product/automl.rst
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/job.py
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-r/h2o-package/R/automl.R
Labels: please review

#4083 PUBDEV-6924: Python Docs: Add examples to CoxProportionalHazards
  h2o-bindings/bin/custom/python/gen_coxph.py
  h2o-py/h2o/estimators/coxph.py
Labels: docs

#4081 PUBDEV-7070: Docs - AutoML Fixes
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
Labels: docs

#4115 PUBDEV-7066: expose mae, rmsle, aucpr to GridSearch in Py client
  h2o-py/h2o/backend/connection.py
  h2o-py/h2o/grid/grid_search.py
  h2o-py/h2o/h2o.py
  h2o-py/h2o/model/metrics_base.py
  h2o-py/h2o/model/model_base.py
  h2o-py/h2o/utils/backward_compatibility.py
  h2o-py/h2o/utils/metaclass.py
  h2o-py/h2o/utils/shared_utils.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_5665_pr_auc.py
  h2o-py/tests/testdir_misc/pyunit_grid_metric_accessors.py
  h2o-py/tests/testdir_misc/pyunit_make_metrics.py
  h2o-py/tests/testdir_misc/pyunit_metric_accessors.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/models.R
Labels: please review

#4119 [PUBDEV-7121] Parallel grid search does not handle max_runtime_secs == 0 for unlimited search
  h2o-algos/src/test/java/hex/grid/GridTest.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/hex/grid/HyperSpaceSearchCriteria.java
  h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
Labels: 4RELEASE

#4120 PUBDEV-6796 - Spearman's correlation
  h2o-core/src/main/java/water/fvec/Frame.java
  h2o-core/src/main/java/water/rapids/Env.java
  h2o-core/src/main/java/water/rapids/Merge.java
  h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstSpearman.java
  h2o-core/src/main/java/water/util/FrameUtils.java
  h2o-core/src/test/java/water/rapids/RapidsTest.java
Labels: please review

#4118 Docs: removed note from XGBoost chapter saying that it is a WIP
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#3332 PUBDEV-6542 - Distributed JUnit key leak test with RapidsTest as the first testsuite using it
  h2o-core/src/test/java/water/rapids/RapidsTest.java
  h2o-core/src/test/java/water/runner/CheckKeysTask.java
  h2o-core/src/test/java/water/runner/CleanAllKeysTask.java
  h2o-core/src/test/java/water/runner/CloudSize.java
  h2o-core/src/test/java/water/runner/CollectInitKeysTask.java
  h2o-core/src/test/java/water/runner/H2ORunner.java
  h2o-core/src/test/java/water/runner/H2ORunnerAfters.java
  h2o-core/src/test/java/water/runner/H2ORunnerBefores.java
  h2o-core/src/test/java/water/runner/LocalTestRuntime.java
Labels: please review

#4124 PUBDEV-7074: AutoML leaderboard extensions
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/FrameMetadata.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsExecutor.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsRegistry.java
  h2o-automl/src/main/java/ai/h2o/automl/events/EventLog.java
  h2o-automl/src/main/java/ai/h2o/automl/events/EventLogEntry.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/Leaderboard.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/LeaderboardCell.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/LeaderboardColumn.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/LeaderboardExtensionsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/MetricScore.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/ModelId.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/ModelSize.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/ScoringTimePerRow.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/TrainingTime.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
  h2o-automl/src/main/java/water/automl/api/AutoMLHandler.java
  h2o-automl/src/main/java/water/automl/api/LeaderboardsHandler.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/EventLogEntryV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/EventLogV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/LeaderboardV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/LeaderboardsV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-automl/src/test/java/ai/h2o/automl/LeaderboardTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepRegistryTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepsExecutorTest.java
  h2o-automl/src/test/java/ai/h2o/automl/events/EventLogTest.java
  h2o-automl/src/test/java/ai/h2o/automl/leaderboard/LeaderboardTest.java
  h2o-core/src/main/java/water/parser/ParseSetup.java
  h2o-py/h2o/automl/__init__.py
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/frame.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_get_automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
Labels: 4RELEASE

#4137 disabling XGBoost in multinode
  h2o-automl/src/main/java/ai/h2o/automl/Algo.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
Labels: 4RELEASE

#4065 PUBDEV-6769: Create examples for the H2O Module section in the Python documentation
  h2o-py/docs/conf.py
  h2o-py/h2o/__init__.py
  h2o-py/h2o/h2o.py
Labels: docs

#4122 PUBDEV-7116: Python Docs: Add examples to PSVM
  h2o-bindings/bin/custom/python/gen_psvm.py
  h2o-py/h2o/estimators/psvm.py
Labels: docs

#4139 PUBDEV-7137 - Categorical node split description generation - NullPointerException
  h2o-algos/src/main/java/hex/tree/TreeHandler.java
  h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java
Labels: 4RELEASE

#4141 PUBDEV-7143: Docs - MOJO import support for XGBoost
  h2o-docs/src/product/save-and-load-model.rst
Labels: docs

#4142 PUBDEV-7145: Docs - calibration_frame and calibrate_model options for XGBoost
  h2o-docs/src/product/data-science/algo-params/calibrate_model.rst
  h2o-docs/src/product/data-science/algo-params/calibration_frame.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#4067 PUBDEV-6447 constrained kmeans POC
  h2o-algos/src/main/java/hex/kmeans/KMeans.java
  h2o-algos/src/main/java/hex/kmeans/KMeansModel.java
  h2o-algos/src/main/java/hex/kmeans/KMeansSimplexSolver.java
  h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
  h2o-algos/src/test/java/hex/kmeans/KmeansConstrainedTest.java
  h2o-docs/src/product/data-science/k-means.rst
Labels: 4RELEASE

#4143 PUBDEV-7146: Docs - Support for Java 13
  h2o-docs/src/product/welcome.rst
Labels: docs

#4140 PUBDEV-7142: Docs - MOJOs available for PCA
  h2o-docs/src/product/mojo-quickstart.rst
  h2o-genmodel/src/main/java/overview.html
Labels: docs

#4104 PUBDEV-7057: add JSON option of PrintMojo
  h2o-algos/src/test/java/hex/tree/PrintMojoTreeTest.java
  h2o-algos/src/test/resources/hex/tree/categorical.json
  h2o-algos/src/test/resources/hex/tree/categoricalOneHot.json
  h2o-algos/src/test/resources/hex/tree/gbmProstate.json
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/isofor/IsolationForestMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraph.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/TreeBackedMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
  h2o-genmodel/src/main/java/hex/genmodel/tools/PrintMojo.java
  h2o-genmodel/src/main/java/hex/genmodel/utils/GenmodelBitSet.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/tree/SharedTreeGraphTest.java
  h2o-py/h2o/__init__.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_misc/pyunit_print_mojo.py
Labels: please review

#4138 PUBDEV-6966 kmeans compute training metrics on dataset from parms
  h2o-algos/src/main/java/hex/kmeans/KMeans.java
  h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
  h2o-r/tests/testdir_algos/kmeans/runit_kmeans_parameters.R
Labels: 4RELEASE

#4146 PUBDEV-7128: Doc updates for HGLM
  h2o-docs/src/product/data-science/algo-params/hglm.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/grid-search.rst
  h2o-docs/src/product/images/h-likelihood.png
  h2o-docs/src/product/images/hglm_augmentation.png
  h2o-docs/src/product/images/hglm_linear_mixed_model1.png
  h2o-docs/src/product/images/hglm_linear_mixed_model2.png
  h2o-docs/src/product/images/hglm_variance_covariance.png
  h2o-docs/src/product/parameters.rst
Labels: 4RELEASE, docs

#4151 AutoML: adding stopping metric removed by mistake
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
Labels: 4RELEASE

#4144 PUBDEV-7141: aucpr updates etc for 3.28.0.1
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/monotone_constraints.rst
  h2o-docs/src/product/data-science/algo-params/sort_metric.rst
  h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
Labels: 4RELEASE, docs

#4152 PUBDEV-7072: bugfixes to AutoML w/r/t AUCPR
  h2o-py/h2o/automl/autoh2o.py
  h2o-r/h2o-package/R/automl.R
Labels: 4RELEASE

#4153 PUBDEV-7141: Updated R/Py leaderboard in AutoML userguide
  h2o-docs/src/product/automl.rst
Labels: 4RELEASE, docs

#4113 PUBDEV-6876: added HGLM Gaussian/Gaussian to H2O-3
  h2o-algos/src/main/java/hex/DataInfo.java
  h2o-algos/src/main/java/hex/api/MakeGLMModelHandler.java
  h2o-algos/src/main/java/hex/glm/ComputationState.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMMetricBuilder.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/glm/GLMTask.java
  h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
  h2o-algos/src/main/java/hex/schemas/GLMV3.java
  h2o-algos/src/main/java/hex/util/LinearAlgebraUtils.java
  h2o-algos/src/test/java/hex/glm/GLMBasicTestHGLM.java
  h2o-bindings/bin/custom/R/gen_glm.py
  h2o-core/src/main/java/hex/ModelMetricHGLMGaussianGaussianGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsHGLM.java
  h2o-core/src/main/java/hex/ModelMetricsHGLMGaussianGaussian.java
  h2o-core/src/main/java/hex/ModelMetricsHGLMGeneric.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsHGLMGaussianGaussianGenericV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsHGLMGaussianGaussianV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsHGLMGenericV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsHGLMV3.java
  h2o-core/src/main/java/water/fvec/Vec.java
  h2o-core/src/main/java/water/util/ArrayUtils.java
  h2o-core/src/main/resources/META-INF/services/water.api.Schema
  h2o-genmodel/src/main/java/hex/ModelCategory.java
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/model/metrics_base.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6876_HGLM_compare_R_large.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6876_HGLM_initial_values.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/glm.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/runitUtils/utilsR.R
  h2o-r/tests/testdir_algos/glm/runit_PUBDEV_6876_HGLM_setInitialValues.R
  h2o-r/tests/testdir_algos/glm/runit_PUBDEV_6876_HGLM_testAgainstR1.R
Labels: 4RELEASE, please review

#4150 PUBDEV-6929: Fix 1-hot encoder for POJO
  h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/OneHotEncoderColumnMapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/OneHotEncoderDomainMapConstructor.java
  h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/OneHotEncoderColumnMapperTest.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/OneHotEncoderDomainMapConstructorTest.java
Labels: 4RELEASE, WIP

#4097 [PUBDEV-7095] Allocate more time for clouding to fix Cloud 1 under 4 issue
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/test/java/water/TestUtil.java
  h2o-extensions/target-encoder/testMultiNode.sh
  h2o-extensions/target-encoder/testSingleNode.sh
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostParamsTest.java
Labels: please review

#4160 PUBDEV-7149 - Endless loop when CsvParser parser $ sign enclosed in quotes
  h2o-core/src/main/java/water/parser/CsvParser.java
  h2o-core/src/test/java/water/parser/CsvParserTest.java
Labels: please review

#4161 fix typo and list formatting in hglm sections
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#4164 PUBDEV-7078 - Tree API requires tree class to be specified for XGBoost in case of binomial
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTreeConverterTest.java
  h2o-py/tests/testdir_tree/pyunit_xgboost_tree.py
Labels: please review

#4165 PUBDEV-7088 - Tree Class documentation is difficult to interpret. Add examples.
  h2o-py/docs/conf.py
  h2o-py/h2o/tree/tree.py
Labels: please review

#4167 PUBDEV-6542 - Improve leak detection in JUnit tests
  h2o-core/src/test/java/water/rapids/RapidsTest.java
  h2o-core/src/test/java/water/runner/CheckKeysTask.java
  h2o-core/src/test/java/water/runner/CleanAllKeysTask.java
  h2o-core/src/test/java/water/runner/CloudSize.java
  h2o-core/src/test/java/water/runner/CollectInitKeysTask.java
  h2o-core/src/test/java/water/runner/H2ORunner.java
  h2o-core/src/test/java/water/runner/H2ORunnerAfters.java
  h2o-core/src/test/java/water/runner/H2ORunnerBefores.java
  h2o-core/src/test/java/water/runner/LocalTestRuntime.java
Labels: please review

#4175 PUBDEV-7172: Replace "View Page Source" link with "Edit on GitHub"
  h2o-docs/src/product/conf.py
  h2o-docs/src/product/data-science/glm.rst
Labels: docs
