Repository h2oai/h2o-3, pull requests merged in 2020-03, with the labels that each got.

#4378 PUBDEV-7328: Add to docs that can now control number of columns to display in dataframe in R client in Jupyter notebook
  h2o-r/h2o-package/R/frame.R
Labels: docs

#4381 PUBDEV-6599: Change the output of get_automl in Python from a dictionary to an object
  h2o-py/h2o/automl/_base.py
  h2o-py/h2o/automl/_h2o_automl_output.py
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_get_automl.py
Labels: please review, python

#4325 PUBDEV-7305: missing model timing properties in client mode
  h2o-algos/src/main/java/hex/ensemble/Metalearner.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-r/tests/testdir_misc/runit_model_output_timing.R
Labels: please review

#4386 TargetEncoderModel's summary prints fold column as column that is going to be encoded by this model
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderModel.java
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_add_te_model_to_a_regular_model.py
Labels: please review

#4370 PUBDEV-6852 - Kubernetes support
  build.gradle
  h2o-assemblies/main/build.gradle
  h2o-core/src/main/java/water/H2O.java
  h2o-core/src/main/java/water/init/EmbeddedConfigProvider.java
  h2o-k8s/README.md
  h2o-k8s/build.gradle
  h2o-k8s/src/main/java/water/k8s/KubernetesEmbeddedConfig.java
  h2o-k8s/src/main/java/water/k8s/KubernetesEmbeddedConfigProvider.java
  h2o-k8s/src/main/java/water/k8s/lookup/ClusterSizeConstraint.java
  h2o-k8s/src/main/java/water/k8s/lookup/KubernetesDnsLookup.java
  h2o-k8s/src/main/java/water/k8s/lookup/KubernetesLookup.java
  h2o-k8s/src/main/java/water/k8s/lookup/LookupConstraint.java
  h2o-k8s/src/main/java/water/k8s/lookup/LookupConstraintsBuilder.java
  h2o-k8s/src/main/java/water/k8s/lookup/TimeoutConstraint.java
  h2o-k8s/src/main/resources/META-INF/services/water.init.EmbeddedConfigProvider
  h2o-k8s/src/test/java/water/k8s/KubernetesEmbeddedConfigProviderTest.java
  h2o-k8s/src/test/java/water/k8s/lookup/LookupConstraintsBuilderTest.java
  settings.gradle
Labels: please review

#4388 PUBDEV-6787: Populate base_models attribute in Stacked Ensemble in Python and R
  h2o-bindings/bin/custom/R/gen_stackedensemble.py
  h2o-bindings/bin/custom/python/gen_stackedensemble.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_base_models.py
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/R/stackedensemble.R
  h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_base_models_user_readable.R
Labels: R, please review, python

#4355 [PUBDEV-6900] xgboost 1.0.0
  docker/Jenkinsfile-build-xgb-build-docker
  docker/xgb/centos/common/sbin/install_packages
  docker/xgb/ubuntu/Dockerfile-ubuntu-gpu
  docker/xgb/ubuntu/Dockerfile-ubuntu-minimal
  docker/xgb/ubuntu/common/sbin/install_packages
  docker/xgb_build/Dockerfile-gpu-centos
  docker/xgb_build/Dockerfile-gpu-ubuntu
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-extensions/xgboost/build.gradle
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostExtension.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/predict/XGBoostNativePredict.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/util/BoosterDump.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/util/BoosterHelper.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/util/NativeLibrary.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/util/NativeLibraryLoaderChain.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/util/Platform.java
  h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
  h2o-extensions/xgboost/src/test/java/biz/k11i/xgboost/tree/XgbPredictContribsTest.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/DefaultMojoImplTest.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostMultiNodeTest.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
  h2o-genmodel-extensions/xgboost/build.gradle
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/OneHotEncoderFactory.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostJavaMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoReader.java
  h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostNativeMojoModel.java
  h2o-genmodel-extensions/xgboost/src/main/resources/META-INF/services/ml.dmlc.xgboost4j.java.INativeLibLoader
  h2o-genmodel-extensions/xgboost/src/test/java/hex/genmodel/algos/xgboost/XGBoostNativeMojoModelTest.java
  h2o-py/test-requirements.txt
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/pipelineUtils.groovy
Labels: please review

#4389 PUBDEV-4534: Add the possibility to use Grids as base model for StackedEnsemble
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
  h2o-bindings/bin/custom/R/gen_stackedensemble.py
  h2o-bindings/bin/custom/python/gen_stackedensemble.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/h2o/grid/grid_search.py
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_base_models.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/constants.R
  h2o-r/h2o-package/R/stackedensemble.R
  h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_base_models_using_grid.R
Labels: R, please review, python

#4406 PUBDEV-7167 - DeepLearning MOJO support in Generic Model
  h2o-algos/src/main/java/hex/generic/Generic.java
  h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
  h2o-algos/src/test/java/hex/generic/GenericModelTest.java
  h2o-core/src/main/java/hex/ModelMetricsBinomialGLMGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsBinomialGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsMultinomialGLMGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsMultinomialGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsOrdinalGLMGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsOrdinalGeneric.java
  h2o-core/src/main/java/hex/ModelMetricsRegressionGeneric.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsMultinomialGLMGenericV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsOrdinalGLMGenericV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsOrdinalGenericV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsRegressionGenericV3.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/deeplearning/DeeplearningMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/DeepLearningModelAttributes.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/SharedTreeModelAttributes.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/VariableImportances.java
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_deeplearning.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_deeplearning.R
Labels: please review

#4379 PUBDEV-7187: Update docs describing how to access Java bindings
  h2o-docs/src/product/faq/java.rst
Labels: docs

#4420 Generic model predictions are compares with original model predictions. Scope management used test-wide.
  h2o-algos/src/test/java/hex/generic/GenericModelTest.java
Labels: please review

#4387 PUBDEV-7358: changed order of parameter for TargetEncoder's Flow UI
  h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderV3.java
  h2o-py/h2o/estimators/targetencoder.py
  h2o-r/h2o-package/R/targetencoder.R
Labels: please review

#4385 PUBDEV-6955: Python - modify StackEnsemble's metalearner property to …
  h2o-bindings/bin/custom/R/gen_stackedensemble.py
  h2o-bindings/bin/custom/python/gen_stackedensemble.py
  h2o-bindings/bin/gen_python.py
  h2o-py/h2o/estimators/deepwater.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/h2o/estimators/targetencoder.py
  h2o-py/h2o/estimators/xgboost.py
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_metalearner.py
  h2o-r/h2o-package/R/stackedensemble.R
  h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_metalearner.R
Labels: R, please review, python

#4430 PUBDEV-7337: SQL Import: Fixes & perf improvements
  h2o-core/src/jmh/java/water/jdbc/SQLManagerBench.java
  h2o-core/src/main/java/water/api/ImportSQLTableHandler.java
  h2o-core/src/main/java/water/api/schemas3/ImportSQLTableV99.java
  h2o-core/src/main/java/water/jdbc/SQLManager.java
  h2o-core/src/test/java/water/jdbc/SQLManagerIntegTest.java
  h2o-core/src/test/java/water/parser/ImportSQLTest.java
  h2o-py/h2o/h2o.py
Labels: WIP

#4443 PUBDEV-7394: Fix base_models selection for StackedEnsemble
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-docs/src/product/flow/packs/test-small/index.list
  h2o-docs/src/product/flow/packs/test-small/stackedensemble_weather.flow
  h2o-web/bower.json
Labels: 4RELEASE, Flow, please review

#4437 PUBDEV-7388: updated sphinx tabs
  h2o-docs/src/product/data-science/algo-params/cluster_size_constraints.rst
Labels: docs

#4313 Proposal: Attempt at simplifying contract and logic of Hyperspace iterator
  h2o-algos/src/test/java/hex/grid/GridTest.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-core/src/main/java/hex/ParallelModelBuilder.java
  h2o-core/src/main/java/hex/grid/Grid.java
  h2o-core/src/main/java/hex/grid/GridSearch.java
  h2o-core/src/main/java/hex/grid/HyperSpaceSearchCriteria.java
  h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
  h2o-core/src/main/java/hex/schemas/HyperSpaceSearchCriteriaV99.java
  h2o-docs/src/product/api-changes.rst
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
Labels: please review

#4464 PUBDEV-7407: Doc updates to performance and prediction section
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#4462 PUBDEV-7409 - Provide original algorithm name for MOJO import
  h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
  h2o-algos/src/main/java/hex/schemas/GenericModelV3.java
  h2o-algos/src/test/java/hex/generic/GenericModelTest.java
  h2o-py/tests/testdir_generic_model/pyunit_generic_model.py
Labels: 4RELEASE, please review

#4375 PUBDEV-6293: in AutoML, tune learning rate for best model found during exploration (XGB+GBM)
  h2o-automl/src/main/java/ai/h2o/automl/Algo.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/IAlgo.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelSelectionStrategies.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelSelectionStrategy.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingSteps.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsExecutor.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsRegistry.java
  h2o-automl/src/main/java/ai/h2o/automl/Models.java
  h2o-automl/src/main/java/ai/h2o/automl/StepDefinition.java
  h2o-automl/src/main/java/ai/h2o/automl/WorkAllocations.java
  h2o-automl/src/main/java/ai/h2o/automl/events/EventLog.java
  h2o-automl/src/main/java/ai/h2o/automl/events/EventLogEntry.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/Leaderboard.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/GBMStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/EventLogV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/StepDefinitionV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelSelectionStrategiesTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepRegistryTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepTest.java
  h2o-automl/src/test/java/ai/h2o/automl/dummy/AlgoRegister.java
  h2o-automl/src/test/java/ai/h2o/automl/dummy/DummyBuilder.java
  h2o-automl/src/test/java/ai/h2o/automl/dummy/DummyModel.java
  h2o-automl/src/test/java/ai/h2o/automl/dummy/DummyStepsProvider.java
  h2o-automl/src/test/resources/META-INF/services/water.api.RestApiExtension
  h2o-core/src/main/java/hex/ModelContainer.java
  h2o-core/src/main/java/hex/grid/Grid.java
  h2o-core/src/main/java/hex/grid/HyperSpaceSearchCriteria.java
  h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
  h2o-core/src/main/java/hex/grid/SequentialWalker.java
  h2o-core/src/test/java/water/runner/H2ORunner.java
  h2o-docs/src/product/automl.rst
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/frame.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_memory_cleanup.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
  h2o-r/tests/testdir_algos/automl/runit_automl_model_selection.R
Labels: 4RELEASE, AutoML, please review

#4460 PUBDEV-7413: Added parallel model building to Segment Models
  h2o-bindings/bin/gen_R.py
  h2o-core/src/main/java/hex/segments/LocalSequentialSegmentModelsBuilder.java
  h2o-core/src/main/java/hex/segments/SegmentModels.java
  h2o-core/src/main/java/hex/segments/SegmentModelsBuilder.java
  h2o-core/src/main/java/hex/segments/SegmentModelsStats.java
  h2o-core/src/main/java/water/api/schemas3/SegmentModelsParametersV3.java
  h2o-core/src/test/java/hex/segments/SegmentModelsBuilderTest.java
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/tests/testdir_algos/gbm/pyunit_gbm_parallel.py
  h2o-r/h2o-package/R/aggregator.R
  h2o-r/h2o-package/R/coxph.R
  h2o-r/h2o-package/R/deeplearning.R
  h2o-r/h2o-package/R/gbm.R
  h2o-r/h2o-package/R/glm.R
  h2o-r/h2o-package/R/glrm.R
  h2o-r/h2o-package/R/isolationforest.R
  h2o-r/h2o-package/R/kmeans.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/R/naivebayes.R
  h2o-r/h2o-package/R/pca.R
  h2o-r/h2o-package/R/psvm.R
  h2o-r/h2o-package/R/randomforest.R
  h2o-r/h2o-package/R/stackedensemble.R
  h2o-r/h2o-package/R/svd.R
  h2o-r/h2o-package/R/targetencoder.R
  h2o-r/h2o-package/R/word2vec.R
  h2o-r/h2o-package/R/xgboost.R
  h2o-r/tests/testdir_misc/runit_bulk_gbm_parallel.R
Labels: 4RELEASE

#4463 Local smalldata path prefix
  h2o-core/src/main/java/water/util/FileUtils.java
  h2o-core/src/test/java/water/util/FileUtilsTest.java
Labels: please review

#4458 PUBDEV-7406 - Target Encoding R example code is broken
  h2o-bindings/bin/custom/R/gen_targetencoder.py
  h2o-r/h2o-package/R/targetencoder.R
Labels: please review

#4415 PUBDEV-7380: Note in docs that "transform" is only for numeric data
  h2o-docs/src/product/data-science/aggregator.rst
  h2o-docs/src/product/data-science/algo-params/transform.rst
  h2o-docs/src/product/data-science/glrm.rst
  h2o-docs/src/product/data-science/pca.rst
  h2o-docs/src/product/faq/data.rst
Labels: docs

#4468 PUBDEV-7350: Doc update for fractionalbinomial family in GLM
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/booklets/v2_2015/source/GLM_Vignette_code_examples/glm_fractionalbinomial_example.R
  h2o-docs/src/booklets/v2_2015/source/GLM_Vignette_code_examples/glm_fractionalbinomial_example.py
  h2o-docs/src/product/data-science/algo-params/family.rst
  h2o-docs/src/product/data-science/algo-params/link.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/grid-search.rst
Labels: docs

#4475 PUBDEV-7419: Doc updates for 3.28.1.3 release
  h2o-docs/src/product/getting-data-into-h2o.rst
  h2o-docs/src/product/starting-h2o.rst
Labels: 4RELEASE, docs
