Repository h2oai/h2o-3, pull requests merged in 2020-11, with the labels that each got.

#5086 [PUBDEV-7852] Refactor PreviewParseWriter to 'guessTypes' Method to be Used Independently
  h2o-core/src/main/java/water/parser/PreviewParseWriter.java
Labels: please review

#4895 PUBDEV-7736 use btree for coxph computation instead the direct approach
  h2o-algos/src/test/java/hex/ModelMetricsRegressionCoxPHTest.java
  h2o-core/src/main/java/hex/ModelMetricsRegressionCoxPH.java
  h2o-r/tests/testdir_algos/coxph/runit_coxph_concordance.R
  h2o-r/tests/testdir_algos/coxph/runit_coxph_concordance_heart.R
Labels: please review

#4995 [MOJO2] Refactor loading of pipeline to load only metadata, not full pipeline.
  h2o-extensions/mojo-pipeline/src/main/java/hex/mojopipeline/MojoPipeline.java
Labels: 4RELEASE

#5117 PUBDEV-7877: Add XGB and GBM feature interactions to docs
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#5102 PUBDEV-7774 Implement XGBoost Feature Interaction Constraint
  h2o-algos/src/main/java/hex/DataInfo.java
  h2o-core/src/main/java/water/AutoBuffer.java
  h2o-core/src/main/java/water/IcedWrapper.java
  h2o-core/src/main/java/water/util/ArrayUtils.java
  h2o-docs/src/product/data-science/algo-params/interaction_constraints.rst
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostV3.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostModelTest.java
  h2o-py/h2o/estimators/xgboost.py
  h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_interactions.py
  h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_monotone.py
  h2o-py/tests/testdir_tree/pyunit_xgboost_tree.py
  h2o-r/h2o-package/R/constants.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/R/xgboost.R
  h2o-r/tests/testdir_algos/xgboost/runit_xgboost_interaction_constraints.R
Labels: 4RELEASE, please review

#5128 PUBDEV-7898: Add a link to Data Manipulation page leading to W2V & TE
  h2o-docs/src/product/data-munging.rst
Labels: docs

#5120 PUBDEV-7888: Added missing Python example to `stratify_by` algo page
  h2o-docs/src/product/data-science/algo-params/stratify_by.rst
Labels: docs

#5133 PUBDEV-7900 - custom pod labels
  h2o-helm/templates/statefulset.yaml
  h2o-helm/values.yaml
Labels: 4RELEASE

#5130 PUBDEV-7899: Release Notes for 3.32.0.2
  Changes.md
Labels: docs

#5143 Rulefit: update docs for model_type parameter
  h2o-docs/src/product/data-science/rulefit.rst
Labels: docs

#5142 PUBDEV-7905: Correct k for PCA that can be up to number of columns
  h2o-docs/src/product/data-science/pca.rst
  h2o-docs/src/product/parameters.rst
Labels: docs

#5106 PUBDEV-7913: Fix as.data.frame.H2OFrame
  h2o-r/h2o-package/R/frame.R
  h2o-r/tests/testdir_misc/runit_as.frame.R
Labels: R

#5154 PUBDEV-7849: Remove unused newdata arg from .plot_varimp
  h2o-r/h2o-package/R/explain.R
Labels: R
