Repository h2oai/h2o-3, pull requests merged in 2020-10, with the labels that each got.

#4984 PUBDEV-7817: Speed up model_summary computations in AutoML Stacked Ensembles in R
  h2o-bindings/bin/custom/R/gen_stackedensemble.py
  h2o-r/h2o-package/R/stackedensemble.R
Labels: R, please review

#4987 PUBDEV-7815: Update Rulefit page default values
  h2o-docs/src/product/data-science/rulefit.rst
Labels: docs

#4992 PUBDEV-7781: Make explicit the categorical_encoding default in xgboost docs
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#4932 PUBDEV-7796: Model explainability interface for H2O models and AutoML objects in R/Python
  h2o-py/h2o/__init__.py
  h2o-py/h2o/explanation/__init__.py
  h2o-py/h2o/explanation/_explain.py
  h2o-py/tests/testdir_misc/pyunit_explain.py
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package/R/explain.R
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/testdir_misc/runit_explain.R
Labels: R, WIP, please review, python

#4952 PUBDEV-7786: Model explainability user guide page
  h2o-docs/src/product/explain.rst
  h2o-docs/src/product/images/explain_ice_plot_wine_alcohol.png
  h2o-docs/src/product/images/explain_model_correlation_heatmap_wine.png
  h2o-docs/src/product/images/explain_pd_multiplot_wine_alcohol.png
  h2o-docs/src/product/images/explain_pd_plot_wine_alcohol.png
  h2o-docs/src/product/images/explain_residual_analysis_wine.png
  h2o-docs/src/product/images/explain_row_ice_plot_wine_alcohol_row1.png
  h2o-docs/src/product/images/explain_row_shap_row1.png
  h2o-docs/src/product/images/explain_shap_summary_wine.png
  h2o-docs/src/product/images/explain_varimp_heatmap_wine.png
  h2o-docs/src/product/images/explain_varimp_wine.png
  h2o-docs/src/product/index.rst
Labels: WIP

#4999 Fix order of pdp plots
  h2o-r/h2o-package/R/explain.R
Labels: R

#4996 Fix missing tkinter in py27 small test
  scripts/jenkins/Makefile.jenkins
Labels: please review, python

#4976 PUBDEV-7811: Update Python FAQ import datatype in UserGuide
  h2o-docs/src/product/faq/python.rst
Labels: docs

#5006 PUBDEV-7541: Update the AutoML description doc string
  h2o-py/h2o/automl/autoh2o.py
  h2o-r/h2o-package/R/automl.R
Labels: 4RELEASE, R, please review, python

#5007 Make sure RuleFit doesn't leak temporary frames created in scoring
  h2o-algos/src/main/java/hex/rulefit/Rule.java
  h2o-algos/src/main/java/hex/rulefit/RuleEnsemble.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
  h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
  h2o-core/src/main/java/water/fvec/Frame.java
Labels: 4RELEASE

#5005 Add code examples for all the new explainability plotting functions in Python and R (PUBDEV-7824, PUBDEV-7821)
  h2o-docs/src/product/explain.rst
  h2o-py/h2o/explanation/_explain.py
  h2o-r/h2o-package/R/explain.R
Labels: 4RELEASE, R, please review, python

#4989 PUBDEV-7816: Update `validation_frame` definition for unsupervised algorithms
  h2o-docs/src/product/data-science/glrm.rst
  h2o-docs/src/product/data-science/k-means.rst
  h2o-docs/src/product/data-science/pca.rst
Labels: docs

#5017 Fix rendering of the factor levels
  h2o-r/h2o-package/R/explain.R
Labels: R, please review

#5014 RuleFit: Speed-up scoring
  h2o-algos/src/main/java/hex/rulefit/Condition.java
  h2o-algos/src/main/java/hex/rulefit/Rule.java
  h2o-algos/src/main/java/hex/rulefit/RuleEnsemble.java
  h2o-algos/src/main/java/hex/rulefit/RuleFit.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
  h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
  h2o-algos/src/test/java/hex/rulefit/RuleFitUtilsTest.java
  h2o-algos/src/test/java/hex/rulefit/RulefitTestUtils.java
  scripts/jenkins/Makefile.jenkins
Labels: 4RELEASE

#5019 Update descriptions in the explainability API
  h2o-py/h2o/explanation/_explain.py
  h2o-r/h2o-package/R/explain.R
Labels: 4RELEASE, R, python

#4922 PUBDEV-7745: Add default values for all arguments of modeling functions in User Guide
  h2o-docs/src/product/data-science/aggregator.rst
  h2o-docs/src/product/data-science/coxph.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gam.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/data-science/glrm.rst
  h2o-docs/src/product/data-science/if.rst
  h2o-docs/src/product/data-science/k-means.rst
  h2o-docs/src/product/data-science/naive-bayes.rst
  h2o-docs/src/product/data-science/pca.rst
  h2o-docs/src/product/data-science/stacked-ensembles.rst
  h2o-docs/src/product/data-science/svm.rst
  h2o-docs/src/product/data-science/word2vec.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#4968 PUBDEV-7808 - Helm chart
  docker/jenkins-images/Dockerfile-k8s-test
  docker/jenkins-images/Dockerfile-release
  h2o-helm/.helmignore
  h2o-helm/Chart.yaml
  h2o-helm/example.yaml
  h2o-helm/templates/NOTES.txt
  h2o-helm/templates/_helpers.tpl
  h2o-helm/templates/ingress.yaml
  h2o-helm/templates/service.yaml
  h2o-helm/templates/statefulset.yaml
  h2o-helm/templates/tests/test-connection.yaml
  h2o-helm/values.yaml
  h2o-k8s/src/main/java/water/k8s/KubernetesEmbeddedConfigProvider.java
  h2o-k8s/tests/clustering/docker-init-script.sh
  h2o-k8s/tests/clustering/h2o-service.yaml
  h2o-k8s/tests/clustering/testvalues-template.yaml
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Labels: 4RELEASE

#5023 Document K8S Helm & reproducibility
  h2o-docs/src/product/cloud-integration/kubernetes.rst
Labels: 4RELEASE

#5024 [xgboost] update excluded libs after 1.2.0 upgrade
  h2o-extensions/xgboost/build.gradle
Labels: 4RELEASE

#5027 [build] xgboost whl now requires py3.6
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: 4RELEASE

#5029 Fix K8S service name propagation
  h2o-helm/templates/statefulset.yaml
Labels: 4RELEASE

#5022 Put HELM instructions into H2O download page
  h2o-dist/index.html
Labels: 4RELEASE

#5037 Instruct users to helm install latest version in the repository on do…
  h2o-dist/index.html
Labels: 4RELEASE

#5016 PUBDEV-7826: Release notes for 3.32.0.1
  Changes.md
Labels: 4RELEASE, docs

#5048 PUBDEV-7837: Added `rule_generation_ntrees` Parameter to RuleFit Guide
  h2o-docs/src/product/data-science/rulefit.rst
Labels: docs

#5049 PUBDEV-7836: Missing syntax highlight Random Grid search Python example
  h2o-docs/src/product/grid-search.rst
Labels: docs

#5039 Fix histogram in PDP/ICE for categorical variables in python
  h2o-py/h2o/explanation/_explain.py
Labels: python

#5056 [PUBDEV-7846] Finalization API with Leaving Frames Locked
  h2o-core/src/main/java/water/fvec/ChunkUtils.java
  h2o-core/src/main/java/water/fvec/Frame.java
Labels: please review
