Repository h2oai/h2o-3, pull requests merged in 2020-02, with the labels that each got.

#4272 AutoML: simplifying logic for default stopping tolerance
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_args.R
Labels: please review

#4281 PUBDEV-7256: Updates to Hadoop documentation
  h2o-docs/src/product/welcome.rst
Labels: docs

#4276 PUBDEV-7189: ensure that AutoML works even if XGBoost extension is missing on the classpath
  h2o-automl/build.gradle
  h2o-automl/src/main/java/ai/h2o/automl/Algo.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelParametersProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsRegistry.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/DRFStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/DeepLearningStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/GBMStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/GLMStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostStepsProvider.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLBuildSpecTest.java
Labels: please review

#4315 Google Cloud H2O-3 Cluster Launcher doc update
  h2o-docs/src/product/cloud-integration/google-compute.rst
  h2o-docs/src/product/images/google_cloud_marketplace.png
Labels: docs

#4321 PUBDEV-7286: Update docs to specify that mtries=-2 gives all features
  h2o-docs/src/product/data-science/algo-params/mtries.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/if.rst
Labels: docs

#3974 PUBDEV-6964: Add to docs that MOJOs and POJOs are threadsafe
  h2o-docs/src/product/mojo-quickstart.rst
  h2o-docs/src/product/pojo-quickstart.rst
Labels: docs

#4258 PUBDEV-7227: unsupported Python bytecode instructions when calling `apply` on H2OFrame
  h2o-py/h2o/astfun.py
  h2o-py/h2o/expr.py
  h2o-py/tests/testdir_apis/Data_Manipulation/pyunit_h2oH2OFrame_apply.py
  h2o-py/tests/testdir_misc/pyunit_apply.py
Labels: please review

#4340 PUBDEV-7267 - Terminal nodes recognized by lack of children. Also, split column not filled for terminal nodes in case of XGBoost.
  h2o-algos/src/main/java/hex/tree/TreeHandler.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-py/tests/testdir_tree/pyunit_tree_pubdev_7267.py
Labels: please review

#4273 PUBDEV-6965: adding new ensemble metalearners
  h2o-algos/src/main/java/hex/ensemble/Metalearner.java
  h2o-algos/src/main/java/hex/ensemble/MetalearnerProvider.java
  h2o-algos/src/main/java/hex/ensemble/Metalearners.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
  h2o-bindings/bin/gen_python.py
  h2o-docs/src/product/data-science/algo-params/metalearner_algorithm.rst
  h2o-docs/src/product/data-science/stacked-ensembles.rst
  h2o-extensions/xgboost/src/main/java/hex/ensemble/XGBoostMetalearnerProvider.java
  h2o-extensions/xgboost/src/main/resources/META-INF/services/hex.ensemble.MetalearnerProvider
  h2o-py/h2o/estimators/__init__.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_metalearner.py
  h2o-r/h2o-package/R/stackedensemble.R
Labels: please review

#4311 PUBDEV-7271 - Per-node sequential DKV manager
  h2o-algos/src/test/java/hex/DKVManagerTest.java
  h2o-core/src/main/java/water/DKVManager.java
  h2o-core/src/main/java/water/fvec/Frame.java
Labels: please review

#4346 Docs: remove psvm from list of metalerner_algorithms
  h2o-docs/src/product/data-science/algo-params/metalearner_algorithm.rst
  h2o-docs/src/product/data-science/stacked-ensembles.rst
Labels: docs

#4347 fix PUBDEV-6063 failing test (since changes in PUBDEV-7227)
  h2o-py/h2o/expr.py
  h2o-py/h2o/frame.py
Labels: 4RELEASE

#4343 PUBDEV-7312 - AWS Auth with session tokens
  h2o-persist-s3/src/main/java/water/persist/IcedS3Credentials.java
  h2o-persist-s3/src/main/java/water/persist/PersistS3.java
  h2o-persist-s3/src/main/java/water/persist/PersistS3CredentialsV3.java
  h2o-persist-s3/src/main/java/water/persist/PersistS3Handler.java
  h2o-persist-s3/src/test/java/water/persist/PersistS3Test.java
  h2o-py/h2o/persist/persist.py
  h2o-py/tests/testdir_persist/pyunit_persistence.py
  h2o-r/h2o-package/R/import.R
Labels: 4RELEASE

#4348 PUBDEV-7317: Add AWS Session Token to docs
  h2o-docs/src/product/cloud-integration/ec2-and-s3.rst
Labels: docs

#4352 PUBDEV-7317 - AWS temporary credentials using HDFS documentation
  h2o-docs/src/product/cloud-integration/ec2-and-s3.rst
Labels: 4RELEASE, please review

#4265 PUBDEV-4639: Added requirement for data.table.
  h2o-core/src/main/java/water/api/DatasetServlet.java
  h2o-core/src/main/java/water/fvec/Frame.java
  h2o-r/h2o-package/R/frame.R
  h2o-r/tests/testdir_jira/runit_pubdev_2844.R
  h2o-r/tests/testdir_misc/runit_as.frame.R
  h2o-r/tests/testdir_misc/runit_as.h2o.R
Labels: please review
