Repository h2oai/h2o-3, pull requests merged in 2020-09, with the labels that each got.

#4838 PUBDEV-7720 Rulefit POC
  h2o-algos/src/main/java/hex/api/RegisterAlgos.java
  h2o-algos/src/main/java/hex/rulefit/RuleFit.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitUtils.java
  h2o-algos/src/main/java/hex/schemas/RuleFitModelV3.java
  h2o-algos/src/main/java/hex/schemas/RuleFitV3.java
  h2o-algos/src/main/resources/META-INF/services/water.api.Schema
  h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
  h2o-bindings/bin/custom/R/gen_rulefit.py
  h2o-bindings/bin/custom/python/gen_rulefit.py
  h2o-bindings/bin/gen_python.py
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/remote/SteamExecutorStarterTest.java
  h2o-py/docs/modeling.rst
  h2o-py/h2o/estimators/__init__.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/rulefit.py
  h2o-py/tests/testdir_algos/rulefit/pyunit_titanic_rulefit.py
  h2o-r/H2O_Load.R
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package/R/rulefit.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
  h2o-test-support/src/main/java/water/TestUtil.java
Labels: WIP

#4765 PUBDEV-7657: link proper base R manuals in R h2o manual
  h2o-r/h2o-package/R/frame.R
Labels: R

#4893 PUBDEV-7744: Release notes for 3.30.1.2
  Changes.md
Labels: docs

#4904 PUBDEV-7759: Correct the API UserGuide formatting
  h2o-docs/src/product/api-changes.rst
Labels: docs

#4867 PUBDEV-7672: TargetEncoder support for multiclass problems.
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/EncodingsComponents.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderBroadcastJoin.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderHelper.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderModel.java
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderMojoWriter.java
  h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderModelOutputV3.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderBroadcastJoinTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderModelTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderMojoIntegrationTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderMojoWriterTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderTestSuite.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingExceptionsHandlingTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingHelperTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingImmutabilityTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingKFoldStrategyTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingLeaveOneOutStrategyTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingNoneStrategyTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingOnBinaryTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingOnMulticlassTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingOnRegressionTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/strategy/AllCategoricalTEApplicationStrategyTest.java
  h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/strategy/ThresholdTEApplicationStrategyTest.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/targetencoder/EncodingMap.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/targetencoder/EncodingMaps.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/targetencoder/TargetEncoderMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/targetencoder/TargetEncoderMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/targetencoder/TargetEncoderMojoModelTest.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/targetencoder/TargetEncoderMojoReaderTest.java
  h2o-genmodel/src/test/java/hex/genmodel/easy/EasyPredictModelWrapperWithTargetEncodingTest.java
  h2o-py/tests/testdir_algos/targetencoder/golden/multinomial_kfold.csv
  h2o-py/tests/testdir_algos/targetencoder/golden/multinomial_loo.csv
  h2o-py/tests/testdir_algos/targetencoder/golden/multinomial_none.csv
  h2o-py/tests/testdir_algos/targetencoder/golden/regression_kfold.csv
  h2o-py/tests/testdir_algos/targetencoder/golden/regression_loo.csv
  h2o-py/tests/testdir_algos/targetencoder/golden/regression_none.csv
  h2o-py/tests/testdir_algos/targetencoder/pyunit_targetencoder_binomial.py
  h2o-py/tests/testdir_algos/targetencoder/pyunit_targetencoder_multinomial.py
  h2o-py/tests/testdir_algos/targetencoder/pyunit_targetencoder_regression.py
  h2o-r/tests/testdir_algos/targetencoder/runit_targetencoder_binary.R
  h2o-r/tests/testdir_algos/targetencoder/runit_targetencoder_multiclass.R
  h2o-r/tests/testdir_algos/targetencoder/runit_targetencoder_regression.R
Labels: please review

#4886 PUBDEV-7730: generate precision recall plots
  h2o-py/h2o/model/metrics_base.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_7730_plot_pr_xval.py
  h2o-py/tests/testdir_misc/pyunit_plot.py
  h2o-py/tests/testdir_misc/pyunit_plot_roc_pr_curve.py
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_misc/runit_curve_plot.R
Labels: 4RELEASE

#4928 PUBDEV-7763: Add a RuleFit page to the User Guide
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/rulefit.rst
Labels: docs

#4947 PUBDV-7787: Use HTTPS for all URLs in R package
  h2o-r/h2o-package/R/communication.R
  h2o-r/h2o-package/R/connection.R
  h2o-r/h2o-package/R/coxph.R
  h2o-r/h2o-package/R/datasets.R
  h2o-r/h2o-package/R/frame.R
  h2o-r/h2o-package/R/glrm.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/R/svd.R
Labels: docs

#4829 Fix Stacked Ensemble's retrieval of seed parameter value
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_seed.R
Labels: algos, please review

#4957 PUBDEV-7787: Use HTTPS for all URLs in R package
  h2o-bindings/bin/custom/R/gen_coxph.py
  h2o-bindings/bin/custom/R/gen_glrm.py
  h2o-bindings/bin/custom/R/gen_svd.py
  h2o-r/h2o-package/R/coxph.R
  h2o-r/h2o-package/R/glrm.R
  h2o-r/h2o-package/R/svd.R
Labels: docs
