Repository h2oai/h2o-3, pull requests merged in 2020-12, with the labels that each got.

#5163 PUBDEV-7922: RuleFit Python example corrections
  h2o-docs/src/product/data-science/rulefit.rst
Labels: docs

#5082 Fix warning from old matplotlib.use
  h2o-py/h2o/frame.py
  h2o-py/h2o/model/dim_reduction.py
  h2o-py/h2o/model/metrics_base.py
  h2o-py/h2o/model/model_base.py
  h2o-py/h2o/utils/ext_dependencies.py
Labels: python

#5169 An attempt to fix custom distribution error
  h2o-py/h2o/h2o.py
Labels: python

#5167 Fix warning from matplotlib in explain
  h2o-py/h2o/explanation/_explain.py
  h2o-py/h2o/frame.py
  h2o-py/h2o/utils/ext_dependencies.py
Labels: python

#5168 Fix failing R tests related to date time handling
  h2o-r/tests/runitUtils/utilsR.R
Labels: R

#5069 PUBDEV-7853: Fix learning curve for GLM
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-py/h2o/model/model_base.py
  h2o-r/h2o-package/R/models.R
  h2o-web/bower.json
Labels: Flow, R, please review, python

#5175 PUBDEV-7928: Fix custom distribution reuse
  h2o-core/src/main/java/hex/DistributionFactory.java
  h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4076_custom_distribution.py
Labels: algos, please review, python

#5186 Fix CoxPH scoring history
  h2o-algos/src/main/java/hex/coxph/CoxPH.java
Labels: algos

#5191 Assign iteration from the winning submodel to the final model when used with lambda search
  h2o-algos/src/main/java/hex/glm/GLMModel.java
Labels: algos

#5104 PUBDEV-7882: Python docstring examples about cross-validation are not using cross-validation
  h2o-bindings/bin/custom/python/gen_deeplearning.py
  h2o-py/h2o/estimators/deeplearning.py
Labels: docs

#5195 Fix missing argument in explain's get_algorithm
  h2o-py/h2o/explanation/_explain.py
Labels: python

#5201 3.32.0.3 Release Notes
  Changes.md
Labels: docs
