Repository h2oai/h2o-3, pull requests merged in 2020-04, with the labels that each got.

#4301 PUBDEV-7178/PUBDEV-7180 adding GAM Basic Model and ModelMetrics
  h2o-algos/src/main/java/hex/DataInfo.java
  h2o-algos/src/main/java/hex/api/RegisterAlgos.java
  h2o-algos/src/main/java/hex/gam/GAM.java
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-algos/src/main/java/hex/gam/GamSplines/CubicRegressionSplines.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/AddGamColumns.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GenerateGamMatrixOneColumn.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/TriDiagonalMatrix.java
  h2o-algos/src/main/java/hex/gam/MetricBuilderGAM.java
  h2o-algos/src/main/java/hex/glm/ComputationState.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/glm/GLMTask.java
  h2o-algos/src/main/java/hex/glm/GLMUtils.java
  h2o-algos/src/main/java/hex/gram/Gram.java
  h2o-algos/src/main/java/hex/optimization/OptimizationUtils.java
  h2o-algos/src/main/java/hex/schemas/GAMModelV3.java
  h2o-algos/src/main/java/hex/schemas/GAMV3.java
  h2o-algos/src/main/java/hex/util/LinearAlgebraUtils.java
  h2o-algos/src/main/resources/META-INF/services/water.api.Schema
  h2o-algos/src/test/java/hex/gam/GamTestPiping.java
  h2o-bindings/bin/custom/R/gen_gam.py
  h2o-bindings/bin/custom/python/gen_gam.py
  h2o-bindings/bin/gen_R.py
  h2o-bindings/bin/gen_python.py
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/water/util/ArrayUtils.java
  h2o-core/src/test/java/water/TestUtil.java
  h2o-py/docs/modeling.rst
  h2o-py/h2o/estimators/__init__.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/gam.py
  h2o-py/h2o/model/model_base.py
  h2o-py/h2o/sklearn/__init__.py
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_access_modelmetrics.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_gamX_saved.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_knotsKey.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_model_scoring.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_varimp_coeffs.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_compare_R.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_generic_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_regression_all_estimators.py
  h2o-r/H2O_Load.R
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/gam.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/testdir_algos/gam/runit_gam.R
  h2o-r/tests/testdir_algos/glm/runit_GLM_makeGLMModel.R
Labels: please review

#4461 PUBDEV-7351: Adding GAM algorithm to User Guide
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/algo-params/alpha.rst
  h2o-docs/src/product/data-science/algo-params/beta_constraints.rst
  h2o-docs/src/product/data-science/algo-params/beta_epsilon.rst
  h2o-docs/src/product/data-science/algo-params/compute_p_values.rst
  h2o-docs/src/product/data-science/algo-params/early_stopping.rst
  h2o-docs/src/product/data-science/algo-params/export_checkpoints_dir.rst
  h2o-docs/src/product/data-science/algo-params/family.rst
  h2o-docs/src/product/data-science/algo-params/fold_assignment.rst
  h2o-docs/src/product/data-science/algo-params/fold_column.rst
  h2o-docs/src/product/data-science/algo-params/gradient_epsilon.rst
  h2o-docs/src/product/data-science/algo-params/ignore_const_cols.rst
  h2o-docs/src/product/data-science/algo-params/ignored_columns.rst
  h2o-docs/src/product/data-science/algo-params/interaction_pairs.rst
  h2o-docs/src/product/data-science/algo-params/interactions.rst
  h2o-docs/src/product/data-science/algo-params/intercept.rst
  h2o-docs/src/product/data-science/algo-params/keep_cross_validation_fold_assignment.rst
  h2o-docs/src/product/data-science/algo-params/keep_cross_validation_models.rst
  h2o-docs/src/product/data-science/algo-params/keep_cross_validation_predictions.rst
  h2o-docs/src/product/data-science/algo-params/lambda.rst
  h2o-docs/src/product/data-science/algo-params/lambda_min_ratio.rst
  h2o-docs/src/product/data-science/algo-params/lambda_search.rst
  h2o-docs/src/product/data-science/algo-params/link.rst
  h2o-docs/src/product/data-science/algo-params/max_active_predictors.rst
  h2o-docs/src/product/data-science/algo-params/max_iterations.rst
  h2o-docs/src/product/data-science/algo-params/missing_values_handling.rst
  h2o-docs/src/product/data-science/algo-params/model_id.rst
  h2o-docs/src/product/data-science/algo-params/nfolds.rst
  h2o-docs/src/product/data-science/algo-params/nlambdas.rst
  h2o-docs/src/product/data-science/algo-params/non_negative.rst
  h2o-docs/src/product/data-science/algo-params/objective_epsilon.rst
  h2o-docs/src/product/data-science/algo-params/offset_column.rst
  h2o-docs/src/product/data-science/algo-params/plug_values.rst
  h2o-docs/src/product/data-science/algo-params/prior.rst
  h2o-docs/src/product/data-science/algo-params/remove_collinear_columns.rst
  h2o-docs/src/product/data-science/algo-params/score_each_iteration.rst
  h2o-docs/src/product/data-science/algo-params/seed.rst
  h2o-docs/src/product/data-science/algo-params/solver.rst
  h2o-docs/src/product/data-science/algo-params/standardize.rst
  h2o-docs/src/product/data-science/algo-params/theta.rst
  h2o-docs/src/product/data-science/algo-params/training_frame.rst
  h2o-docs/src/product/data-science/algo-params/tweedie_link_power.rst
  h2o-docs/src/product/data-science/algo-params/tweedie_variance_power.rst
  h2o-docs/src/product/data-science/algo-params/validation_frame.rst
  h2o-docs/src/product/data-science/algo-params/weights_column.rst
  h2o-docs/src/product/data-science/algo-params/x.rst
  h2o-docs/src/product/data-science/algo-params/y.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gam.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/data-science/k-means.rst
  h2o-docs/src/product/data-science/naive-bayes.rst
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/grid-search.rst
  h2o-docs/src/product/images/gam_cubic_regression_spines1.png
  h2o-docs/src/product/images/gam_piecewise_tent_basis.png
  h2o-docs/src/product/images/gam_simple_piecewise1.png
  h2o-docs/src/product/images/gam_simple_piecewise2.png
Labels: do not merge, docs

#4481 PUBDEV-7410: Add doc examples for upload_model and download_model
  h2o-docs/src/product/save-and-load-model.rst
Labels: docs

#4483 GAM: fix test_rest_api.py
  py/testdir_multi_jvm/test_rest_api.py
Labels: 4RELEASE, please review

#4484 Docs: Updated GAM parameters names
  h2o-docs/src/product/data-science/gam.rst
  h2o-docs/src/product/flow.rst
Labels: docs

#4482 PUBDEV-7425: Make GAM parameter names more descriptive
  h2o-algos/src/main/java/hex/gam/GAM.java
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GenerateGamMatrixOneColumn.java
  h2o-algos/src/main/java/hex/gam/MetricBuilderGAM.java
  h2o-algos/src/main/java/hex/schemas/GAMV3.java
  h2o-algos/src/test/java/hex/gam/GamTestPiping.java
  h2o-bindings/bin/custom/R/gen_gam.py
  h2o-py/h2o/estimators/gam.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_access_modelmetrics.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_gamX_saved.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_knotsKey.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_model_scoring.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_varimp_coeffs.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_compare_R.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_generic_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_regression_all_estimators.py
  h2o-r/h2o-package/R/gam.R
  h2o-r/tests/testdir_algos/gam/runit_gam.R
  py/testdir_multi_jvm/test_rest_api.py
Labels: 4RELEASE, please review

#4485 PUBDEV-7423: Adding print method for H2OSegmentModels in R
  h2o-r/h2o-package/R/segment.R
Labels: 4RELEASE, please review

#4450 PUBDEV-7202 add function to upload binary model
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/water/api/ModelsHandler.java
  h2o-core/src/main/java/water/api/RegisterV3Api.java
  h2o-py/h2o/__init__.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_misc/pyunit_download_model.py
  h2o-r/h2o-package/R/constants.R
  h2o-r/h2o-package/R/export.R
  h2o-r/h2o-package/R/import.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/tests/testdir_jira/runit_pubdev_7135_download.R
Labels: 4RELEASE

#4476 Release notes for 3.28.1.3 release
  Changes.md
Labels: 4RELEASE

#4478 PUBDEV-7089: Fix naming convention in gradle settings
  build.gradle
  h2o-algos/build.gradle
  h2o-assemblies/genmodel/build.gradle
  settings.gradle
Labels: 4RELEASE

#4495 PUBDEV-7427: Release notes for 3.30.0.1 release
  Changes.md
Labels: 4RELEASE

#4498 Add DRF to `predict_contributions` doc string for Python and R
  h2o-py/h2o/model/model_base.py
  h2o-r/h2o-package/R/models.R
Labels: R, please review, python

#4499 Add H2O AutoML logo to AutoML chapter
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/single_node_mode.rst
  h2o-docs/src/product/images/h2o-automl-logo.jpg
  h2o-docs/src/product/parameters.rst
Labels: docs

#4454 PUBDEV-7126: Make Date formatters ThreadLocal
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/ai/h2o/automl/events/EventLogEntry.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
  h2o-automl/src/test/java/ai/h2o/automl/events/EventLogTest.java
Labels: AutoML, please review

#4501 PUBDEV-7441 - Target encoder does not unlock output Frame
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
Labels: please review

#4504 PUBDEV-7439: train_segments not included in the R html documentation
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
Labels: docs

#4503 PUBDEV-7439: train_segments not included in the R html documentation
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
Labels: docs

#4507 PUBDEV-7447: Fix R example for GAM
  h2o-docs/src/product/data-science/gam.rst
Labels: docs

#4513 PUBDEV-7450: Use variables when showing H2O-3 versions in the docs
  h2o-docs/src/product/architecture.rst
  h2o-docs/src/product/conf.py
  h2o-docs/src/product/downloading.rst
  h2o-docs/src/product/faq/general.rst
  h2o-docs/src/product/faq/hadoop.rst
  h2o-docs/src/product/faq/java.rst
  h2o-docs/src/product/faq/python.rst
  h2o-docs/src/product/faq/r.rst
  h2o-docs/src/product/flow.rst
  h2o-docs/src/product/mojo-quickstart.rst
  h2o-docs/src/product/starting-h2o.rst
  h2o-docs/src/product/welcome.rst
  h2o-py/docs-requirements.txt
  scripts/jenkins/groovy/buildConfig.groovy
Labels: docs

#4505 PUBDEV-7442: Add new "Kubernetes Integration" topic to the welcome.rst
  h2o-docs/src/product/images/h2o-k8s-clustering.png
  h2o-docs/src/product/welcome.rst
Labels: docs

#4512 PUBDEV-7372: Create an Example section for each algo topic
  h2o-docs/src/product/data-science/aggregator.rst
  h2o-docs/src/product/data-science/algo-params/sample_size.rst
  h2o-docs/src/product/data-science/coxph.rst
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/drf.rst
  h2o-docs/src/product/data-science/gam.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/data-science/glrm.rst
  h2o-docs/src/product/data-science/if.rst
  h2o-docs/src/product/data-science/k-means.rst
  h2o-docs/src/product/data-science/naive-bayes.rst
  h2o-docs/src/product/data-science/pca.rst
  h2o-docs/src/product/data-science/stacked-ensembles.rst
  h2o-docs/src/product/data-science/svm.rst
  h2o-docs/src/product/data-science/word2vec.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#4506 PUBDEV-7443: New links for constrained k-means python demo
  h2o-docs/src/product/data-science/k-means.rst
Labels: docs

#4496 PUBDEV-6296: StackedEnsemble optimization: skip predictions for base models with coef 0 when using GLM metalearner
  h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleMojoWriter.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/naivebayes/NaiveBayesModel.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
  h2o-algos/src/test/java/hex/glm/GLMTest.java
  h2o-algos/src/test/java/hex/naivebayes/NaiveBayesTest.java
  h2o-algos/src/test/java/hex/tree/drf/DRFTest.java
  h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
  h2o-core/src/main/java/hex/Model.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/ensemble/StackedEnsembleMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/ensemble/StackedEnsembleMojoReader.java
  h2o-genmodel/src/test/java/hex/genmodel/algos/ensemble/StackedEnsembleBinomialWithoutUselessModelsMojoTest.java
  h2o-genmodel/src/test/resources/hex/genmodel/algos/ensemble/binomial_without_useless_models.zip
Labels: Mojo, WIP, algos, please review

#4518 The new extensions require an upgraded version of sphinx
  h2o-docs/src/product/conf.py
  h2o-py/docs-requirements.txt
  scripts/jenkins/groovy/buildConfig.groovy
Labels: docs

#4511 Add new topic in algorithms chapter about supported data types
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/supported-data-types.rst
Labels: docs

#4520 PUBDEV-7459: Link to slideshare in DRF chapter should point to https instead of http
  h2o-docs/src/product/data-science/drf.rst
Labels: docs

#4525 Use a version of sphinx and sphinx_substitution_extensions that support Py3.5
  h2o-py/docs-requirements.txt
  scripts/jenkins/groovy/buildConfig.groovy
Labels: docs

#4545 PUBDEV-7446 - Throw error when https is true on h2o.init() while starting local cluster
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_misc/pyunit_init_https.py
  h2o-r/h2o-package/R/connection.R
  h2o-r/tests/testdir_misc/runit_init_https.R
Labels: please review

#4439 PUBDEV-7376 - Kubernetes integration/clustering tests
  docker/Jenkinsfile-build-k8s-test-docker
  docker/jenkins-images/Dockerfile-k8s-test
  docker/jenkins-images/Dockerfile-k8s-test-h2o
  docker/jenkins-images/Dockerfile.dev
  h2o-k8s/tests/clustering/README.md
  h2o-k8s/tests/clustering/docker-init-script.sh
  h2o-k8s/tests/clustering/h2o-cluster-check.sh
  h2o-k8s/tests/clustering/h2o-service.yaml
  h2o-k8s/tests/clustering/readme/h2o-k8s-clustering.png
  h2o-k8s/tests/clustering/registries.yaml
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/buildConfig.groovy
  scripts/jenkins/groovy/defaultStage.groovy
  scripts/jenkins/groovy/defineTestStages.groovy
  scripts/jenkins/groovy/insideDocker.groovy
Labels: please review

#4544 PUBDEV-7462: Update docs of mojo visualisation for png format
  h2o-docs/src/product/images/mojo_visu_tree.png
  h2o-docs/src/product/mojo-quickstart.rst
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#4539 PUBDEV-7461: Add information about the h2o.get_leaderboard function to the AutoML User Guide page
  h2o-docs/src/product/automl.rst
Labels: docs

#4474 PUBDEV-7020: Updated Target Encoding data munging topic
  h2o-bindings/bin/custom/python/gen_targetencoder.py
  h2o-docs/src/product/data-munging.rst
  h2o-docs/src/product/data-munging/target-encoding.rst
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
  h2o-py/h2o/estimators/targetencoder.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_gbm_target_encoding.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_old_te_performance_docs_demo_titanic.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_target_encoding_model.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_te_performance_docs_demo_titanic.py
  h2o-r/tests/testdir_algos/targetencoder/runit_old_targetencoder_model_docs_demo.R
  h2o-r/tests/testdir_algos/targetencoder/runit_targetencoder_model_docs_demo.R
Labels: docs

#4548 PUBDEV-7460: Added pyunit test to double check on various modelmetrics.
  h2o-algos/src/main/java/hex/gam/GAM.java
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/AddGamColumns.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
  h2o-algos/src/main/java/hex/glm/ComputationState.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMTask.java
  h2o-algos/src/main/java/hex/glm/GLMUtils.java
  h2o-algos/src/main/java/hex/gram/Gram.java
  h2o-algos/src/test/java/hex/gam/GamTestPiping.java
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_model_scoring.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_compare_R.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7460_gam_accuracy_others.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7460_gam_hit_ratios_others_large.py
Labels: 4RELEASE

#4546 PUBDEV-7470 - Document and test upload/download and import/save MOJO in pairs.
  h2o-docs/src/product/save-and-load-model.rst
  h2o-py/tests/testdir_generic_model/pyunit_mojo_import.py
  h2o-r/h2o-package/R/export.R
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_algos/generic/runit_generic_mojo_convenience.R
  h2o-r/tests/testdir_misc/runit_saveMojo.R
Labels: 4RELEASE, please review

#4527 PUBDEV-7451: Add clarification: min_mem_size and max_mem_size = NULL/None in h2o.init() uses JVM default
  h2o-docs/src/product/starting-h2o.rst
  h2o-py/h2o/h2o.py
  h2o-r/h2o-package/R/connection.R
Labels: docs

#4547 Py Rapids expr: explicitly prevent creation of tmp frames for scalars
  h2o-py/h2o/expr.py
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_5180.py
Labels: 4RELEASE

#4553 PUBDEV-7020: Merging changes from PR 4474 into rel-zahradnik
  h2o-bindings/bin/custom/python/gen_targetencoder.py
  h2o-docs/src/product/data-munging.rst
  h2o-docs/src/product/data-munging/target-encoding.rst
  h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
  h2o-py/h2o/estimators/targetencoder.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_gbm_target_encoding.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_old_te_performance_docs_demo_titanic.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_target_encoding_model.py
  h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_te_performance_docs_demo_titanic.py
  h2o-r/tests/testdir_algos/targetencoder/runit_old_targetencoder_model_docs_demo.R
  h2o-r/tests/testdir_algos/targetencoder/runit_targetencoder_model_docs_demo.R
Labels: 4RELEASE, docs

#4549 PUBDEV-7486: Allow GBM to learn from column containing NAs and a single non-NA value
  h2o-algos/src/main/java/hex/tree/DHistogram.java
  h2o-algos/src/main/java/hex/tree/DTree.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
  h2o-algos/src/test/java/hex/tree/gbm/SharedTreeTest.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-core/src/main/java/water/fvec/Vec.java
  h2o-core/src/test/java/water/fvec/VecTest.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
Labels: 4RELEASE

#4552 PUBDEV-7353 Custom threshold for predictions
  h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/water/api/schemas3/ModelOutputSchemaV3.java
  h2o-core/src/main/java/water/rapids/Env.java
  h2o-core/src/main/java/water/rapids/ast/prims/models/AstModelResetThreshold.java
  h2o-core/src/main/java/water/rapids/vals/ValFrame.java
  h2o-core/src/main/resources/META-INF/services/water.rapids.ast.AstRoot
  h2o-py/h2o/utils/model_utils.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_7353_reset_threshold
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_algos/glm/runit_PUBDEV_7353_GLM_reset_threshold.R
Labels: 4RELEASE

#4554 PUBDEV-7469 - Expose leader node only on K8S
  h2o-core/src/main/java/water/H2ONode.java
  h2o-k8s/README.md
  h2o-k8s/build.gradle
  h2o-k8s/src/main/java/water/k8s/KubernetesEmbeddedConfigProvider.java
  h2o-k8s/src/main/java/water/k8s/api/KubernetesRestApi.java
  h2o-k8s/src/main/java/water/k8s/lookup/KubernetesDnsLookup.java
  h2o-k8s/src/main/java/water/k8s/probe/KubernetesLeaderNodeProbeHandler.java
  h2o-k8s/src/test/java/water/k8s/KubernetesEmbeddedConfigProviderTest.java
  h2o-k8s/src/test/java/water/k8s/api/KubernetesRestApiTest.java
  h2o-k8s/src/test/java/water/k8s/probe/KubernetesLeaderNodeProbeHandlerTest.java
  h2o-k8s/tests/clustering/h2o-service.yaml
Labels: 4RELEASE, please review

#4556 Remove markup language from R docs
  h2o-r/h2o-package/R/connection.R
Labels: please review

#4528 PUBDEV-7343: Doc improvements for Hive Import
  h2o-docs/src/product/getting-data-into-h2o.rst
Labels: docs

#4551 [PUBDEV-7484] test for token refresh working in supported scenarios
  h2o-hive/src/main/java/water/hive/DelegationTokenPrinter.java
  h2o-hive/src/main/java/water/hive/DelegationTokenRefresher.java
  h2o-hive/src/main/java/water/hive/GenerateHiveToken.java
  h2o-hive/src/main/java/water/hive/HiveTokenGenerator.java
  scripts/jenkins/Makefile.jenkins
  scripts/jenkins/groovy/hadoopCommands.groovy
  scripts/jenkins/groovy/hadoopStage.groovy
  scripts/jenkins/groovy/kerberosCommands.groovy
Labels: please review

#4560 Placeholders for namespaces in K8S readme
  h2o-k8s/README.md
Labels: please review
