Repository h2oai/h2o-3, pull requests merged in 2021-06, with the labels that each got.

#5520 PUBDEV-8181: Fix misuse of is in python
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/frame.py
Labels: python

#5510 PUBDEV-8146: Add params (with default value) to the signature of estimator's constructors.
  h2o-bindings/bin/bindings.py
  h2o-bindings/bin/custom/python/gen_deeplearning.py
  h2o-bindings/bin/custom/python/gen_drf.py
  h2o-bindings/bin/custom/python/gen_gam.py
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-bindings/bin/custom/python/gen_targetencoder.py
  h2o-bindings/bin/custom/python/gen_word2vec.py
  h2o-bindings/bin/gen_python.py
  h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostV3.java
  h2o-py/h2o/backend/connection.py
  h2o-py/h2o/estimators/aggregator.py
  h2o-py/h2o/estimators/coxph.py
  h2o-py/h2o/estimators/deeplearning.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/estimators/gam.py
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/generic.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/glrm.py
  h2o-py/h2o/estimators/isolation_forest.py
  h2o-py/h2o/estimators/kmeans.py
  h2o-py/h2o/estimators/naive_bayes.py
  h2o-py/h2o/estimators/pca.py
  h2o-py/h2o/estimators/psvm.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/rulefit.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/h2o/estimators/svd.py
  h2o-py/h2o/estimators/targetencoder.py
  h2o-py/h2o/estimators/word2vec.py
  h2o-py/h2o/estimators/xgboost.py
  h2o-py/h2o/frame.py
  h2o-py/h2o/grid/grid_search.py
  h2o-py/h2o/h2o.py
  h2o-py/h2o/model/metrics_base.py
  h2o-py/h2o/model/model_base.py
  h2o-py/h2o/sklearn/__init__.py
  h2o-py/h2o/transforms/decomposition.py
  h2o-py/h2o/tree/tree.py
  h2o-py/h2o/utils/config.py
  h2o-py/h2o/utils/metaclass.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_validate_frames.py
  h2o-py/tests/testdir_algos/targetencoder/pyunit_te_deprecated_params.py
  h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2ono_progress.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_4818.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_5112.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_params.py
  h2o-py/tests/testdir_utils/pyunit_deprecations.py
  h2o-py/tests/testdir_utils/pyunit_h2oconfig.py
  h2o-py/tests/testdir_utils/pyunit_logger.py
  h2o-py/tests/testdir_utils/pyunit_progressbar.py
  h2o-py/tests/testdir_utils/pyunit_typechecks.py
  h2o-r/h2o-package/R/rulefit.R
  h2o-r/h2o-package/R/targetencoder.R
  h2o-r/h2o-package/R/word2vec.R
  h2o-r/h2o-package/R/xgboost.R
Labels: please review

#5513 PUBDEV-8170: expose AutoML args as writeable properties until first call to train
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_params_attributes.py
Labels: please review

#5517 PUBDEV-8167: Screeplot fails for PCA in R and Python
  h2o-bindings/bin/custom/R/gen_pca.py
  h2o-py/h2o/model/dim_reduction.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_algos/pca/pyunit_pca_importance.py
  h2o-r/h2o-package/R/pca.R
  h2o-r/tests/testdir_algos/pca/runit_pca_importance.R
Labels: R, please review, python

#5532 PUBDEV-8175: improve AutoML behaviour when multiple instances are created in parallel
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/Leaderboard.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLConcurrencyTest.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepRegistryTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepsExecutorTest.java
  h2o-automl/src/test/java/ai/h2o/automl/preprocessing/TargetEncodingTest.java
  h2o-py/h2o/explanation/_explain.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_concurrent_runs.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_params_attributes.py
  h2o-r/h2o-package/R/explain.R
Labels: AutoML, please review

#5495 PUBDEV-7139: Variable importance for black-box models
  README.md
  h2o-algos/src/test/java/hex/varimp/PermutationVarImpTest.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/water/rapids/Env.java
  h2o-core/src/main/java/water/rapids/PermutationVarImp.java
  h2o-core/src/main/java/water/rapids/ast/prims/models/AstPermutationVarImp.java
  h2o-core/src/main/java/water/util/MRUtils.java
  h2o-core/src/main/java/water/util/VecUtils.java
  h2o-core/src/test/java/water/fvec/VecShuffleTest.java
  h2o-core/src/test/java/water/util/MRUtilsTest.java
  h2o-docs/src/product/data-science.rst
  h2o-docs/src/product/data-science/permutation-variable-importance.rst
  h2o-py/demos/permutation_var_imp.ipynb
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_jira/pyunit_pubdev_7139_permutation_var_imp.py
  h2o-r/H2O_Load.R
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package/R/permutation_varimp.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/testdir_jira/runit_pubdev_7139_permutation_varimp.R
Labels: R, please review, python

#5550 [NOCHECK] PUBDEV-8210: Fix failing scale_pca_rf test
  h2o-py/tests/testdir_pipeline/pyunit_scale_pca_rf.py
Labels: python
