Repository h2oai/h2o-3, pull requests merged in 2021-12, with the labels that each got.

#5872 PUBDEV-8361: Fix local build warnings for python documentation
  h2o-bindings/bin/custom/python/gen_anovaglm.py
  h2o-bindings/bin/custom/python/gen_targetencoder.py
  h2o-py/docs/metrics.rst
  h2o-py/docs/model_categories.rst
  h2o-py/h2o/automl/_base.py
  h2o-py/h2o/automl/_estimator.py
  h2o-py/h2o/automl/autoh2o.py
  h2o-py/h2o/estimators/anovaglm.py
  h2o-py/h2o/estimators/targetencoder.py
  h2o-py/h2o/explanation/_explain.py
  h2o-py/h2o/frame.py
  h2o-py/h2o/h2o.py
  h2o-py/h2o/model/metrics_base.py
  h2o-py/h2o/model/model_base.py
  h2o-py/h2o/model/segment_models.py
Labels: docs

#5925 PUBDEV-8443: Updated `y` description for maxrglm
  h2o-docs/src/product/data-science/maxrglm.rst
Labels: docs

#5926 PUBDEV-8432: Update MaxRGLM examples
  h2o-docs/src/product/data-science/maxrglm.rst
Labels: docs

#5936 PUBDEV-8451: Added change log to user guide
  h2o-docs/src/product/index.rst
Labels: docs

#5948 [PUBDEV-8452][FOLLOWUP] Rename lambda Field on RuleFitParameters to _lambda
  h2o-algos/src/main/java/hex/rulefit/RuleFit.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
Labels: please review

#5953 PUBDEV-8471: 3.34.0.5 Release Notes
  Changes.md
Labels: docs

#5973 PUBDEV-8478: 3.34.0.7 Release Notes [nocheck]
  Changes.md
Labels: docs

#5900 PUBDEV-8439: consolidate rules during extraction
  h2o-algos/src/main/java/hex/rulefit/Rule.java
  h2o-algos/src/main/java/hex/rulefit/RuleFit.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitUtils.java
  h2o-algos/src/test/java/hex/rulefit/RuleFitUtilsTest.java
Labels: 4RELEASE

#5933 PUBDEV-8222: Infogram R API + plot & updates to Python API + plot
  h2o-admissibleml/src/main/java/hex/Infogram/Infogram.java
  h2o-admissibleml/src/main/java/hex/Infogram/InfogramModel.java
  h2o-admissibleml/src/main/java/hex/Infogram/InfogramUtils.java
  h2o-admissibleml/src/main/java/hex/schemas/InfogramModelV3.java
  h2o-admissibleml/src/main/java/hex/schemas/InfogramV3.java
  h2o-admissibleml/src/test/java/hex/Infogram/InfogramCVValidTest.java
  h2o-admissibleml/src/test/java/hex/Infogram/InfogramPipingTest.java
  h2o-bindings/bin/custom/R/gen_infogram.py
  h2o-bindings/bin/custom/python/gen_infogram.py
  h2o-py/h2o/estimators/infogram.py
  h2o-py/h2o/plot/__init__.py
  h2o-py/h2o/plot/_matplotlib.py
  h2o-py/h2o/plot/_polycollection.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8075_core_infogram_iris.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8075_safe_infogram_personal_loan.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8258_core_infogram_breast_cancer_cv_fold_column.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8258_core_infogram_breast_cancer_cv_validFrame.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8258_core_infogram_breast_cancer_cv_validFrame_plot.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8258_safe_infogram_personal_loan_cv_fold_column.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8258_safe_infogram_personal_loan_cv_validFrame.py
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_8258_safe_infogram_personal_loan_cv_validFrame_plot.py
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/infogram.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/tests/testdir_algos/infogram/runit_PUBDEV_8075_core_infogram_erin_hdma_large.R
Labels: 4RELEASE

#5960 PUBDEV-8449: Admissible ML user guide page
  h2o-docs/src/product/admissible.rst
  h2o-docs/src/product/images/infogram_core_iris.png
  h2o-docs/src/product/images/infogram_fair_credit.png
  h2o-docs/src/product/images/infogram_fair_hmda.png
  h2o-docs/src/product/index.rst
Labels: docs, 4RELEASE

#5150 PUBDEV-7903: Add new R functions to the pkgdown R docs website
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
Labels: docs

#5225 PUBDEV-7542: Dynamic stacking strategy for H2OAutoML
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLSession.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingSteps.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-docs/src/product/automl.rst
  h2o-py/h2o/automl/_estimator.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_memory_cleanup.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_params_attributes.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_max_runtime_secs.R
Labels: AutoML

#5983 PUBDEV-8480: 3.36.0.1 Release Notes
  Changes.md
Labels: docs
