Repository h2oai/h2o-3, pull requests merged in 2021-08, with the labels that each got.

#5605 [DOCS] 3.32.1.5 Release notes draft [nocheck]
  Changes.md
Labels: docs

#5601 [PUBDEV-8257] 'cross_validation_metrics_summary' on MOJO Models Use Wrong Type for Columns
  h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
  h2o-core/src/main/java/hex/ModelBuilder.java
Labels: please review

#5614 PUBDEV-8096: Added note about memory use when using XGBoost/AutoML to user guide [nocheck]
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/xgboost.rst
Labels: docs

#5604 [DOCS] PUBDEV-8259 - Weight value of 0 warning
  h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
  h2o-docs/src/product/data-science/algo-params/weights_column.rst
  h2o-py/h2o/estimators/coxph.py
  h2o-py/h2o/estimators/deeplearning.py
  h2o-py/h2o/estimators/gam.py
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/rulefit.py
  h2o-py/h2o/estimators/stackedensemble.py
  h2o-py/h2o/estimators/xgboost.py
  h2o-r/h2o-package/R/coxph.R
  h2o-r/h2o-package/R/deeplearning.R
  h2o-r/h2o-package/R/gam.R
  h2o-r/h2o-package/R/gbm.R
  h2o-r/h2o-package/R/glm.R
  h2o-r/h2o-package/R/randomforest.R
  h2o-r/h2o-package/R/rulefit.R
  h2o-r/h2o-package/R/stackedensemble.R
  h2o-r/h2o-package/R/xgboost.R
Labels: docs

#5631 PUBDEV-8281: 3.32.1.6 Release Notes [nocheck]
  Changes.md
Labels: docs

#5456 PUBDEV-8123: Fix examples in H2O Explain documentation
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
  h2o-docs/src/product/explain.rst
Labels: docs

#5637 PUBDEV-8205: Mention that explain requires supervised models
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
  h2o-docs/src/product/explain.rst
  h2o-py/h2o/explanation/_explain.py
  h2o-r/h2o-package/R/explain.R
Labels: please review

#5488 PUBDEV-8088 Implement ANOVA Type III test for GLM
  h2o-algos/src/main/java/hex/anovaglm/ANOVAGLM.java
  h2o-algos/src/main/java/hex/anovaglm/ANOVAGLMModel.java
  h2o-algos/src/main/java/hex/anovaglm/ANOVAGLMUtils.java
  h2o-algos/src/main/java/hex/anovaglm/GenerateTransformColumns.java
  h2o-algos/src/main/java/hex/api/RegisterAlgos.java
  h2o-algos/src/main/java/hex/gam/GAM.java
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GAMModelUtils.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
  h2o-algos/src/main/java/hex/schemas/ANOVAGLMModelV3.java
  h2o-algos/src/main/java/hex/schemas/ANOVAGLMV3.java
  h2o-algos/src/main/resources/META-INF/services/water.api.Schema
  h2o-algos/src/test/java/hex/anovaglm/AnovaGLMBasicTest.java
  h2o-bindings/bin/custom/R/gen_anovaglm.py
  h2o-bindings/bin/custom/python/gen_anovaglm.py
  h2o-bindings/bin/gen_R.py
  h2o-bindings/bin/gen_python.py
  h2o-py/docs/modeling.rst
  h2o-py/h2o/estimators/__init__.py
  h2o-py/h2o/estimators/anovaglm.py
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_algos/anovaglm/pyunit_PUBDEV_8088_NA_handling.py
  h2o-py/tests/testdir_algos/anovaglm/pyunit_PUBDEV_8088_transformFrame.py
  h2o-py/tests/testdir_algos/glm/pyunit_generate_synthetic_GLM_data.py
  h2o-py/tests_rest_smoke/testdir_multi_jvm/test_rest_api.py
  h2o-r/H2O_Load.R
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package.template
  h2o-r/h2o-package/R/anovaglm.R
  h2o-r/h2o-package/R/explain.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/R/segment.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/testdir_algos/anovaglm/runit_PUBDEV_8088_frame_transform.R
  h2o-r/tests/testdir_algos/anovaglm/runit_PUBDEV_8088_missing_value_handling_NA.R
  h2o-r/tests/testdir_algos/anovaglm/runit_PUBDEV_8088_prostate_fail.R
Labels: please review, please high-level review

#5653 Fix failing test learning curve plot [nocheck]
  h2o-r/h2o-package/R/explain.R
Labels: R

#5656 PUBDEV-8304: Update ignored_columns example [nocheck]
  h2o-docs/src/product/data-science/algo-params/ignored_columns.rst
Labels: docs
