Repository h2oai/h2o-3, pull requests merged in 2021-11, with the labels that each got.

#5819 PUBDEV-8370: Fix documentation: MSE -> MAE in Performance and Prediction
  h2o-docs/src/product/performance-and-prediction.rst
Labels: please review, docs

#5764 PUBDEV-8283: Tune scale_pos_weight param for XGBoost in AutoML
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
Labels: please review, AutoML

#5765 PUBDEV-8133: rulefit multinomial fix
  h2o-algos/src/main/java/hex/rulefit/Rule.java
  h2o-algos/src/main/java/hex/rulefit/RuleEnsemble.java
  h2o-algos/src/main/java/hex/rulefit/RuleFit.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
  h2o-algos/src/main/java/hex/rulefit/RuleFitMojoWriter.java
  h2o-algos/src/main/java/hex/schemas/RuleFitV3.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
  h2o-algos/src/test/java/hex/rulefit/RuleFitUtilsTest.java
  h2o-core/src/main/java/water/rapids/Env.java
  h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstAppendLevels.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/MojoRuleEnsemble.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/RuleFitMojoModel.java
  h2o-py/h2o/estimators/rulefit.py
  h2o-py/h2o/frame.py
  h2o-py/tests/testdir_algos/rulefit/pyunit_cancer_rulefit.py
  h2o-py/tests/testdir_algos/rulefit/pyunit_credit_rulefit.py
  h2o-py/tests/testdir_algos/rulefit/pyunit_ecology_rulefit.py
  h2o-py/tests/testdir_algos/rulefit/pyunit_football_rulefit.py
  h2o-py/tests/testdir_algos/rulefit/pyunit_iris_rulefit.py
  h2o-py/tests/testdir_misc/pyunit_append_levels.py
  h2o-r/h2o-package/R/rulefit.R
Labels: please review

#5851 PUBDEV-8392: Supported MOJO list for algorithms
  h2o-docs/src/product/images/checkmark.png
  h2o-docs/src/product/images/xmark.png
  h2o-docs/src/product/save-and-load-model.rst
Labels: docs

#5821 PUBDEV-8163: fix GAM CV bug
  h2o-algos/src/main/java/hex/gam/GAM.java
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GAMModelUtils.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
  h2o-algos/src/test/java/hex/gam/GamCVTest.java
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7366_gam_cv_all_params_binomial.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8136_check_gamX_saved_serialization.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8163_gam_cv_all_params_binomial_serialization.py
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8163_gam_cv_fold_column.py
Labels: please review

#5779 PUBDEV-8344: disable sklearn integration for ANOVA GLM and MaxR2 GLM
  h2o-docs/src/product/data-science/anova_glm.rst
  h2o-py/h2o/sklearn/__init__.py
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_generic_all_estimators.py
  h2o-py/tests/testdir_sklearn/pyunit_sklearn_regression_all_estimators.py
Labels: python

#5036 rulefit demo [nocheck]
  h2o-docs/src/product/flow/packs/examples/Rulefit_Example.flow
  h2o-py/demos/rulefit_demo.ipynb
Labels: 4RELEASE

#5879 [nocheck] Add python 3.7 to prerequisites
  h2o-dist/index.html
Labels: please review, python, docs

#5827 [PUBDEV-8377] Increase Jetty Idle Timeout to 5 minutes and Make It Configurable
  h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8Helper.java
  h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Helper.java
Labels: please review

#5845 PUBDEV-8381: Add Gains/Lift table to Performance & Prediction
  h2o-docs/src/product/images/gainslift_plot.png
  h2o-docs/src/product/images/gainslift_table.png
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#5889 PUBDEV-8407: fix gam test failure
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8407_gam_weight.py
Labels: 4RELEASE

#5875 PUBDEV-8406: 3.34.0.4 Release Notes
  Changes.md
Labels: docs

#5897 PUBDEV-8424: Add R/Python examples on how to get to reproducibility information
  h2o-docs/src/product/data-science/gbm-faq/reproducibility.rst
Labels: docs
