Repository h2oai/h2o-3, pull requests merged in 2022-08, with the labels that each got.

#6274 PUBDEV-8791: 3.36.1.4 Release Notes
  Changes.md
Labels: docs

#6267 PUBDEV-8768 - fix testUniqueRowsWithCounts
  h2o-algos/src/test/java/hex/tree/FriedmanPopescusHTest.java
Labels: please review

#6285 [nocheck] Fix explain in R 3.3
  h2o-r/h2o-package/R/explain.R
Labels: please review, R

#6293 PUBDEV-8806: Added new commands to ModelSelection
  h2o-docs/src/product/data-science/model_selection.rst
Labels: docs
