Repository h2oai/h2o-3, pull requests merged in 2022-04, with the labels that each got.

#6102 PUBDEV-8620: Fix cv_computeAndSetOptimalParameters
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-py/tests/testdir_algos/glm/pyunit_glm_cv_compute_and_set_optimal_parameters.py
Labels: please review

#6050 PUBDEV-8528: Change default leaderboard sorting in regression to RMSE
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/Leaderboard.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelingStepTest.java
  h2o-automl/src/test/java/ai/h2o/automl/leaderboard/LeaderboardTest.java
  h2o-py/tests/testdir_algos/automl/leaderboard/pyunit_automl_leaderboard_regression.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_regression.py
  h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
  h2o-r/tests/testdir_algos/automl/runit_automl_sort_metric.R
Labels: please review, AutoML

#5952 PUBDEV-7858: Expose distribution parameter in AutoML
  h2o-algos/src/main/java/hex/anovaglm/ANOVAGLMModel.java
  h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
  h2o-algos/src/main/java/hex/ensemble/Metalearners.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/rulefit/RuleFit.java
  h2o-algos/src/main/java/hex/tree/drf/DRF.java
  h2o-algos/src/main/java/hex/tree/drf/DRFModel.java
  h2o-algos/src/main/java/hex/util/DistributionUtils.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/GLMStepsProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-docs/src/product/data-science/algo-params/distribution.rst
  h2o-extensions/xgboost/src/main/java/hex/ensemble/XGBoostMetalearnerProvider.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-py/h2o/automl/_estimator.py
  h2o-py/tests/testdir_algos/automl/pyunit_automl_distributions.py
  h2o-r/h2o-package/R/automl.R
  h2o-r/tests/testdir_algos/automl/runit_automl_distributions.R
  h2o-web/bower.json
Labels: please review

#6141 PUBDEV-8643: Add more detailed exception when we suspect the error is caused by RCurl
  h2o-r/h2o-package/R/communication.R
Labels: please review, R

#6139 PUBDEV-8653: Residual calculation is flipped in the Residual Analysis Plot
  h2o-py/h2o/explanation/_explain.py
  h2o-r/h2o-package/R/explain.R
Labels: please review, python, R

#6084 PUBDEV-8595: Added information on date columns
  h2o-docs/src/product/data-munging/change-column-type.rst
Labels: docs, 4RELEASE

#6144 PUBDEV-8631: Shifting docs page info to the user guide
  h2o-docs/src/product/additional-resources.rst
  h2o-docs/src/product/index.rst
Labels: docs, 4RELEASE

#6142 PUBDEV-8591: Added information on HDFS configuration
  h2o-docs/src/product/faq/hadoop.rst
  h2o-docs/src/product/welcome.rst
Labels: docs, 4RELEASE

#6067 PUBDEV-8576: ModelBuilder private parameter allowing AutoML to enforce time budget on the final model after CV
  h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
  h2o-algos/src/main/java/hex/ensemble/Metalearner.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelBuilder.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
Labels: WIP

#6076 PUBDEV-8590: Fix typos in admissible.rst
  h2o-docs/src/product/admissible.rst
Labels: 4RELEASE

#5674 PUBDEV-8014: Add num_of_features argument to explain's varimp
  h2o-py/h2o/explanation/_explain.py
  h2o-py/tests/testdir_misc/pyunit_explain.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/explain.R
  h2o-r/tests/testdir_misc/runit_explain.R
Labels: python, R

#6151 ICE fixes [nocheck]
  h2o-r/h2o-package/R/explain.R
Labels: 4RELEASE

#6154 PUBDEV-8644: Fix bad URLs in R package for CRAN check
  h2o-r/h2o-package.template
  h2o-r/h2o-package/R/frame.R
Labels: 4RELEASE

#5907 PUBDEV-8388: Add a plot function for gains/lift in R and Python
  h2o-docs/src/product/performance-and-prediction.rst
  h2o-py/h2o/model/binomial.py
  h2o-py/h2o/model/metrics_base.py
  h2o-py/tests/testdir_misc/pyunit_plot_gains_lift.py
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/tests/testdir_misc/runit_plot_gains_lift.R
Labels: python, R, please high-level review

#6133 PUBDEV-8639 improve Uplift DRF documentation
  h2o-docs/src/product/data-science/upliftdrf.rst
Labels: docs, 4RELEASE

#6096 PUBDEV-8585: verify GLM binomial IRLSM implementation and p-value calculation
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/modelselection/ModelSelectionModel.java
  h2o-algos/src/main/java/hex/schemas/GLMV3.java
  h2o-algos/src/main/java/hex/schemas/ModelSelectionV3.java
  h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/estimators/model_selection.py
  h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8428_modelselection_backward_binomial_large.py
  h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8585_glm_backward_compare_large.py
  h2o-r/h2o-package/R/glm.R
  h2o-r/h2o-package/R/modelselection.R
Labels: 4RELEASE

#6161 UpliftDRF Fix qini coefficient to qini value [nocheck]
  h2o-algos/src/main/java/hex/tree/uplift/UpliftDRF.java
  h2o-docs/src/product/data-science/upliftdrf.rst
  h2o-docs/src/product/images/uplift_scoring_history.png
  h2o-py/demos/uplift_random_forest_compare_causalml.ipynb
Labels: 4RELEASE

#6163 PUBDEV-8665: Added question section to Additional Resources page
  h2o-docs/src/product/additional-resources.rst
Labels: docs, 4RELEASE

#6164 PUBDEV-8654: Added documentation on monotone splines for GAM
  h2o-algos/src/main/java/hex/schemas/GAMV3.java
  h2o-docs/src/product/data-science/gam.rst
  h2o-py/h2o/estimators/gam.py
  h2o-r/h2o-package/R/gam.R
Labels: docs, 4RELEASE

#6162 PUBDEV-8657: 3.36.1.1 Release Notes
  Changes.md
Labels: docs, 4RELEASE

#5107 PUBDEV-7913: Fix autoexplain's PDP date handling
  h2o-py/h2o/explanation/_explain.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_misc/pyunit_explain.py
  h2o-r/h2o-package/R/explain.R
  h2o-r/h2o-package/R/frame.R
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_javapredict/runit_mojo_predict.R
  h2o-r/tests/testdir_misc/runit_explain.R
  h2o-r/tests/testdir_misc/runit_string_manipulations.R
  h2o-r/tests/testdir_munging/runit_isax.R
  h2o-r/tests/testdir_munging/strop/runit_lstrip.R
  h2o-r/tests/testdir_munging/strop/runit_rstrip.R
  h2o-r/tests/testdir_parser/runit_PUBDEV_8239.R
Labels: please review, python, R

#6180 PUBDEV-8682: Fix ambiguity check in consolidate varimp
  h2o-r/h2o-package/R/explain.R
Labels: please review, R

#6169 PUBDEV-8667: fix test failure testStandardErrorBinomial
  h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
Labels: do not merge
