Repository h2oai/h2o-3, pull requests merged in 2022-07, with the labels that each got.

#6239 PUBDEV-8751: Added `transform_frame` to GLRM
  h2o-docs/src/product/data-science/glrm.rst
Labels: docs

#6225 PUBDEV-5280: Add h2o.create_leaderboard function to score & compare a set of models
  h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelSelectionStrategies.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsExecutor.java
  h2o-automl/src/main/java/ai/h2o/automl/events/EventLog.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/ModelGroup.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/ModelProvider.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/ModelSize.java
  h2o-automl/src/main/java/ai/h2o/automl/leaderboard/ModelStep.java
  h2o-automl/src/main/java/ai/h2o/automl/modeling/CompletionStepsProvider.java
  h2o-automl/src/main/java/water/automl/api/AutoMLHandler.java
  h2o-automl/src/main/java/water/automl/api/LeaderboardsHandler.java
  h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
  h2o-automl/src/main/java/water/automl/api/schemas3/LeaderboardV99.java
  h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
  h2o-automl/src/test/java/ai/h2o/automl/ModelSelectionStrategiesTest.java
  h2o-automl/src/test/java/ai/h2o/automl/leaderboard/LeaderboardTest.java
  h2o-core/src/main/java/hex/leaderboard/AlgoName.java
  h2o-core/src/main/java/hex/leaderboard/Leaderboard.java
  h2o-core/src/main/java/hex/leaderboard/LeaderboardCell.java
  h2o-core/src/main/java/hex/leaderboard/LeaderboardColumn.java
  h2o-core/src/main/java/hex/leaderboard/LeaderboardExtensionsProvider.java
  h2o-core/src/main/java/hex/leaderboard/MetricScore.java
  h2o-core/src/main/java/hex/leaderboard/ModelId.java
  h2o-core/src/main/java/hex/leaderboard/ScoringTimePerRow.java
  h2o-core/src/main/java/hex/leaderboard/TrainingTime.java
  h2o-core/src/main/java/water/rapids/Env.java
  h2o-core/src/main/java/water/rapids/ast/prims/models/AstMakeLeaderboard.java
  h2o-core/src/main/java/water/util/DKVUtils.java
  h2o-core/src/main/java/water/util/TwoDimTable.java
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/performance-and-prediction.rst
  h2o-py/h2o/__init__.py
  h2o-py/h2o/explanation/_explain.py
  h2o-py/h2o/scoring.py
  h2o-py/tests/testdir_misc/pyunit_make_leaderboard.py
  h2o-r/h2o-package/R/explain.R
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_misc/runit_make_leaderboard.R
Labels: python, core, R, Rapids, please high-level review, AutoML

#6229 PUBDEV-8744: Removed mention of R2 returning NaN for non-linear models
  h2o-py/h2o/model/model_base.py
  h2o-r/h2o-package/R/models.R
Labels: docs

#6240 PUBDEV-8754: 3.36.1.3 Release Notes
  Changes.md
Labels: docs

#6245 PUBDEV-8754: 3.36.1.3 Release Notes
  Changes.md
Labels: docs

#6176 PUBDEV-8589: Pareto Front in explain
  h2o-bindings/bin/custom/R/gen_infogram.py
  h2o-docs/src/product/explain.rst
  h2o-docs/src/product/images/explain_pareto_front.png
  h2o-py/h2o/automl/_base.py
  h2o-py/h2o/explanation/__init__.py
  h2o-py/h2o/explanation/_explain.py
  h2o-py/h2o/grid/grid_search.py
  h2o-py/tests/testdir_misc/pyunit_explain.py
  h2o-r/h2o-package/R/explain.R
  h2o-r/h2o-package/R/infogram.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/tests/testdir_misc/runit_explain.R
Labels: python, R
