Repository h2oai/h2o-3, pull requests merged in 2022-09, with the labels that each got.

#6288 [PUBDEV-8726] Change error message that GLM does not support contributions
  h2o-bindings/bin/custom/python/gen_drf.py
  h2o-bindings/bin/custom/python/gen_gbm.py
  h2o-bindings/bin/custom/python/gen_generic.py
  h2o-bindings/bin/custom/python/gen_xgboost.py
  h2o-core/src/main/java/water/api/ModelMetricsHandler.java
  h2o-py/h2o/estimators/gbm.py
  h2o-py/h2o/estimators/generic.py
  h2o-py/h2o/estimators/random_forest.py
  h2o-py/h2o/estimators/xgboost.py
  h2o-py/h2o/model/extensions/__init__.py
  h2o-py/h2o/model/extensions/contributions.py
  h2o-py/h2o/model/model_base.py
  h2o-r/h2o-package/R/explain.R
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_misc/runit_explain.R
  h2o-web/package.json
Labels: please review

#6297 PUBDEV-8811: Fix leaderboard sorting
  h2o-core/src/main/java/hex/leaderboard/Leaderboard.java
  h2o-core/src/main/java/water/rapids/ast/prims/models/AstMakeLeaderboard.java
Labels: please review

#6295 PUBDEV-8572: added Java to calculate variable inflation factors
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/glm/GLMUtils.java
  h2o-algos/src/main/java/hex/modelselection/ModelSelectionUtils.java
  h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
  h2o-algos/src/main/java/hex/schemas/GLMV3.java
  h2o-algos/src/test/java/hex/glm/GLMModelTest.java
  h2o-algos/src/test/java/hex/glm/GLMTestVariableInflationFactors.java
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8572_glm_VIF.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8572_glm_VIF_CV.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8572_glm_VIF_enumPreds.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8572_glm_VIF_p_values.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8572_glm_multinomial_VIF.py
  h2o-r/h2o-package/R/glm.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/tests/testdir_algos/glm/runit_PUBDEV_8572_glm_VIF.R
Labels: 4RELEASE

#6311 PUBDEV-8825: Already trained model can be calibrated manually
  h2o-algos/src/main/java/hex/tree/CalibrationHelper.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/main/java/water/rapids/prims/AstSetCalibrationModel.java
  h2o-algos/src/main/resources/META-INF/services/water.rapids.ast.AstPrimitive
  h2o-algos/src/test/java/hex/tree/SharedTreeTest.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
  h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostOutput.java
  h2o-py/build.gradle
  h2o-py/h2o/model/extensions/supervised_trees.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_misc/pyunit_model_calibrate.py
  h2o-test-support/src/main/java/water/TestFrameCatalog.java
Labels: 4RELEASE

#6207 PUBDEV-8632: Implement major release blogs into User Guide
  h2o-docs/src/product/blog-releases.rst
  h2o-docs/src/product/images/blog/rel-zorn.png
  h2o-docs/src/product/images/blog/uplift-blog.png
  h2o-docs/src/product/index.rst
Labels: docs

#6312 PUBDEV-8817: Added note to explain confusion matrix calculation
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs, 4RELEASE

#6300 [nocheck] fix r cmd check as cran
  h2o-bindings/bin/custom/R/gen_deeplearning.py
  h2o-r/h2o-package/R/deeplearning.R
  scripts/jenkins/Makefile.jenkins
  scripts/validate_r_cmd_check_output.R
  scripts/validate_r_cmd_check_output.py
Labels: please review

#6314 PUBDEV-8829: Adding VIF to GLM docs
  h2o-docs/src/product/data-science/glm.rst
Labels: docs, 4RELEASE

#6310 PUBDEV-8470 In training checkpoints documentation
  h2o-docs/src/product/data-science/algo-params/in_training_checkpoints_dir.rst
  h2o-docs/src/product/data-science/algo-params/in_training_checkpoints_tree_interval.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/parameters.rst
Labels: 4RELEASE

#6316 PUBDEV-8827: Added documentation for GLM Tweedie dispersion parameter estimation
  h2o-docs/src/product/data-science/glm.rst
  h2o-docs/src/product/images/dispersion_param_fig1.png
  h2o-docs/src/product/images/dispersion_param_fig2.png
Labels: docs, 4RELEASE

#6269 PUBDEV-8685 implement tweedie dispersion master estimation using maximum likelihood
  h2o-algos/src/main/java/hex/glm/DispersionTask.java
  h2o-algos/src/main/java/hex/glm/DispersionUtils.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/glm/GLMTask.java
  h2o-algos/src/main/java/hex/glm/TweedieMLDispersionOnly.java
  h2o-algos/src/main/java/hex/modelselection/ModelSelectionModel.java
  h2o-algos/src/main/java/hex/schemas/GLMV3.java
  h2o-algos/src/test/java/hex/glm/GLMTweedieDispersionOnlyTest.java
  h2o-py/h2o/estimators/glm.py
  h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8685_tweedie_dispersion_factor_exceed2.py
  h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8685_tweedie_dispersion_only_less2.py
  h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8774_fix_dispersion.py
  h2o-r/h2o-package/R/glm.R
  h2o-r/tests/testdir_algos/glm/runit_pubdev_8685_tweedie_dispersion_ml.R
  h2o-test-support/src/main/java/water/TestUtil.java
Labels: 4RELEASE

#6281 PUBDEV-8315: restoring the full model rendering by default
  h2o-py/h2o/model/model_base.py
Labels: 4RELEASE

#6320 PUBDEV-8839: 3.36.1.5 Release Notes
  Changes.md
Labels: docs

#6326 PUBDEV-8842: 3.38.0.1 Release Notes
  Changes.md
Labels: docs

#6331 PUBDEV-8846: Do not warn about job not having a proper model type when no model was trained
  h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
Labels: please review

#6339 PUBDEV-8848: fixed/updated broken links
  h2o-docs/src/product/data-science/k-means.rst
  h2o-docs/src/product/data-science/xgboost.rst
  h2o-docs/src/product/welcome.rst
Labels: docs

#6343 PUBDEV-8854: Added VIF example to user guide and python docs
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-docs/src/product/data-science/glm.rst
  h2o-py/h2o/estimators/glm.py
Labels: docs
