Repository h2oai/h2o-3, pull requests merged in 2022-03, with the labels that each got.

#6088 PUBDEV-8568: Use curl package in R client but keep RCurl as fallback (part 3)
  h2o-r/h2o-package/R/communication.R
Labels: R

#6104 PUBDEV-8622: Make GLM fail when beta constraints and multinomial or ordinal family
  h2o-algos/src/main/java/hex/ensemble/Metalearners.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
  h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
  h2o-docs/src/product/data-science/algo-params/beta_constraints.rst
  h2o-docs/src/product/data-science/algo-params/non_negative.rst
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8079_rollup_stats.py
Labels: please review

#6085 PUBDEV-8505 Document make_metrics method
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#5871 PUBDEV-5258: Add cross_validation_metrics_summary to SE
  h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
  h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_metalearner.py
  h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_metalearner.R
Labels: please review, python, R

#6121 PUBDEV-8633: Check curl version and add documentation
  h2o-docs/src/product/faq/r.rst
  h2o-r/h2o-package/R/communication.R
  h2o-r/tests/runitUtils/utilsR.R
Labels: R

#6120 PUBDEV-8634: Fix R check length == 1 for logic operations
  h2o-r/h2o-package/R/config.R
  h2o-r/h2o-package/R/frame.R
  h2o-r/h2o-package/R/grid.R
  h2o-r/h2o-package/R/import.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/runitUtils/utilsR.R
  h2o-r/tests/testdir_munging/binop/runit_binop2_divCol.R
Labels: please review, R

#6126 PUBDEV-8642: 3.36.0.4 Release Notes
  Changes.md
Labels: docs
