Repository h2oai/h2o-3, pull requests merged in 2022-11, with the labels that each got.

#6405 PUBDEV-8897: Fixed typo for `build_glm_model` in ModelSelection
  h2o-docs/src/product/data-science/model_selection.rst
Labels: docs

#6370 PUBDEV-8051: Add params slot to R
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/data-science/algo-params/checkpoint.rst
  h2o-docs/src/product/tutorials/datascience/DataScienceH2O-Dev.md
  h2o-docs/src/product/tutorials/gbm/gbmTuning.Rmd
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/kvstore.R
  h2o-r/h2o-package/R/models.R
Labels: please review, R

#6371 PUBDEV-8876: extremely slow Py estimator validation when training model with very wide dataset
  h2o-py/h2o/estimators/estimator_base.py
  h2o-py/h2o/utils/shared_utils.py
  h2o-py/tests/testdir_algos/common/pyunit_train_preparation_perf.py
  h2o-py/tests/testdir_utils/pyunit_shared_utils.py
Labels: python, 4RELEASE

#6419 PUBDEV-8908: Make sure we don't leave open file descriptors from H2OConnection
  h2o-py/h2o/backend/connection.py
  h2o-py/h2o/utils/shared_utils.py
Labels: python

#6391 PUBDEV-8882: Change exceptions in SE check to warnings
  h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
Labels: please review

#6404 PUBDEV-8892: Updated bibliography in FAQ and version in conf.py file
  h2o-docs/src/product/conf.py
  h2o-docs/src/product/faq/general.rst
Labels: docs

#6418 PUBDEV-8904: Updated booklet links and locations GBM/GLM/DL
  h2o-docs/src/product/data-science/deep-learning.rst
  h2o-docs/src/product/data-science/gbm.rst
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#6424 PUBDEV-8910: updated logo, favicon, background, and front version number
  h2o-docs-theme/sphinx_rtd_theme/static/css/theme.css
  h2o-docs/src/front/assets/images/favicon-16x16.png
  h2o-docs/src/front/assets/images/favicon-32x32.png
  h2o-docs/src/front/assets/images/favicon.ico
  h2o-docs/src/front/index.html
  h2o-docs/src/product/images/favicon.ico
  h2o-docs/src/product/images/logo.png
  h2o-docs/src/product/sphinx_rtd_theme/static/css/theme.css
Labels: docs

#6415 PUBDEV-8903: Fix incorrect current value indicator
  h2o-py/h2o/explanation/_explain.py
  h2o-py/tests/testdir_misc/pyunit_explain.py
  h2o-r/h2o-package/R/explain.R
  scripts/jenkins/groovy/buildConfig.groovy
Labels: please review, python, R

#6426 PUBDEV-8912: p-val/z-val work with regularization now
  h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
  h2o-docs/src/product/data-science/algo-params/compute_p_values.rst
  h2o-docs/src/product/data-science/gam.rst
  h2o-docs/src/product/data-science/glm.rst
Labels: docs

#6425 PUBDEV-8911: Added M-spline implementation to docs
  h2o-docs/src/product/data-science/gam.rst
Labels: docs

#6363 PUBDEV-8843: implementing p-value calculation with regularisation
  h2o-algos/src/main/java/hex/glm/ComputationState.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/schemas/GLMRegularizationPathV3.java
  h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
  h2o-algos/src/test/java/hex/glm/GLMBasicTestRegression.java
  h2o-algos/src/test/java/hex/glm/GLMPValuesWithRegularizationTest.java
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-py/h2o/estimators/glm.py
  h2o-py/tests/testdir_algos/glm/pyunit_pvalues_with_regularization_GLM.py
  h2o-r/tests/testdir_algos/glm/runit_PUBDEV_8843_glm_lambda_not_null_regPath.R
Labels: 4RELEASE

#6427 PUBDEV-8914: 3.38.0.3 Release Notes
  Changes.md
Labels: docs
