Repository h2oai/h2o-3, pull requests merged in 2023-05, with the labels that each got.

#6676 PUBDEV-8899: Tweedie Variance Power Maximum Likelihood estimation
  h2o-algos/src/main/java/hex/gam/GAMModel.java
  h2o-algos/src/main/java/hex/glm/ComputationState.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/glm/GLMTask.java
  h2o-algos/src/main/java/hex/glm/TweedieVariancePowerMLEstimator.java
  h2o-algos/src/main/java/hex/modelselection/ModelSelectionUtils.java
  h2o-algos/src/test/java/hex/glm/GLMTweediePowerEstimationTest.java
  h2o-py/tests/testdir_algos/glm/pyunit_tweedie_variance_power_ml_estimation.py
  h2o-py/tests/testdir_algos/glm/pyunit_tweedie_variance_power_ml_estimation_large.py
  scripts/jenkins/groovy/defineTestStages.groovy
Labels: please review, algos

#15475 Adding H2O AutoML wave ref to user guide
  h2o-docs/src/product/automl.rst
  h2o-docs/src/product/images/h2o-automl-wave-1.png
  h2o-docs/src/product/images/h2o-automl-wave-2.png
  h2o-docs/src/product/images/h2o-automl-wave-3.png
  h2o-docs/src/product/images/h2o-automl-wave-4.png
Labels: docs

#6842 PUBDEV-8900: Estimate tweedie dispersion parameter, variance power using maximum likelihood.
  h2o-algos/src/main/java/hex/glm/DispersionUtils.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/glm/TweedieEstimator.java
  h2o-algos/src/test/java/hex/glm/GLMTweediePowerEstimationTest.java
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/testdir_algos/glm/pyunit_tweedie_p_and_phi_ml_estimation.py
  h2o-py/tests/testdir_algos/glm/pyunit_tweedie_p_and_phi_ml_estimation_large.py
  h2o-py/tests/testdir_algos/glm/pyunit_tweedie_variance_power_ml_estimation_large.py
  scripts/jenkins/groovy/buildConfig.groovy
Labels: please review

#15532 PUBDEV-9096: Change R package maintainer
  h2o-r/h2o-DESCRIPTION.template
  h2o-r/h2o-package.template
  h2o-r/h2o-package/R/explain.R
  h2o-r/h2o-package/R/models.R
Labels: please review

#15539 PUBDEV-9097: Fix infogram CV with weights
  h2o-admissibleml/src/main/java/hex/Infogram/EstimateCMI.java
  h2o-admissibleml/src/main/java/hex/Infogram/Infogram.java
  h2o-admissibleml/src/test/java/hex/Infogram/InfogramCVValidTest.java
  h2o-py/tests/testdir_algos/infogram/pyunit_PUBDEV_9097_infogram_cv_with_weights.py
Labels: please review
