Repository h2oai/h2o-3, pull requests merged in 2023-11, with the labels that each got.

#15838 GH-15832 Fix UpliftDRF MOJO API, add docs, tests
  h2o-algos/src/main/java/hex/generic/Generic.java
  h2o-algos/src/main/java/hex/generic/GenericModel.java
  h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
  h2o-core/src/main/java/hex/AUUC.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelMetrics.java
  h2o-core/src/main/java/hex/ModelMetricsBinomialUpliftGeneric.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialUpliftGenericV3.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialUpliftV3.java
  h2o-core/src/main/resources/META-INF/services/water.api.Schema
  h2o-docs/src/product/data-science/upliftdrf.rst
  h2o-genmodel/src/main/java/hex/genmodel/MojoPipelineWriter.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelAttributes.java
  h2o-genmodel/src/main/java/hex/genmodel/attributes/metrics/MojoModelMetricsBinomialUplift.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptor.java
  h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
  h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_mojo.py
  h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_upliftdrf.py
  h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_upliftdrf.R
  h2o-r/tests/testdir_algos/uplift/runit_uplift_compare_h2o_vs_upliftRF.R
  h2o-r/tests/testdir_algos/uplift/runit_uplift_rf_mojo.R
Labels: bug

#15837 GH-15761 - Fix relevel_by_frequency bug
  h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstRelevelByFreq.java
  h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstRelevelByFreqTest.java
  h2o-py/tests/testdir_misc/pyunit_relevel_by_freq.py
  h2o-r/tests/testdir_misc/runit_relevel.R
  h2o-r/tests/testdir_misc/runit_relevel_by_freq.R
  h2o-r/tests/testdir_misc/runit_relevel_by_freq_hair.R
Labels: bug

#15882 [GH-15851] Bring 3.44 release blog to user guide
  h2o-docs/src/product/blog-releases.rst
  h2o-docs/src/product/images/blog/rel-3-44.png
Labels: docs

#15884 [GH-15881] Added K8s security note
  h2o-docs/src/product/cloud-integration/kubernetes.rst
Labels: docs

#15904 [GH-15903] 3.44.0.2 Release Notes
  Changes.md
Labels: docs

#15902 [GH-15817] Improve default threshold API and doc for binomial classification
  h2o-docs/src/product/performance-and-prediction.rst
Labels: docs

#15899 GH-15894: Make sure the functions that are supposed to be exported are exported in the R package
  h2o-docs/src/product/data-science/model_selection.rst
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/logging.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/R/tf-idf.R
  h2o-r/h2o-package/R/zzz.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/scripts/h2o-r-test-setup.R
  h2o-r/tests/runitUtils/utilsR.R
  h2o-r/tests/testdir_algos/coxph/runit_coxph_cancer.R
Labels: please review

#15917 GH-15916: Speed up Friedman-Popescu's H
  h2o-algos/src/main/java/hex/tree/FriedmanPopescusH.java
  h2o-py/tests/testdir_algos/gbm/pyunit_h_gbm_duration_large.py
Labels: please review

#15898 GH-15887: allow Py H2OFrame constructor to accept an existing H2OFrame
  h2o-py/h2o/frame.py
  h2o-py/h2o/h2o.py
  h2o-py/h2o/utils/shared_utils.py
  h2o-py/tests/testdir_apis/Data_Manipulation/pyunit_h2oH2OFrame.py
Labels: python, bug

#15957 GH-15956: Fix R tests - explain and parquet_pubdev7293 by making some internal functions available during the test run
  h2o-r/scripts/h2o-r-test-setup.R
Labels: please review
