Repository h2oai/h2o-3, pull requests merged in 2023-10, with the labels that each got.

#15645 GH-15643: Fix wrong {in,ex}clude_explanation parameter validation
  h2o-py/h2o/explanation/_explain.py
  h2o-py/tests/testdir_misc/pyunit_explain.py
Labels: please review

#15786 [GH-15785] 3.42.0.4 Release Notes
  Changes.md
Labels: docs

#15671 GH-15669: fix R package
  h2o-r/h2o-package/R/connection.R
  h2o-r/h2o-package/R/zzz.R
  make-dist.sh
Labels: please review

#15812 [GH-15811] 3.44.0.1 Release Notes [no check]
  Changes.md
Labels: docs

#15875 [nocheck] fix broken link in r doc to fix CRAN checks
  h2o-r/h2o-package/R/frame.R
Labels: docs, R, documentation, CRAN

#15874 [nocheck] README visible links for communication channels
  README.md
Labels: docs
