Repository h2oai/h2o-3, pull requests merged in 2023-09, with the labels that each got.

#15592 GH-6783 Add custom metric function to UpliftDRF
  h2o-algos/src/main/java/hex/schemas/UpliftDRFV3.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/main/java/hex/tree/uplift/UpliftDRF.java
  h2o-algos/src/main/java/hex/util/EffectiveParametersUtils.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelMetricsBinomialUplift.java
  h2o-core/src/main/java/hex/ScoreKeeper.java
  h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialUpliftV3.java
  h2o-docs/src/product/data-science/algo-params/upload_custom_metric.rst
  h2o-docs/src/product/data-science/upliftdrf.rst
  h2o-py/h2o/estimators/uplift_random_forest.py
  h2o-py/h2o/h2o.py
  h2o-py/h2o/model/metrics/uplift.py
  h2o-py/h2o/model/models/uplift.py
  h2o-py/tests/pyunit_utils/utils_model_metrics.py
  h2o-py/tests/testdir_algos/uplift/pyunit_custom_metric_uplift.py
  h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_api_test.py
  h2o-py/tests/testdir_misc/pyunit_make_metrics.py
  h2o-r/h2o-package/R/classes.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/R/upliftrandomforest.R
  h2o-r/tests/testdir_algos/uplift/runit_uplift_smoke.R
  h2o-r/tests/testdir_misc/runit_make_metrics_uplift_binomial.R
Labels: please review

#15770 GH-15727: add write_checksum parameter on data export feature
  h2o-core/src/main/java/water/api/FramesHandler.java
  h2o-core/src/main/java/water/api/schemas3/FramesV3.java
  h2o-core/src/main/java/water/fvec/Frame.java
  h2o-core/src/main/java/water/parser/BinaryFormatExporter.java
  h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/FrameParquetExporter.java
  h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetExporter.java
  h2o-py/h2o/h2o.py
  h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2oexport_file.py
  h2o-r/h2o-package/R/export.R
  h2o-r/tests/testdir_misc/runit_export_file_csv.R
  h2o-r/tests/testdir_misc/runit_export_file_parquet.R
  h2o-r/tests/testdir_misc/runit_export_parquet_multipart.R
Labels: feature

#15615 GH-15556 Implement UpliftDRF MOJO
  h2o-algos/src/main/java/hex/schemas/UpliftDRFModelV3.java
  h2o-algos/src/main/java/hex/tree/Score.java
  h2o-algos/src/main/java/hex/tree/SharedTree.java
  h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
  h2o-algos/src/main/java/hex/tree/uplift/UpliftDRF.java
  h2o-algos/src/main/java/hex/tree/uplift/UpliftDRFModel.java
  h2o-algos/src/main/java/hex/tree/uplift/UpliftDrfMojoWriter.java
  h2o-algos/src/main/java/hex/tree/uplift/UpliftDrfPojoWriter.java
  h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
  h2o-algos/src/test/java/hex/tree/uplift/UpliftDRFTest.java
  h2o-core/src/main/java/hex/AUUC.java
  h2o-core/src/main/java/hex/Model.java
  h2o-core/src/main/java/hex/ModelMetricsBinomialUplift.java
  h2o-core/src/main/java/water/api/ModelMetricsHandler.java
  h2o-core/src/test/java/hex/AUUCTest.java
  h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoFactory.java
  h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/upliftdrf/UpliftDrfMojoModel.java
  h2o-genmodel/src/main/java/hex/genmodel/algos/upliftdrf/UpliftDrfMojoReader.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
  h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/UpliftBinomialModelPrediction.java
  h2o-py/h2o/h2o.py
  h2o-py/h2o/model/model_base.py
  h2o-py/h2o/model/models/uplift.py
  h2o-py/tests/testdir_misc/pyunit_make_metrics.py
  h2o-r/h2o-package/R/models.R
  h2o-r/tests/testdir_misc/runit_make_metrics_uplift_binomial.R
Labels: please review, Uplift Trees
