Repository h2oai/h2o-3, pull requests merged in 2024-04, with the labels that each got.

#16132 GH-16131: Adding 3.46 release blog to the user guide
  h2o-docs/src/product/blog-releases.rst
  h2o-docs/src/product/images/blog/rel-3-46.png
Labels: docs

#16003 GH-15988: Craft Isotonic Regression Examples
  h2o-bindings/bin/custom/python/gen_isotonicregression.py
  h2o-py/h2o/estimators/isotonicregression.py
Labels: docs

#16018 GH-16016: Craft Uplift DRF Example
  h2o-bindings/bin/custom/python/gen_upliftdrf.py
  h2o-py/h2o/estimators/uplift_random_forest.py
Labels: documentation

#16035 GH-6722 constraint glm
  h2o-admissibleml/src/test/java/hex/Infogram/InfogramCVValidTest.java
  h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
  h2o-algos/src/main/java/hex/glm/CoefIndices.java
  h2o-algos/src/main/java/hex/glm/ComputationState.java
  h2o-algos/src/main/java/hex/glm/ConstrainedGLMUtils.java
  h2o-algos/src/main/java/hex/glm/GLM.java
  h2o-algos/src/main/java/hex/glm/GLMModel.java
  h2o-algos/src/main/java/hex/glm/GLMTask.java
  h2o-algos/src/main/java/hex/glm/GLMUtils.java
  h2o-algos/src/main/java/hex/gram/Gram.java
  h2o-algos/src/main/java/hex/optimization/OptimizationUtils.java
  h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
  h2o-algos/src/main/java/hex/schemas/GLMV3.java
  h2o-algos/src/test/java/hex/glm/GLMConstrainedTest.java
  h2o-algos/src/test/java/hex/optimization/ExactLineSearchTest.java
  h2o-bindings/bin/custom/python/gen_glm.py
  h2o-core/src/main/java/water/util/ArrayUtils.java
  h2o-core/src/main/java/water/util/FrameUtils.java
  h2o-py/h2o/estimators/glm.py
  h2o-py/h2o/model/model_base.py
  h2o-py/tests/pyunit_utils/__init__.py
  h2o-py/tests/pyunit_utils/utilsPY.py
  h2o-py/tests/pyunit_utils/utils_for_glm_tests.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_beta_equality_loose_lessthan_linear_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_beta_linear_constraints_binomial_objective_likelihood.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_constraints_on_collinear_cols1.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_constraints_on_collinear_cols2.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_equality_constraints_only_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_equality_loose_lessthan_linear_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_glm_coefNames.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_light_tight_beta_equality_lessthan_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_light_tight_equality_lessthan_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_light_tight_linear_constraints_only_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_linear_constraints_error.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_loose_beta_linear_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_loose_only_linear_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_redundant_constraints.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_separate_linear_beta_gaussian.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_tight_beta_equality_linear_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_tight_equality_linear_constraints_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_GH_6722_tight_linear_constraints_only_binomial.py
  h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_7730_plot_pr_xval.py
  h2o-r/h2o-package/R/glm.R
  h2o-r/h2o-package/R/models.R
  h2o-r/h2o-package/pkgdown/_pkgdown.yml
  h2o-r/tests/testdir_algos/glm/runit_GH_6722_redundant_constraints.R
  h2o-r/tests/testdir_algos/glm/runit_gh_6722_glm_coefficient_names.R
Labels: please review, please high-level review
